### PR TITLE
Added A-B marks to favorites

### LINKED ISSUE #450: [Request] Save A-B loop marks on favorites
It would be great if we could have the option to have our variables such as [ A - B ] Marks be remembered for that particular file when we add it to favorites.

Thanks for the great work on this great player and taking up development.

### PR DESCRIPTION
**Pull request by cw2**
Resolves #450

Added new checkbox **Remember A-B repeat marks** to **Add Favorite** dialog.

Notes:
- The checkbox is enabled only in file playback mode and if at least one repeat mark is set,
- The format of the stored favorite is fully backward-compatible, A-B marks are appended to position with a non-numeric delimiter, i.e. `StartPos[:[A][-B]]`, for example `1234:5555-6666` - so the old start position parsing `scanf("%I64d")` reads the digits up to `:` and then stops. The new parsing `scanf("%I64d:%I64d%I64d")` then continues to read A-B marks and uses the negative sign to determine the B mark, for example `1234:-6666`,
- The playback starts at Mark A, if set.

### CODE REVIEW

**Comment by clsid2** [comment]
The favorite value is a semicolon separated string. So you can split it and then parse the individual values. The AB values can be appended to the end I think.

**Comment by cw2** [comment]
Well, I did not really want to append A-B mark values to the end of the favorite string, because the last part is a file path or URL and semicolon is legal character for both; also the existing code passes the remaining CAtlList<CString> args for further processing (I have not checked the details).

But, I can of course append them to the end, if you want.

**Comment by cw2** [comment]
~~Regarding the semicolon in favorite file path or URL: there is a bug in my code, parsing resp. splitting the favorite string should be limited to 3 parts in order not to split file path/URL (it was correct in the original `ExplodeEsc(..., _T(';'), 3)` call).~~

Edit: Correction, there was actually bug in the original code, ExplodeEsc limit to 3 parts leaves RemoteDrive merged with the file path/URL.

**Comment by clsid2** [comment]
Why not use `1234:5555:6666` to avoid negative sign?

**Comment by cw2** [comment]
> Why not use `1234:5555:6666` to avoid negative sign?

Yes, this can be used too, I can change it, no problem...

However, using the negative sign has one very minor benefit (besides it looking more like A-B range): in case there is only B mark set, scanf parsing `1234::6666` will return 2, which would need additional checking to distinguish from `1234:5555:`. The negative sign eliminates that additional check, because it becomes part of the mark value, virtually eliminating the delimiter. Of course the values can be saved with explicit zeros like `1234:0:6666` or `1234:5555:0`, but the code should not depend on it, resp. should handle the worst case (wrong or missing A-B mark values).

**Comment by clsid2** [comment]
It should always store both AB mark values if either one is set. So either `1234` or `1234:0:6666` are valid. Using separate values has less chance of future bugs than the negative sign.

**Pull request merged**
