### PR TITLE
Allow skipping past unopenable files

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
Tried it and it correctly skips past unrenderable files. Good.

If I open a bad file directly then ideally the skip forward/back buttons should be enabled. Actually, also after closing a good file (with Ctrl+C).

Skipping also does not work after deleting a played file with the hotkey (and playlist size = 1). I don't know if the file search function works with a file that no longer exists, so maybe previous/next filename needs to be stored before doing the file delete.

**Comment by adipose** [comment]
First issue I can look at.

As for the second issue, if the search function could use the string of the original bad file, even if deleted, it might work.  Basically it would have to detect where the deleted file belong if it were added to the sort.

**Comment by adipose** [comment]
First issue seems to be working.

Second issue is pretty simple to add, I think.  I'll see.

**Comment by clsid2** [comment]
It works. But it only does not yet properly check if the failed/closed item in the playlist is a local file. That check should be added to CanSkipFromClosedFile function. If it contains "://" it is an URL instead of a file.

**Comment by adipose** [comment]
OK, check it out now.

**Pull request merged**
