### PR TITLE
fix for PGS subtitles

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
This is not a desired solution. Videos are often cropped (black bars removed) and we want to be able to place the subtitles below the video in that case.

Better solution would be to follow the positioning option from the settings to give user control.

When positioning relative to the window we could place a restriction on the height of the subtitle area to avoid the problem from the bug report. So if we restrict to max 16:9 AR that means:
max_subarea_height = window_width x 9 / 16
subarea_offset_from_top = (window_height - max_subarea_height) / 2

And in case the window is widescreen (21:9 monitor) we could restrict the width of the subtitle area.

**Comment by adipose** [comment]
The problem I was trying to fix is the aspect ratio of the subtitles is altered according to the window size.  The actual offset of the subs should be fixable.  What seems to be happening is this: the subs are rendered according to the video aspect ratio, and then stretched to the window aspect ratio.  It makes no sense the way it is, now.

Perhaps your idea would work.  I was thinking we need to tell the subs the size of the "video" area matches the size of the window.  Why do the subs need to know the video is 1920/1080, if the rendering choice is based on the window and not the video?

**Comment by adipose** [comment]
I have also confirmed the same issue exists with DVBSub.

**Comment by adipose** [comment]
Here's some examples of what it does.  Personally, I think rendering on the video is actually preferred to what it does here.  Note the text is actually stretched and quite far from the video frame.

image

image

image

**Comment by adipose** [comment]
See what you think of these changes.  Honestly, it seems more like a fluke/bug that the subs could previously appear in the letterbox areas.  Nothing was really programmed to make this work properly--setting the subs relative to the window had the appearance of doing this, but it wasn't really working correctly.

If a sub was supposed to be 216 pixels from the bottom of a 1080 video, and the frame was changed to 2000 pixels, that sub would be 400 pixels from the bottom of the frame, and would grow in height by 85% (making tall skinny fonts).  But the 216 was carefully chosen to sit a certain distance from the bottom of the video--it is somewhat arbitrary when applied to the window frame.

I don't think the program actually knows in advance the space needed for the subs, you just assume they are placed correctly.  So there's no way to really know where you need to move them if you have arbitrary black bars.  But what I did was assume the subs could always move at least as far as the thickness of the black bars down, and try to go no further than 33% of the video height to keep them from floating too far away.  It would be unlikely for subs to take up more than a 3rd of the video frame, I would think.

If this is a complete waste of time or not a good solution, I'll stop messing with it!  But I am kind of a stickler for aspect ratios, and the current system is kind of wonky.

**Comment by clsid2** [comment]
Do I understand correctly that the pgs data contains information about the video size on which it should be drawn? In that case we can use that information to best fit that subtitle area in the window.

Sample with a sub at top:
https://www.sendspace.com/file/ffv00x

And pgs can also be used for motion tracking:
https://www.sendspace.com/file/6ua6uu

And I have seen cases where video was re-encoded to 720p with unmodified subs from the original 1080p video.

**Comment by adipose** [comment]
Yes it does. It then gets scaled to the draw area, which needs to be the same aspect ratio or the images will get stretched.

**Comment by clsid2** [comment]
Then solution is:
Subpic texture size = video resolution as defined in the pgs
Draw area = largest rectangle of same AR within the window

**Comment by adipose** [comment]
That seems reasonable.  However, I didn't know how to control the draw area as the system basically offers two options: either relative to the video or the window frame.  But maybe I can override the window frame it thinks it's rendering to.

What I did instead was tell it to render to the video size, but shift the vertical offset if there is room below.

Note that there are a number of maximum size frames that are the same aspect ratio within the window if the window is stretched vertically.  One of the maximum size would be the video area itself.  Another would be offset by one pixel.  Another would be offset by two pixels.  Etc.

So, presumably we should center it vertically.  Which in the case of the video being non-cropped, leaves the subs right on the video.  In the case of it being cropped, it will show up  at least partially in the black bar area.

**Comment by clsid2** [comment]
Yes, it should be centered. So ultimately it will end up in the same position as originally intended by the creators of the video.

**Comment by adipose** [comment]
I think the best fit option was what we were looking for.  It works with the motion tracking, as well as cropped videos.  And uncropped videos keep the right aspect ratio.

The only "issue" with best fit is if a very narrow view is used on a cropped video, the subs will be off the view (where they rightly belong). You would have to expand the view to a full 720/1080 to see them.  But I think it's a reasonable compromise, because trying to smash them onto the video would screw up things like motion tracking.

**Comment by clsid2** [comment]
Subs should also be visible when watching a cropped video at 100% size. In that case the subtitle area should be downscaled to fit within the video area. Subs will appear smaller than normal, but that's better than falling outside the visible area.

**Comment by adipose** [comment]
If we do that, the motion tracking blocks will get distorted and not match the right positions.  Is that acceptable?

**Comment by clsid2** [comment]
Why would it be distorted in that case? That isn't a cropped video as far as I know.

What I mean is, suppose we have a 1920x1080 video with pgs subs that define that same size. Video is cropped to 1920x800 during re-encode. If we watch this fullscreen on a 1920x1080 monitor, we can render subs at 1920x1080 as well. With a 1920x1200 monitor, subs also get rendered at 1920x1080 (and centered vertically). If we watch that video at 1920x800 size, then subtitle area is 1422x800 (centered horizontally).

**Comment by adipose** [comment]
That video would not be distorted (although it currently _is_ distorted if the video frame is stretched).  But any video that had cropping + PGS has the potential to have distortion if we don't honor the original positions.  Surveillance videos are unlikely to be cropped--but it's not impossible.

I understood what you were proposing, and in the case of simple subs, it should work.  I will see if that can be done easily.

For what it's worth, the existing "xysubs," which I assume refer to subs with specific XY positions, are using "BEST_FIT" already.

**Comment by adipose** [comment]
Here is what the motion tracking looks like with a stretched video frame, prior to my changes:

image

After changes:

image

**Comment by adipose** [comment]
OK!  I think this adds the feature of forcing subs in a cropped video to show up, even if the window isn't sized big enough to see the letterbox areas.

**Pull request merged**
