### PR TITLE
Fixed the resource updater reading mpc-hc.rc with the incorrect encoding when it is encoded as UTF-8 without bom

### PR DESCRIPTION
**Pull request by Sp3EdeR**

### CODE REVIEW

**Comment by clsid2** [comment]
This might break things. Everything is currently working, so you probably changed the encoding of the rc file if you are having issues?

**Comment by Sp3EdeR** [comment]
Well, I checked the file in a hex editor before I touched it for the first time (4db1199ddb10e567eb48e8853832e0853ff6cc9d), and I saw no BOM in it, and it showed as a UTF-8 file. Right now, in my environment, I'm seeing the same thing - no BOM and UTF-8 contents. So I thought that the script should follow this trend.
What I don't get is how it works for you. Git might be changing the encoding or BOM on commit/checkout perhaps. If you could check the encoding and BOM-edness of your mpc-hc.rc, perhaps we could figure out the cause of the difference.

**Comment by clsid2** [comment]
We had issues with this in past, so I am not keen on changing anything.

Notepad++ shows "UCS-2 LE BOM" which is UTF-16LE.

**Comment by Sp3EdeR** [comment]
Thanks for checking! Then I suspect that your Git may be changing the encoding on checkout due to a setting or hook. I'm pretty sure that the actual format that's stored in the repo is UTF-8 without BOM (https://raw.githubusercontent.com/clsid2/mpc-hc/develop/src/mpc-hc/mpc-hc.rc). But since your file has a BOM, this change should have no effect on your environment. It only reinterprets BOMless mpc-hc.rc files from UTF16 to UTF8.
Alternatively, it would also be an option to use [chardet](https://pypi.org/project/chardet/) to detect the encoding reliably, but that would introduce an additional pip dependency...
Or I could use this modification locally on my end. But where one person has trouble, there usually are more.

**Comment by ale5000-git** [comment]
@Sp3EdeR: It is your git client that doesn't support "working-tree-encoding".

From here: https://git-scm.com/docs/gitattributes/2.19.2
```
Alternative Git implementations (e.g. JGit or libgit2) and older Git versions (as of March 2018) do not support
the working-tree-encoding attribute. If you decide to use the working-tree-encoding attribute in your repository,
then it is strongly recommended to ensure that all clients working with the repository support it.

For example, Microsoft Visual Studio resources files (*.rc) or PowerShell script files (*.ps1) are sometimes encoded in UTF-16.
If you declare *.ps1 as files as UTF-16 and you add foo.ps1 with a working-tree-encoding enabled Git client, then foo.ps1
will be stored as UTF-8 internally. A client without working-tree-encoding support will checkout foo.ps1 as UTF-8 encoded file.
This will typically cause trouble for the users of this file.

If a Git client, that does not support the working-tree-encoding attribute, adds a new file bar.ps1, then bar.ps1 will be
stored "as-is" internally (in this example probably as UTF-16). A client with working-tree-encoding support will interpret
the internal contents as UTF-8 and try to convert it to UTF-16 on checkout. That operation will fail and cause an error.
```

**Comment by Sp3EdeR** [comment]
Ah, good point @ale5000-git, thanks! My git version was too old and did not support that switch. It works fine after the update!

As for this PR... I don't think it should cause issues, since all the processed RC files have a UTF16 BOM. It should only fixes issues for git clients that don't support `working-tree-encoding`. Resource building still works well after the git update.

**Comment by clsid2** [comment]
It was changed here:
https://github.com/clsid2/mpc-hc/commit/d740a8e3ac9f47b67a1b5818f85acf8427f4ddde

**Comment by Sp3EdeR** [comment]
@clsid2 when d740a8e3ac9f47b67a1b5818f85acf8427f4ddde was commited, the `working-tree-encoding=UTF-16` git attribute was used, which means the `mpc-hc.rc` would be checked out as UTF 16 LE without BOM at that time.

At 4c080e90ed1ba962977b9f7fdd65520803f9f47a, you changed that to `working-tree-encoding=UTF-16LE-BOM`. This change caused the `TranslationData.py` to change to the `elif raw.startswith(codecs.BOM_UTF16_LE):` branch instead, leaving the default setting unused.

**Pull request merged**
