### PR TITLE
improve utf-8 comments in textfile.cpp

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by adipose** [comment]
For what it's worth, there are non-emoji characters starting at 0x10000:

https://www.utf8-chartable.de/unicode-utf8-table.pl?start=65536&unicodeinhtml=dec

I believe emoji start at 0x1F600.  Not sure how much of a problem this really represents.

**Comment by adipose** [comment]
So, I tested it out some more, and found that certain Japanese characters require 4-bytes.  So, I've added support to the patch.

```
1
00:00:01,000 --> 00:00:02,500
𩸽 (japanese hokke, U+29E3D)
```

**Comment by adipose** [comment]
This does leave a bad character (square char) for emoji. I am working on excluding them.

**Comment by adipose** [comment]
I understand why it says 16 bit. It's mapping everything to wchar which are only two bytes.

So the resulting utf16 data can only handle the basic multilingual plane.

Any value > 0xffff isn't assignable using this method (same as handled by 3 byte utf8).

**Comment by ale5000-git** [comment]
> 
> 
> This does leave a bad character (square char) for emoji. I am working on excluding them.

Why exclude them?
I think is the normal way to display a square when a character isn't supported by the current font.
The user should know there is something (in my opinion).

**Pull request merged**
