### PR TITLE
Transifex updates

### PR DESCRIPTION
**Pull request by adipose**
Updated translations
Fix for line endings
Support ordered string substitution for CN

### CODE REVIEW

**Comment by clsid2** [comment]
Github shows some merge conflicts.

**Comment by adipose** [comment]
@clsid2 

Should be fixed.  The script had a bug when the source POT file had \r\n, which created a single extra blank entry in every PO file.  I fixed the bug but the bad POs got merged in between.   I must have missed merging the upstream when I fixed it.

**Comment by clsid2** [comment]
There is a bug somewhere in the line ending changes. The translations get lost when running the script:
mpc_po_bug

**Comment by adipose** [comment]
That is strange, as I always run the script before committing my changes.  I backed it up, and ran sync.bat, and compared it.

image

There was a bug like you mention, but I thought I had fixed that one.

**Comment by clsid2** [comment]
I figured out it is related to this Git setting which controls line-endings:
core.autocrlf = true (checkout Windows style line endings, commit as Linux style)

You might be using a different value.

**Comment by adipose** [comment]
Yes, mine is false.  Transifex is committing as linux, so with this setting I can probably revert the changes to the script.

**Comment by adipose** [comment]
@clsid2 I reverted the change to that script, and used the autocrlf setting.

Given that the script is dependent on the line endings being in windows format, perhaps we should add a unix2dos in the script, or else set core.eol for each of those files.

**Pull request merged**
