### PR TITLE
avoid OSD floating outside main window

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by adipose** [comment]
@clsid2 , did this help when switching windows (vs minimizing)?

I also can see times when the OSD is over an overlapped window.  I don't know why topmost is necessary.

**Comment by clsid2** [comment]
Still happens

**Comment by adipose** [comment]
`WS_EX_LAYERED` is only supported on Windows7 for topmost windows.  I suspect this is why it is set to TOPMOST for Windows 7.  However, if we disable OSD transparency on Windows7, then there really is no problem if layered isn't supported (it's a performance thing for alpha-blending, mostly).

However, I cannot quite reproduce the weird issue that I can in mpc-hc, where it can do this:

image

So if I can figure that out, maybe I can fix the real problem.

**Comment by clsid2** [comment]
I am fine with only allowing transparency on Win8+.

But I am curious if there are any OSD code differences with BE, since it does not happen there.

**Comment by adipose** [comment]
Solved with this code:

image

The comment here suggests that it's to be done only once.  But the code does no such thing (I added firstRun bit).  Without setting this window ordering at least once (after creating the OSD), the OSD doesn't come immediately after the main window in the z-order.

**Pull request merged**
