### PR TITLE
save mediainfo to current file folder

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
Probably better and simpler to just use a generic filename for URLs like `online_stream`.

**Comment by adipose** [comment]
Do you mean across the board or just in this function?

**Comment by clsid2** [comment]
In this function.

But could maybe be done elsewhere too, I haven't checked.

**Comment by adipose** [comment]
Oh, you mean we just throw out the url name entirely.

If the stream is a filename maybe it's worth keeping.  But many urls are messy, it's true.

**Comment by clsid2** [comment]
Yes, so it will become `online_stream.mediainfo.txt`
User can change it to desired name in the save dialog.

In most cases URLs are indeed messy and no proper filename can be extracted. Even a domain is not really useful.

Plus this save function will probably not get used often at all for URLs.

**Pull request merged**
