### PR TITLE
More improvements to favoriteorganize dialog

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
I noticed that when loading the player, the favorites dialog is visible for a fraction of a second. Can that be fixed?

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1649

I also noticed it has the same peek preview issue, fixed here as well.  The subtitle download dialog doesn't _seem_ to have the initial display bug, but there's no reason it shouldn't.  The same fix could work there, but I see that other code kind of assumes that window is already created.  There's another way to start it as hidden, though--I could implement it if necessary.

**Comment by clsid2** [comment]
I have never seen the subtitle dialog being visible at start.

**Comment by adipose** [comment]
I found the difference.

`EnableSaveRestore(IDS_R_DLG_ORGANIZE_FAV, TRUE);`

If TRUE is added here, the favorite dialog never flashes on screen.  The TRUE excludes it from remembering the min/max position.  But more interestingly, there is a weird bit of code added for MPC-HC:

In `CResizableWndState::LoadWindowRect`:

```cpp
		if (bRectOnly)	// restore size/pos only
		{
			// MPC-HC custom code
			wp.showCmd = SW_HIDE;
			wp.flags = 0;
		}
```

I confirmed that this code is what is preventing the subtitle download dialog from displaying during the `SetWindowPlacement` call.  So, it's a bit of an undocumented feature.

Favorite Organize dialog could probably use this flag--its main effect is it wouldn't remember if it had been previously maximized.  But overall, I think the code is cleaner if we prevent showing through some other method, like hiding it during initdialog.

**Comment by clsid2** [comment]
Whatever you think is best solution is fine with me.

**Pull request merged**
