### PR TITLE
fix for audio distortion on DVDs

### LINKED ISSUE #498: DVD Menu not drawn when using MPC-VR and DX11
See comments here: https://github.com/clsid2/mpc-hc/issues/464

I believe the audio issue is unrelated to this render issue.

### LINKED ISSUE #584: DVD playback speed issue with internal audio renderer
@adipose

I have gotten a few reports about this. Playback sometimes speeds up or slows down at start of a title on the disc. Happens only with internal audio renderer. Probably related to the clock fix we did for MPCVR,

Seems to happen on titles where audio starts later than the video.

### PR DESCRIPTION
**Pull request by adipose**
Fixes https://github.com/clsid2/mpc-hc/issues/584
Seems to have fixed https://github.com/clsid2/mpc-hc/issues/498 as well.

### CODE REVIEW

**Comment by Aleksoid1978** [comment]
After this fix - there is little A/V desync after start playback(if do seeking all is good).
Test on this DVD - https://1drv.ms/u/s!Aoq8mAMlVv8UmlHwRch7FsWmk_Qg?e=AZQ2IW

**Comment by adipose** [comment]
I tested on this DVD using latest, and I found no audio sync issues.  I let it play from the beginning, and the audio seemed right on where it should be.

What am I doing wrong?

**Comment by Aleksoid1978** [comment]
I test in debug build, later build release and check again:)

**Comment by Aleksoid1978** [comment]
Check in Release version - the same.
If start playback - at the beginning, at about 00:30, when the girl starts singing, her voice does not coincide slightly with the movement of her lips. You just have to take a closer look. If do seeking - all perfect.

**Comment by adipose** [comment]
I did the same test. If there is a sync issue it's too subtle for me to notice! I was watching lips and saw no issue.

I need to understand better how these changes fix the dvd menu option, though. Perhaps something about the original DVD is broken, rather than sanear itself (before this change). But it is odd that the audio sync can break video rendering.

I suspect the buffer size is related.

**Comment by Aleksoid1978** [comment]
Hmm - very strange. I see desync on 2 different PC.

**Comment by adipose** [comment]
I'm not seeing it, but that might mean I'm just not as sensitive to it as you (I am using headphones...not sure if that should matter).

I did some more investigating, and I think I know the "problematic" line of code for the original dvd issue.  I've temporarily change it in this test build, so see if that still causes your de-sync issue.

https://mega.nz/file/EQRAjQZb#EGEGlaXyb_HulS5k5CF6b9R36yvbHOP3PltUqXJTyKQ

**Comment by Aleksoid1978** [comment]
Check on PC with Asus Xonar DG - impossible watch any DVD, fps is low, sound is broken. Test on 1.9.6/1.9.7/latest developers build/test version.

P.S. I think i know what's happened. In 1.9.6 change in Sanear for DVD using event mode with minimum period(see IAudioClient::GetDevicePeriod()) - usually it's 3ms, it's bad for some sound adapter(MPC-BE using 50ms).

**Comment by adipose** [comment]
Yes, the buffer length is changed. In the latest build I reverted that and just changed the event mode.

**Comment by Aleksoid1978** [comment]
I check you latest build - not playable at all(low fps and etc).

**Comment by Aleksoid1978** [comment]
Can you set period = 50ms and give me for test ?

**Comment by adipose** [comment]
Strange, I have no performance problems with it.  

Here's a build with 50ms periodicy.

https://mega.nz/file/EEYSiKhC#iUuK35XbsHv6sJ1Q60Cnn48MADxpB98XuiFg9Y9qMsc

**Comment by Aleksoid1978** [comment]
Hmm - the same. On any DVD. Tested on Asus Xonar DG.

Version:
MPC-HC (Nightly, 64-bit)
------------------------

Build information:
    Version:            1.9.7.40 (fd277ea20-dirty) (patch142) (develop@a91c9d4)
    Compiler:           MSVC v19.27.29111
    Build date:         Aug 31 2020

LAV Filters:
    LAV Splitter:       0.74.1.64
    LAV Video:          0.74.1.64
    LAV Audio:          0.74.1.64
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

Operating system:
    Name:               Windows NT 10.0 (build 19041)
    Version:            10.0 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7 CPU         930  @ 2.80GHz
    GPU:                NVIDIA GeForce GT 1030 (driver version: 27.21.14.5167)

Filters currently loaded:
  - Internal Audio Renderer
  - Enhanced Video Renderer (custom presenter)
  - Audio Switcher
  - LAV Video Decoder (internal)
  - LAV Audio Decoder (internal)
  - DVD Navigator

fps

**Comment by adipose** [comment]
I was testing with mpcvr. Fix was only needed with mpcvr, actually...maybe we can isolate it there.

**Comment by Aleksoid1978** [comment]
With MPC-VR the same.

**Comment by adipose** [comment]
Can you upload your settings?

**Comment by clsid2** [comment]
I get stable 23.97 fps with that test DVD and build from above. Tried both software decoding and DXVA2 native.

I notice in your screenshot that on first line it says Clock 56%. So there is a large clock deviation somehow.

**Comment by Aleksoid1978** [comment]
As I say - this situation only on Asus Xonar DG, on Nvidia 960 all is ok.

**Comment by Aleksoid1978** [comment]
In MPC-BE good on any sound adapter.

**Comment by Aleksoid1978** [comment]
> 
> 
> Strange, I have no performance problems with it.
> 
> Here's a build with 50ms periodicy.
> 
> https://mega.nz/file/EEYSiKhC#iUuK35XbsHv6sJ1Q60Cnn48MADxpB98XuiFg9Y9qMsc

I don't know what you do - but here is small patch changing periodicy for event mode(from minimal to default), with him all is good on Asus Xonar DG

[sanear_event_periodicy.diff.zip](https://github.com/clsid2/mpc-hc/files/5159267/sanear_event_periodicy.diff.zip)

P.S. But A/V desync is present on test DVD :)

**Comment by adipose** [comment]
Although I cannot duplicate your issue, I can see it could be caused by the patches I submitted. But without these patches, the original test DVD crashes mpc-hc when using mpc-vr. I cannot reproduce that error any other way, personally.

Something with the buffer or periodicy must be causing it, but the real issue may be with the event callback code. I do wonder if there is a bug in mpc-vr, that is avoided when using mpc-ar.

Mpc-be has trouble with that test DVD too, but only in DX11 mode.

**Comment by Aleksoid1978** [comment]
In MPC-BE there is no crash with any DVD when using MPC VR.

**Comment by adipose** [comment]
It doesn't crash but I believe the menu didn't work. Maybe I mis-remembered.

**Comment by Aleksoid1978** [comment]
https://1drv.ms/u/s!Aoq8mAMlVv8Ul1tXuHPKJlDTuEwO?e=3Uy59p - the same A/V desync after start playback, normal after seeking :)

**Comment by lifegpc** [comment]
@Aleksoid1978 It seems works fine on my machine. Compare with the Blu-ray version, it seems OK for me.

**Comment by clsid2** [comment]
Does it play correctly with MPC-BE AR as external filter in MPC-HC?

**Comment by adipose** [comment]
I haven't tried it yet, but I thought mpc-ar was an internal library and not loadable externally.

**Comment by Aleksoid1978** [comment]
Trying 
[MpcAudioRenderer.ax.zip](https://github.com/clsid2/mpc-hc/files/5162650/MpcAudioRenderer.ax.zip)

**Comment by clsid2** [comment]
I have added patch to recognize it as audio renderer. It fails to complete graph if audio switcher is disabled. I have not yet investigated what is going wrong. But works fine with switcher enabled.

**Comment by clsid2** [comment]
And debug build hangs in "Opening..." state even with switcher enabled. Weird thing is that playback starts.

**Comment by Aleksoid1978** [comment]
Exclude MPC-BE AR in **CMainFrame::SetupNavStreamSelectSubMenu()**
MPC-BE AR use IAMStreamSelect for select output devices when playback. MPC-HC trying use as stream select filter.

P.S. Fix "deadlock":
[MpcAudioRenderer.ax.zip](https://github.com/clsid2/mpc-hc/files/5172871/MpcAudioRenderer.ax.zip)

**Comment by clsid2** [comment]
Thanks. I will fix that.

Perhaps it is a good idea for the renderer to set a different value for pdwGroup value in IAMStreamSelect::Info call. Currently it is 0 which MPC-HC (and many other players as well) will interpret as video. 1 is audio and 2 is subs. So you could use 3.

**Comment by adipose** [comment]
https://mega.nz/file/gEZFFAjR#VEGefyRVLO0H-rrEDm434llWx5__RZL66q8zVL9lXI0

@Aleksoid1978 , can you test this build?

**Comment by Aleksoid1978** [comment]
> 
> 
> https://mega.nz/file/gEZFFAjR#VEGefyRVLO0H-rrEDm434llWx5__RZL66q8zVL9lXI0
> 
> @Aleksoid1978 , can you test this build?

Perfect A/V sync. But now i can't test on Asus Xonar DG - only after weekend.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/609

What this patch does is enable AUDCLNT_STREAMFLAGS_EVENTCALLBACK, but doesn't change the buffer duration or periodicy.  In my testing, only this flag was needed to avoid the original DVD menu problem.  Oddly, enabling this while changing period actually brought back the blank menu.  Hopefully, by leaving the buffer alone, your issues are gone.

**Comment by Aleksoid1978** [comment]
As i say - minimal periodicy(usually 3ms) is bad for some sound adapter, like Asus Xonar DG & Creative X Fi Gamer.

**Comment by Aleksoid1978** [comment]
Test on Asus Xonar DG latest test build and build latest from git - very bad.
1 - In Exclusive mode audio device "not start"(playback start).

2 - In Shared mode audio device start - but there is no sound and MPC-HC hang after some(5-10) seconds.
3 - In debug mode infinity assert at AudioDeviceManager.cpp at line 59.

P.S. IAudioClient::Initialize() failed for exclusive mode because supportsExclusiveEventMode = false. But using flag AUDCLNT_STREAMFLAGS_EVENTCALLBACK.
Also - checking for supporting event mode is not working(GetDevicePropertyUint(devicePropertyStore, supportsEventModeKey)) - i check on some different PC with different sound adapter on Win 10 - always if false.

**Comment by adipose** [comment]
I'm seeing a few issues with this latest patch as well.  Stay tuned.

**Comment by adipose** [comment]
@clsid2 

I couldn't get the mpc-be AR to load.  I did regsvr32, and tried to add it as an external filter, but it doesn't show up.  What am I missing?

**Comment by clsid2** [comment]
Use latest MPC-HC dev build.

Here is fresh MPC AR build:
https://www.sendspace.com/file/yhzqsn

Then simply select it as audio renderer. No need to add to external filters. The build from Aleksoid was x86. Maybe that was your issue.

**Comment by adipose** [comment]
I had built it myself (64 bit), but the option never showed up.

**Comment by adipose** [comment]
Never mind--it was 32 bit when I built it, my mistake.

**Comment by adipose** [comment]
I see now that the 64 bit build is failing for me.  I wanted to build it to get the debug symbols.  

Here's my error:

```
2>libucrtd.lib(strnlen.obj) : error LNK2005: strnlen already defined in libmingwex.a(lib64_libmingwex_a-strnlen.o)
2>   Creating library C:\dev\mpc-be-beta_1.5.5\bin\Filters_x64_Debug\MpcAudioRenderer.lib and object C:\dev\mpc-be-beta_1.5.5\bin\Filters_x64_Debug\MpcAudioRenderer.exp
2>C:\dev\mpc-be-beta_1.5.5\bin\Filters_x64_Debug\MpcAudioRenderer.ax : fatal error LNK1169: one or more multiply defined symbols found
```

I got this before, and I think perhaps there's a special msys64 used by Aleksoid.  @Aleksoid1978, can you comment?

**Comment by adipose** [comment]
Found the mpc-be mingw archive, which is working ok now!

**Comment by Aleksoid1978** [comment]
https://sourceforge.net/p/mpcbe/code/HEAD/tree/trunk/docs/Compilation.txt, part B :)

**Comment by adipose** [comment]
I have discovered one thing.  An eight-year-old hack to ffmpeg (not in ffmpeg source) to deal with still images is causing the hangup when mousing over the menu.

https://github.com/clsid2/FFmpeg/commit/f0223a3fb24cdec38ff15d8eb28d310d1550d080

Reverting this enables the player to continue functioning fine--albeit without rendering the still (as mentioned in the hack).

In my testing, there seems to be something of a timing issue. If artificial delays are introduced, the menu can render ok as well.  It is possible that sanear is synced "too well" and due to the frame rewind, gets trapped in a waiting loop.   I don't fully understand it.  But this ffmpeg change definitely seems connected to the issue.

**Pull request merged**
