### PR TITLE
Support standalone url

### PR DESCRIPTION
**Pull request by lifegpc**
#798

### CODE REVIEW

**Comment by lifegpc** [comment]
The format now is not be used, any ideas? I also notice some bug in audio compare.

**Comment by lifegpc** [comment]
current code h265(hevc) are not included. But some sites (bilibili.com) have h265. ( current bilibili extractor in youtube-dl is very old code, So I write my own branch, the extactor result is same as in follow picture. 
image

**Comment by clsid2** [comment]
I don't really like the part where you use format value as a replacement for vcodec/acodec and then recursively call IsBetterYDLStream. That may get buggy. I prefer to compare format values separately.

For now just initially use these simple rules for streams with only format value:
- another stream with vcodec/acodec is better than a stream with only format value
- when comparing streams that both only have a format value, then pick first one where value isn't "none". If they are the same, then first one is best.

We can improve it further later. Do you have any example URLs for these situations:
- multiple extracted streams with different format values (and no vcodec info for any of them)
- at least one extracted stream with vcodec and at least one with only format
- stream with vcodec HEVC, extracted by official youtube-dl

**Comment by lifegpc** [comment]
>I don't really like the part where you use format value as a replacement for vcodec/acodec and then recursively call IsBetterYDLStream. That may get buggy. I prefer to compare format values separately.

Ok. I will remove that part code first.

**Comment by lifegpc** [comment]
I will do it tomorrow. =-=

**Comment by lifegpc** [comment]
Simple rules all done.

**Pull request merged**
