### PR TITLE
rename pan & scan to video frame

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by xLn2** [comment]
I think video frame also may not provide intended meaning. I come up with suggestion "Frame manipulation".

**Comment by tsubasanouta** [comment]
"VidFrm" also means video frame in the key options panel.

**Comment by clsid2** [comment]
I am not sure if changing `Pan&Scan` menu name after this many years is a good idea.

On Keys page, `PnS` and `VidFrm` could be replaced by `Pan Scan` and `Video Frame`.

**Comment by adipose** [comment]
Whatever you think is right.  I thought keeping the shortcuts the same as the menu would provide clarity.

Other ideas for the menu:

"P&S (adjust frame)"
"Adjust Frame (P&S)"
"Pan & Scan / Frame Adjust"

**Comment by clsid2** [comment]
PnS Frame Adjust

**Comment by adipose** [comment]
Should I change the title of the "preset" window to PnS Frame Adjust Presets ?

image

**Comment by clsid2** [comment]
Also change the VidFrm ones from Keys page?
`VidFrm Double` -> `Video Frame Double Size`

**Comment by butterw** [comment]
As mentioned in #831 VidFrm is actually useful as a search filter in the keys page. Video Frame will not be.

**Comment by adipose** [comment]
Why not?

**Comment by butterw** [comment]
try searching for frame in keys, you get all variants of:  frame-step, keyframe, frame time correction.

**Comment by adipose** [comment]
Oh, but "Video Frame" would help, right?

**Comment by butterw** [comment]
Typical users dont know what the names for the commands they are looking for. As long as all the Video Frame entries stick in a block together (in the list and as results on a search for vid or frame), it would be ok IMO.

**Comment by clsid2** [comment]
> Should I change the title of the "preset" window to PnS Frame Adjust Presets ?
> 
ok

**Comment by Rikk** [comment]
I think some reference to "Pan & Scan" should remain, as 'PnS' is not something my mind would read as Pan & Scan. At least in View/right-click menus.

**Comment by adipose** [comment]
> I think some reference to "Pan & Scan" should remain, as 'PnS' is not something my mind would read as Pan & Scan. At least in View/right-click menus.

People will get used to it--Pan & Scan is an anachronism at this point.  PnS should hopefully be enough to register with those looking for the old menu.

**Comment by tsubasanouta** [comment]
Options→Player→History
Remember last Pan & Scan zoom
Do you improve Pan & Scan to PnS Frame Adjust?

**Pull request merged**
