### PR TITLE
support style blocks: foreground and bg colors

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
In `WebVTT2SSA` use optimization at begin:
```
if (str.Find(L'<') < 0) {
    return;
} else {
   // do stuff
}
```
Otherwise slow regex and replacement code is run when unnecessary.

**Comment by ale5000-git** [comment]
@adipose: It would be nice if in case the splitter doesn't set language but the language is in the subtitles itself to display it.
It is also useful for external subtitles (not embedded in mkv).

Sample:
```
WEBVTT
Kind: captions
Language: en

00:00:03.110 --> 00:00:08.370
We produce quite a lot of data that's
immediately available to the public and
```

**Comment by pinterf** [comment]
Some fixes were needed, please have a look at
https://github.com/pinterf/xy-VSFilter/commit/6679330029816616202c68cc4862f8ce18614932
Aside from a typo, the problems emerged in multiple color text handling and when other tags appeared inside `<c....> </c>`
e.g. `<c.colorFE4D9A><b>T</b></c><c.color123456><b>u</b></c>`

**Comment by clsid2** [comment]
Applied. Thanks.

**Comment by adipose** [comment]
Breaks styles applied to tags:

```
STYLE
::cue(i) { 
	color: rgb(0,255,255);
};

STYLE
::cue(u) { 
	color: rgb(128,255,255);
};

00:00:15.0 --> 00:00:20.0 line:85%
<c.lime><i><u>italics underlined</u></i></c>
```

The u tag style should override all else and give the text a teal color.  But after your patch, it simply uses the lime color.  This doesn't follow webvtt spec.

**Comment by pinterf** [comment]
I can see. I was testing with Akari's Turing Love WebVTT.txt sample from here:
https://github.com/pinterf/xy-VSFilter/issues/18#issuecomment-803512511
It is containing such multi colored tag (each letter has a new color), with a b tag inside  (00:00:07.6829.

**Comment by adipose** [comment]
I did find a bug in the optimizer, where it could fail to apply the last unapplied style once it finds text.  Another issue you introduced:

        int dotPos = inner.Find(L".", tagPos);

tagPos is a position in the global string and breaks the find when applied to "inner".

**Comment by pinterf** [comment]
Uh, true, first, when dot was searched against globals string, I clamped dotPos not to exceed endPos, then I moved the whole assignment later to seek in inner only but did not replace tagPos start specifier. I wonder what else did I miss.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1054

You can try this patch, now.

One other thing you changed was:

`tagPos = str.Find(L">", endTag);`

What this code was supposed to do was find the next open tag, which is what the loop invariant is expecting.  Since we were closing out a tag, nothing needed to be done until the next tag was found, so we find the next tag, and continue.  However, I did discover that it had a bug, too, because of the SSA reset tag changing the string length and messing up the tagPos, so I moved that line of code down (after reverting your change).

**Comment by adipose** [comment]
Thanks for reviewing the code, btw, I did find some issues thanks to you.  I had a boolean before to track applied styles, but I forgot I never finished that code, and it didn't seem to need it (or use it) after other changes, so I removed it.  Now I see that it didn't use it because I never finished implementing that bit.  And all my test cases failed to reveal that bug.

**Comment by pinterf** [comment]
So I was on wrong way on fixing when I noticed that the 'inner' string got shifted and did not follow tag boundaries. Thanks for the insights.

**Pull request merged**
