### PR TITLE
Patch82

### PR DESCRIPTION
**Pull request by adipose**
Fix a regression with ssa files.  Not sure why it only affects those with a default style in the ssa file, but it may trigger a reload when other styles are in there.

### CODE REVIEW

**Comment by clsid2** [comment]
Applied manually

**Comment by clsid2** [comment]
Some comments for the libass branch:
1) The global setting (bRenderUsingLibass) in AppSettings isn't used at all. Instead the libass setting is stored in the default style. That seems wrong to me. It isn't a style setting.
2) The added code in SubtitleInputPin, such as SetPin and LoadASSTrack, should be run conditionally, so it is only executed if libass is enabled.
3) Toggling libass on/off during playback will probably cause issues. So stop playback before applying settings change in option dialog?

**Comment by clsid2** [comment]
@adipose

**Comment by adipose** [comment]
1. It isn't exactly a style setting, true.  I store it there only because the subtitles is a subproject which is largely unaware of the mpc-hc project, and it doesn't directly access the mpc-hc settings.  All settings are passed to the RTS via the style object, and doing more than that requires more code changes.  It can also be initiated from DirectVobSubFilter.cpp, which isn't aware of global settings, either.  A way to solve this might be to access it directly from the registry, but I don't really see any harm in storing the setting as a "style" of subtitles, as it does affect the style in some way.

2. I think this should be done in https://github.com/clsid2/mpc-hc/pull/513

3. We could do that, but by storing it in the style, I think it will have to go through a code path that reloads the subtitle if it changes.  I haven't tested it, yet.

**Comment by clsid2** [comment]
1. The new settings could be passed to the RTS using a second struct containing generic subtitle settings. I think it is a bad idea to (ab)use the style struct for it, certainly since that whole struct is stored as a single registry/ini value.

**Comment by adipose** [comment]
Problem I had was RTS is also instantiated from DirectVobSubFilter.cpp, which also doesn't have access to global mpc-hc settings.  So two classes that are unaware of mpc-hc, one instantiated from the other.  DirectVobSubFilter has a style object which it passes along to RTS.

I'm sure it could be done but I wasn't quite sure how to best change the code minimally.  Seems DirectVobSubFilter would also need the libass option passed to it somehow.

One option is to have the libass option as a field in the style object, but not store it in the default style in the registry.  That solves the problem of getting it to the subclasses without storing it in a confusing way.

**Comment by clsid2** [comment]
Do it similar as:
pRTS->SetDefaultStyle(s.subtitlesDefStyle);
For example:
pRTS->SetSubRendererSettings(s.subRendererSettings);

And store the values inside the subRendererSettings struct as separate settings in MPC-HC/DirectVobSub. See for example subPicQueueSettings.

**Comment by adipose** [comment]
@clsid2 

Where are the vobsub style settings stored, out of curiosity?  It seems vobsub has a parallel set of registry (?) entries that are similar to but different from the mpc-hc settings.  But I couldn't find them stored anywhere.

**Comment by clsid2** [comment]
vobsub subtitles are bitmaps. I don't think it uses any stored settings.

**Comment by adipose** [comment]
It loads settings from registry for default style, etc. Like subpicqueuesettings.

**Comment by clsid2** [comment]
Oh, you mean DirectVobSub (a.k.a VSFilter). I though you meant vobsub subtitle format (.idx/sub). 

HKEY_CURRENT_USER\Software\MPC-HC\vsfilter

**Comment by adipose** [comment]
@clsid2 Thanks.  I don't have such a key in my registry.  How can I most easily activate the built-in vsfilter?

**Comment by clsid2** [comment]
It is a standalone filter. Can be used with any other player as well.
Register it using: regsvr32 vsfilter.dll
After that you can select it in output settings of MPC-HC.

**Pull request closed without merging**
