### PR TITLE
Added video codec and resolution to status bar (#1264)

### PR DESCRIPTION
**Pull request by cw2**
This is first attempt on video codec (FourCC) and resolution info in the status bar - I apologize in advance for adding stuff at wrong places, I'll gladly move it to more suitable/correct locations.

Notes:
- Alternative FourCC guid detection and conversion https://stackoverflow.com/a/16591872
- Experimental: the resolution character is '×' (Alt+0215)
- TODO: CMainFrm::m_videoStatusInfo has to be cleared somewhere

### CODE REVIEW

**Comment by clsid2** [comment]
Maybe use two variablea to store the information:
m_statusbarVideoSize
m_statusbarVideoFourCC

You can clear value in CMainFrame::OnFilePostClosemedia()
Example for the audio lang in statusbar:  `currentAudioLang.Empty();`

Use a regular x character for now. I have had an issue with Unicode characters in the past in statusbar.

**Comment by clsid2** [comment]
You should be able to merge the two EnumFilters loops. You don't need IAMStreamSelect, just look at the mediatype.

**Comment by cw2** [comment]
> You should be able to merge the two EnumFilters loops. You don't need IAMStreamSelect, just look at the mediatype.

Hm, what would be the correct way to distinguish between NV12 and AVC1 that are being enumerated with the same mediatype? Unfortunately, I have only very basic understanding of DS filters...

**Comment by clsid2** [comment]
NV12 is an output mediatype, so that must have been a different pin in the filter graph.

**Comment by clsid2** [comment]
Use something like this:
```
CString fourCC;
BeginEnumFilters(m_pGB, pEF, pBF) {
    BeginEnumPins(pBF, pEP, pPin) {
        AM_MEDIA_TYPE mt;
        if (S_OK == m_pGB->IsPinDirection(pPin, PINDIR_INPUT)
                && S_OK == m_pGB->IsPinConnected(pPin)
                && SUCCEEDED(pPin->ConnectionMediaType(&mt))) {
            if (mt.majortype == MEDIATYPE_Video && GetMediaTypeFourCC(mt.subtype, fourCC)) {
                break;
            }
        }
    }
    EndEnumPins;

    if (!fourCC.IsEmpty()) {
        break;
    }
}
EndEnumFilters;
```

**Comment by cw2** [comment]
Well, I am using
```
        BeginEnumFilters(m_pGB, pEF, pBF) {
            BeginEnumPins(pBF, pEP, pPin) {
                CMediaTypeEx mtEx;
                if (S_OK == m_pGB->IsPinDirection(pPin, PINDIR_INPUT) &&
                    S_OK == m_pGB->IsPinConnected(pPin) &&
                    SUCCEEDED(pPin->ConnectionMediaType(&mtEx))) {
                    CString str = mtEx.ToString();
                    TRACE(_T("MTEX: %s\n"), str.GetString());
                }
            }
            EndEnumPins;
        }
        EndEnumFilters;
```
which produces the following output:
```
MTEX: Subtitle: UTF-8
MTEX: Audio: IEEE Float 48000Hz 6ch 9216kbps
MTEX: Video: NV12 1920x800 23.976fps
MTEX: Subtitle: UTF-8
MTEX: Audio: IEEE Float 48000Hz 6ch 9216kbps
MTEX: Video: MPEG4 Video (H264) 1920x800 23.976fps
MTEX: Audio: DTS 48000Hz 6ch 1536kbps
```
The last two are the actual audio and video streams that should be displayed in the status bar.

Edit: Both NV12 and MPEG4 have `majortype == MEDIATYPE_Video`.

**Comment by clsid2** [comment]
NV12 is the input pin of the video renderer. IEEE Float is from the input pin of audio renderer and audio switcher.

You should only look at the first pin with `majortype == MEDIATYPE_Video`.

**Comment by cw2** [comment]
> You should only look at the first pin with `majortype == MEDIATYPE_Video`.

I understand, but the problem is the first such pin is NV12 - I have run code from your example and it ends up with fourCC value being "NV12". 

You are right, NV12 is Enhanced Video Renderer input, while MPEG4 is for LAV Video Decoder (Internal). I guess it is technically correct that the fourCC value of the first video pins is returned, but it does not seem to be the expected value to be displayed in the status bar, which match the information shown in the audio/video submenus and details page of the Properties dialog (?)

**Comment by clsid2** [comment]
You are right. Keep the IAMStreamSelect code.

Only these little changes are needed:

-  Use two variables to store the information:
m_statusbarVideoSize
m_statusbarVideoFourCC
- Clear values in CMainFrame::OnFilePostClosemedia()
- Use a regular x character in resolution.
- Check if the video stream is enabled (in case there are multiple).
https://docs.microsoft.com/en-us/windows/win32/api/strmif/nf-strmif-iamstreamselect-info
pdwFlags parameter
- I think you must also call DeleteMediaType to prevent a memory leak.

**Comment by cw2** [comment]
Ok, I'll update the PR with the changes... Thank you for your patience :)

Note: Just out of curiosity, I have stepped-through pin enumeration in Details property page dialog https://github.com/clsid2/mpc-hc/blob/5b37764e7aa1082d439ee8ccd4818322a1ea5ddf/src/mpc-hc/PPageFileInfoDetails.cpp#L275-L289 that seems to be returning the desired info - but curiously it starts at the filter `pBF` = CLAVSplitterSource, while the code in CMainFrame::OpenSetupStatusBar() starts at NullTextRenderer, even though the root filter graph instance is the same (m_pGB). Perhaps the enumeration in OpenSetupStatusBar() is called too early?

**Comment by clsid2** [comment]
That segment only enumerates the pins of one filter.

But thinking of that, you could indeed just only enumerate the output pins of the source filter.  A pointer to that filter is stored as `m_pFSF` after building the graph.

**Comment by cw2** [comment]
Fixed review issues.

Notes:
- I have added only video codec fourCC and resolution, as most of the audio GUIDs are not fourCC - I would suggest to use different format of the displayed information in a future version, perhaps something like a "lightweight" CMediaTypeEx.ToString(),
- GetMediaTypeFourCC() could be made static CMediaTypeEx member function,
- CMainFrame::AppendStatusBarText2(...) is used only once, but I guess the formatting of the remaining status bar texts could be generalized (also depending on audio info mentioned above),
- I have missed Visual Studio deleting commented-out sections in the rc file - sorry about that, I'll re-add it if necessary.

**Comment by clsid2** [comment]
Yes, please get rid of the AppendStatusBarText2 function. I will be moving the formatting code around later anyway.

For audio it will indeed need a new function to map mediatypes to short and simple descriptors like "AC3" for common audio formats.

**Comment by cw2** [comment]
Removed AppendStatusBarText2 function; rebased on the latest develop.

**Comment by clsid2** [comment]
I just noticed that it only works with "LAV Splitter Source" and not with "File Source (Async)"+"LAV Splitter" combo. I will fix that later.

**Comment by cw2** [comment]
> I just noticed that it only works with "LAV Splitter Source" and not with "File Source (Async)"+"LAV Splitter" combo. I will fix that later.

What media uses "File Source (Async)"+"LAV Splitter" combo? Or better yet what is the minimal set of media I need to check to verify the feature "works" or at least did not break anything?

**Comment by clsid2** [comment]
Fixed it.

**Pull request merged**
