### PR TITLE
Adding missing header file Variables.h

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
I already fixed it by adding the missing variables in the code.

**Comment by adipose** [comment]
mpc-be has several variables in this file, and I've been adding them when it makes sense.  It might conflict once you include the file.

They are basically global constants that get used in various modules.  Might be better to have a namespace or something.

**Comment by clsid2** [comment]
If you prefer using the header, I am ok with that. Then we need to remove the variable declaration from the code. Preferably for all variables that both HC/BE have in common to keep things similar.

**Comment by adipose** [comment]
I moved the externs to Variables.h.  In mpc-be they were inlines, but your way is better, esp. since it's being modified in Mainfrm.cpp.

**Pull request merged**
