### PR TITLE
Support RAR5 format as well as other RAR formats as a file source

### PR DESCRIPTION
**Pull request by adipose**
Update unrar source version.
Small patch to unrar source
Significant changes to RARFileSource to leverage that library.
Async reading needs testing. I do not know how this occurs in mpc-hc--all reads seem to be done synchronously in my testing.

### CODE REVIEW

**Comment by clsid2** [comment]
I have applied the unrar update and also imported the original RARFileSource code into the tree. Can you make a new patch for the RARFileSource changes?

**Comment by adipose** [comment]
@clsid2 I think I saw a message from you stating you managed to cherry pick the patch.  Do I still need to apply a new patch?

**Comment by clsid2** [comment]
I cherrypicked the patches of your other PR for the keys sorting/filtering.
I wanted to split the import of RARFileSource into a separate patch. So a new patch is needed for your modifications. Or maybe rebase of this branch will work.

**Comment by adipose** [comment]
I think the changes I just pushed should do it.

**Comment by clsid2** [comment]
I will test this later. Does seeking work smoothly or does it need to read data from beginning?

**Comment by adipose** [comment]
It's smooth, because I don't allow compressed RARs, yet.  So it just has to find the position in the RAR and read from there.  In the case of multi-volume sets it may have to jump from volume to volume to find the right block.  I could make it more like the old code, which memorizes the correct volume for each block, but in testing with a 50 volume 5GB video, I had no problems.

I'd like to support all types and just let the performance be what it is, but I had an idea about creating RLE "waypoints" to make it seek faster after the first decoding for a compressed file.  But it's so deep in the code, I would likely have to reimplement it for every RAR file format (about 4 of them, I think).

A quicker solution would just be to create a thread to decode it to disk while playing, and make it wait if it hasn't decoded that block yet.

**Comment by adipose** [comment]
Here is a suite of tests I used (minus huge videos).  Extract this main rar, and inside are all the tests (rar4, rar5, single and multi-volume, and one rar5 multi-video multi-volume).

https://mega.nz/#!YJQDhQxC!mNgyJKPEfclwhjahuj0voFtAF00i-yaOJvPpoZwGzEk

**Pull request merged**
