### PR TITLE
Dynamic Toolbars

### PR DESCRIPTION
**Pull request by adipose**
1. Allows for an arbitrary layout of buttons on the toolbar, running any command in the wmcmd array.
2. Allows for a second toolbar.svg (similar to other tb names, but prefixed by "dynamic_") to use as button images.  Sequence for new buttons starts at 15.  Choosing -1 for the sequence uses the default button from the legacy toolbar, if it exists.
3. Stores layout in ToolbarLayout registry key.  Format (this results in the same toolbar layout as normal):
`<|PLAY_PLAY|-1|><|PLAY_PAUSE|-1|><|PLAY_STOP|-1|><|BUTTONSEP|-1|><|NAVIGATE_SKIPBACK|-1|><|PLAY_DECRATE|-1|><|PLAY_INCRATE|-1|><|NAVIGATE_SKIPFORWARD|-1|><|BUTTONSEP|-1|><|PLAY_FRAMESTEP|-1|><|BUTTONSEP|-1|><|DUMMYSEPARATOR|-1|><|VOLUME_MUTE|-1|>`
4. Would allow designing toolbar within MPC-HC, but beyond the scope of this addon.  I plan to make a settings page for designing it, when I get around to it.
5. Dropped support for PNG toolbars.  Honestly, it's a tiny amount of code that supported it, so maybe we don't need to remove it if people find it useful to have hand drawn buttons.

### CODE REVIEW

**Comment by clsid2** [comment]
Dropping BMP/PNG can't be done yet, because pretty much all current toolbars use those formats.

If we want people to create new extended custom toolbar designs, then we need to define a fixed template. That way the toolbars are interchangeable and we eliminate unnecessary complexity. The flexibility should be just in the order and amount of buttons and their chosen actions.

Some ideas:
1. We only support SVG and only the whole new toolbar design. So old toolbar support is dropped.
3. Separate toolbars for normal and black themes. (buttons.svg/buttons_dark.svg)
2. We display the image "as is", so similar to current colored one. No more use of the image grayer.
3. The toolbar image contains separate icons for the enabled and disabled state of a button (if relevant). Again, no more need for image grayer.
4. Maybe we can have two display states for the toolbar, one when no file is loaded and one when file is loaded. That way irrelevant icons are hidden. Might look nicer and cleaner.
4. The toolbar image contains icons for all most common actions. I can ask on Doom9 or here, which actions people would like to add to the toolbar.
5. The toolbar image contains some generic icons that we could use for uncommon actions. For example icon that shows "1"/"2"/"3" or "A"/"B"/"C". Tooltips can clarify which action is assigned in case the users forgets.
6. Is it easily possible to show a menu when clicking on a button? I already know that people will want to be able to select audio/subtitle track directly from a button.
7. Finally we need to ask some people to design a few toolbars. One to include as default and others to offer as alternative. A custom SVG one was made on Doom9 recently. I can ask same guy to maybe make another one.

**Comment by adipose** [comment]
1. Old toolbar support is basically gone--the code is still possible to enable, but for now it's hidden inside if-blocks that won't execute.  I left it in for now, as it's helpful for testing.
2. Good
3. Good
4. Good idea.  Will make code simpler.
8. I think it's possible.  I have been thinking about how best to enable such a capability.
9. Yes

Now, as for 5-7, my thinking was it's not possible to know for sure which actions users might want to enable on the toolbar.  I have built the code to enable any function that could have a hotkey attached.  That wasn't any harder than having predetermined commands.  I had thought the same as you, that the built-in toolbar should have a bunch of generic icons (1-9, A-Z would be a good start, then other common functions).  However, my thought was, if the user can assign an arbitrary action to a button, 3rd party toolbars should have unlimited buttons they can add.

We could say that the new toolbar is:
buttons 0-14 (legacy), buttons 15-30 (expanded), and any buttons after that have to be chosen manually.  From the "default" buttons we could allow automatic assignment of common commands.  For any other action, you have to choose manually.

What do you think?

**Comment by clsid2** [comment]
It seems unlikely to me that someone might choose a large number of  "uncommon" actions. And even it that would be the case for a handful of people, then we could just repeat the "generic" buttons.
So for example:
Play Pause A B C D A B Volume
I don't see how choosing an icon would be helpful? If the toolbar doesn't contain a matching icon, then there isn't a good one to choose.

**Comment by adipose** [comment]
Maybe we are talking about different things.  I was just thinking, if I didn't like the icon for a button, I could add more buttons to my toolbar svg, and use them.  Nobody else would have to use them, just me.  Someone may publish an svg with 100 icons.  Great, I can use any of them for anything I want.

**Comment by clsid2** [comment]
That would be a nightmare to configure. Users should just be able to choose the desired toolbar buttons. The button icons should be handled automatically. The users themselves are generally also not the ones making the svg images.

I want to avoid making things very complex.

We could define a standard template with minimum set of required button icons.
In addition we could, if those turn out to be insufficient, define a list of optional extra icons (with a specific defined order).
Given that the buttons are squares, we can calculate the number of icons that are available in the image based on its size. That info can be used to determine if an icon index is available or if a generic icon should be used instead.

**Comment by adipose** [comment]
Yes, I understand the users wouldn't be creating SVG images very frequently. But like they do today, they could download any toolbar someone else took the time to make (perhaps because they wanted some particular icon).

My thought was more that users may want to put some action on their toolbar, but it's not one of the predefined actions. Rather than have them submit a request for feature every time, they could just choose from the actions (similar to how they can set a hot key today) and add it to the toolbar. But for that to work, I thought they might want to choose an icon.

One possibility is just to use the first letter (A-Z icons needed) for any custom key. Another is just to make sure we have an assigned icon for every possible action we might allow. Another is to just make those text buttons instead.

**Comment by ale5000-git** [comment]
Just an idea: what about include also an empty button (in the svg file) for custom actions where inside it you can insert a letter rendered using a system installed font, if possible with CSS support (this allow infinite possibilities without change the svg file)?

Also about separators, personally I like them but maybe they can be just images in the svg rather than real separators.

**Comment by clsid2** [comment]
A few generic icons should be enough to handle 99.9% of all use cases. I am sure the designers can make something nice.
I am not interested in making things complex for just a few weirdos.

Regarding the need for having a "disabled" icon. That may not be needed for most buttons if we hide those when playback is inactive.

Make a table with "allowed" actions for mapping to a button. That way we can also exclude a few that don't make sense for using as a button.
Table contains:
- ID
- icon index enabled
- icon index disabled (or -1 if irrelevant)
- bool playback_only -> if true button is shown only when playback is active)
- function button_display(bool* show, bool* disabled) -> a function for each button to test additional conditions for showing/disabling the button. For example seek buttons should be hidden if file has no known duration.
- function button_action() -> action to perform if clicked, usually same as in the hotkey table.

The IDs do not need to be direct mappings to the hotkey list. We might think of new "actions" that are not in that list, such as showing a menu with subtitle streams.

**Comment by adipose** [comment]
I had one other thought--we could have predefined icons that have to be included in the base toolbar (say the first 15 plus 10 more).  Any time those actions are put on the toolbar, it's clear which icon to use.

If we wanted expanded icon sets beyond that, we could require an SVG of expanded icons, plus an index file indicating which commands were represented by the expanded icons.  If the action weren't in there, we could do text buttons, numbered buttons, or A-Z (though this would "work" it might be kind of ugly to have a bunch of random letters on your toolbar).

**Comment by adipose** [comment]
> 
> 
> A few generic icons should be enough to handle 99.9% of all use cases. I am sure the designers can make something nice.
> I am not interested in making things complex for just a few weirdos.
> 
> Regarding the need for having a "disabled" icon. That may not be needed for most buttons if we hide those when playback is inactive.
> 
> Make a table with "allowed" actions for mapping to a button. That way we can also exclude a few that don't make sense for using as a button.
> Table contains:
> 
>     * ID
> 
>     * icon index enabled
> 
>     * icon index disabled (or -1 if irrelevant)
> 
>     * bool playback_only -> if true button is shown only when playback is active)
> 
>     * function button_display(bool* show, bool* disabled) -> a function for each button to test additional conditions for showing/disabling the button. For example seek buttons should be hidden if file has no known duration.
> 
>     * function button_action() -> action to perform if clicked, usually same as in the hotkey table.
> 
> 
> The IDs do not need to be direct mappings to the hotkey list. We might think of new "actions" that are not in that list, such as showing a menu with subtitle streams.

OK, sounds good.

**Comment by clsid2** [comment]
Yes, that is what I meant. But without a customizable index.

New default toolbar contains:
Current icons + lots of new icons for common actions + 4 generic icons

We specify a strict list for the order in which the icons should be in the image. So each icon has a known index.
Image width/height = number of icons.

Then images are also easily comparable by looking at them. Having different orders makes that impossible.

This list has a required set of icons, plus optional ones for less common actions. The list is ordered from common to uncommon. The image designer decides till how far he goes on the list. Wanting to include icon 30 means also needing to include all icons before it. This avoids the need to parse a mapping file.

There will probably be just a few people who design a toolbar, so it should be easy and straightforward.

Also, for some of the more exotic actions I suspect it is pretty difficult to make a tiny icon that would be self-explanatory.

**Comment by adipose** [comment]
> 
> 
> Yes, that is what I meant. But without a customizable index.
> 
> New default toolbar contains:
> Current icons + lots of new icons for common actions + 4 generic icons
> 
> We specify a strict list for the order in which the icons should be in the image. So each icon has a known index.
> Image width/height = number of icons.
> 
> Then images are also easily comparable by looking at them. Having different orders makes that impossible.
> 
> This list has a required set of icons, plus optional ones for less common actions. The list is ordered from common to uncommon. The image designer decides till how far he goes on the list. Wanting to include icon 30 means also needing to include all icons before it. This avoids the need to parse a mapping file.
> 
> There will probably be just a few people who design a toolbar, so it should be easy and straightforward.
> 
> Also, for some of the more exotic actions I suspect it is pretty difficult to make a tiny icon that would be self-explanatory.

Yes, this all makes sense.  To expand on my thinking before, one user had asked for an icon to "skip ahead."  My thought was, the "next video" button looks close enough to this action that they could have just used that.  So, they specify they want "skip" and choose icon "next video" and it's good enough to satisfy them without having to design a new toolbar button.

Your solution will be simpler and easier to maintain.

**Comment by clsid2** [comment]
A "seek ahead" icon would of course be something that should be in the required part of the expanded iconset.

I think it is a good idea to get a list of actions that users want added, before starting further implementation. Then we can decide on the order of icons. And if some need a disabled state.

There are plenty common ones for which a good icon is possible: fullscreen, show playlist, select audio track, sub track, seek, open file/url, move to recycle bin.

**Comment by adipose** [comment]
For disabled image list, the typical way to do this is to have one image for all the enabled buttons, and another for all the disabled ones.  Do we want to have two SVGs for this purpose?  Or perhaps one svg with two rows, which we extract the icons from to create the two "imagelists" for MFC?

**Comment by clsid2** [comment]
Just a few of the icons need a disabled state.

Since the buttons will now be in a custom order, we could also easily have two states of the toolbar. One for when a file is loaded, and one for when not. If no file is loaded, then irrelevant icons can just be hidden instead of being disabled.

I have asked on Doom9 which things they would like to be added as buttons. A popular request so far is the ability to directly access certain submenus: recent files list, audio track selection, subtitle track selection, playback rate menu.
For normal hotkey stuff: fullscreen toggle, playlist toggle, options, file properties.

**Comment by butterw** [comment]
- Making submenus available (ex: shaders) would be nice. 
Some might not always be applicable (ex: chapters, subtitle track) in which case it would make sense to set the button to disabled state.

**Comment by adipose** [comment]
> 
> 
> Just a few of the icons need a disabled state.
> 
> Since the buttons will now be in a custom order, we could also easily have two states of the toolbar. One for when a file is loaded, and one for when not. If no file is loaded, then irrelevant icons can just be hidden instead of being disabled.
> 
> I have asked on Doom9 which things they would like to be added as buttons. A popular request so far is the ability to directly access certain submenus: recent files list, audio track selection, subtitle track selection, playback rate menu.
> For normal hotkey stuff: fullscreen toggle, playlist toggle, options, file properties.

What I mean is where to store the disabled icons themselves.  One way to support disabled buttons is to have a list of icons (imagelist) for enabled state, and another for disabled state.  If you don't supply both of these, you depend on windows to "gray out" the disabled buttons, which may not look great.

From an implementation point of view, it would be easiest to have them in two files:
buttons.svg
buttonsDisabled.svg

But it wouldn't be much harder to have one image, with the top row being enabled buttons, and the bottom row being disabled ones.

Personally, I don't like hiding icons that aren't active, because it's potentially confusing for the user.  They may not realize it's missing because it's not currently enabled, and they also may find it jarring when buttons move around depending on the state of the application.  A grayed-out button indicates that the button is there, but something about the state prevents you from using it.  But in any case, we do need to supply some disabled buttons, and I guess my preference would be for a single SVG just to make it simpler for the user.

**Comment by clsid2** [comment]
They can be in a single SVG.
play, play_disabled, pause, pause_disabled, stop, stop_disabled, etcetera.

You may be right about hiding icons being confusing.

**Comment by adipose** [comment]
This now supports a set of commands that can be specified, rather than arbitrary commands.  I've also included an SVG supported by this code, that contains all necessary for dark theme and classic theme, in one file.

image

I used one row per style (classic, classic disabled, themed, themed disabled), as this makes it easy to edit, and easy to load (one row per button list).  If buttons are scattered around, the code would have to process one button at a time and build up a toolbar image (similar to how I did before when it was arbitrary).  This code is much simpler as a result.

**Comment by adipose** [comment]
Obviously, new buttons and menus are not supported, yet.  But this lays the groundwork for dynamic toolbars.  If we intend to drop PNG toolbars, this would be sufficient to go live with equal functionality to the existing built-in svg toolbar, as well as have the ability to remove separators and buttons you don't use.

**Comment by clsid2** [comment]
Can you make a test build?

**Comment by adipose** [comment]
https://mega.nz/file/8VI3AIwC#E0soRw4B3bg5SN8-VGG07_em1zu0Pt4zUCY33dfvXjc

**Comment by evgenydzhumaev** [comment]
If you like, I have some work. There are already ready-made svgs, you can use them.
[Dropbox download](https://www.dropbox.com/s/t9m3k8yas7laf3f/mpc_toolbars_grid_svg_multicolor_pack.zip?dl=0)

**Comment by clsid2** [comment]
Accidental branch delete?

I do wish to look into this toolbar customization in the future. I like your concept of the four rows in the SVG.

**Comment by adipose** [comment]
Yep, I restored it now from git commits.  Had to make a new PR though.

**Pull request closed without merging**
