### PR TITLE
fix auto seek to DVD title with internal audio renderer

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
I get audio sync issues with this patch. Might be related to the fact that the time is only updated every 500ms. Seems to be the limitation of IDVDinfo2.GetCurrentLocation.

**Comment by adipose** [comment]
Hmm, what if you revert this:

https://github.com/adipose/mpc-hc/blob/5cc693b327ad1077be45e59832824ec810ce4917/src/thirdparty/sanear/src/MyClock.cpp

Does it make any difference? This seemed like a bug so I fixed it, but it wasn't really part of the fix.

**Comment by adipose** [comment]
@clsid2 

Another issue, it doesn't work in release mode and just shows the green highlights for the buttons.  I am not sure why it works in debug mode and not release.  Maybe a timing issue that allows the debug to draw before it goes to STILL mode.

**Comment by adipose** [comment]
Correction, it works for EVR-CP and madVR but not MPC-VR.  I'm not sure why this would be.

**Comment by clsid2** [comment]
I didn't get any menu issues. Try latest version of MPCVR.

**Comment by adipose** [comment]
Hmm, strange.  I am still getting it after installing latest MPC-VR. Maybe something else going on.

**Comment by clsid2** [comment]
I did a rebuild and sync issue seems gone now.
No menu issue here with MPCVR 0.47.1356

**Comment by adipose** [comment]
I turned off D3D11 and now it works in MPCVR.

**Pull request merged**
