### PR TITLE
review use of DT_NOPREFIX and verify it is correct for all themed controls

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
Is this a work in progress till all uses are reviewed?

**Comment by adipose** [comment]
All done.

**Comment by clsid2** [comment]
Maybe add ASSERT in the check so future missed ones can be detected in debug build?

If all current uses have been checked, then review comments can be removed?

**Comment by adipose** [comment]
Either it needs a prefix constant or I tried to note that it doesn't.

It's not documented anywhere what the behavior of common control painting is.  Perhaps a better option is to document in the theme classes what the observed painting is.

The comments aren't needed anymore but I thought they may be useful in the future to prevent re-review.

I do have one outstanding issue I observed, but it affects classic and themed.  The behavior of the setting's tree and the headers of the sheets is different.  This would only matter if either contained ampersands, which none currently do.

**Comment by clsid2** [comment]
ok, good.

Maybe just shorten it to `// DT_NOPREFIX not needed`

**Comment by adipose** [comment]
Done

**Pull request merged**
