### PR TITLE
show number of valid subtitles instead of result size

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
Maybe better to log both values?
"Results: 15, Valid: 0"

For the file in this specific issue, there is no exact filename match. Question is, should be then show inexact matches when doing a manual search?

Something like this at end of loop:
```
if (i == nCount-1 && valid == 0 && manualsearch && searchedByFileName && !allow_inexact) {
   // restart loop
   i = -1;
   allow_inexact = true;
}
```

Unrelated improvement idea: pressing the Search button while the search field is still empty should use the filename as search parameter.

**Comment by adipose** [comment]
Yeah, showing the inexact matches isn't a bad idea, though it can be a very long list sometimes.  Maybe a dialog that says no matches found, do you want to search for all similar titles?

**Comment by clsid2** [comment]
I don't think a dialog is needed, since users probably prefer long list of inexact results over no results at all. An extra option can always be added later if there are complaints.

**Comment by adipose** [comment]
OK, try it out now.  I used an outer loop for clarity.

**Pull request merged**
