### PR TITLE
port of mpc(be) audio renderer

### PR DESCRIPTION
**Pull request by adipose**
This was a big project, but I think it's working well, now.  Some thoughts:

1. mpc-be uses a custom ffmpeg build.  it creates a single lib, ffmpeg.lib (which is required for mpc-ar). I was able to build against the lavfilters libraries, but they require dlls.  These dlls would need to be available to mpc-hc, and not just lavfilters.

2. I had to link mpc-hc against several ffmpeg related libs, which I added to mpc-hc.vcxproj

3. MPC-HC already works with the installed mpc-be AR, as an external filter, but this gives us more control over the code going forward.

4. Changes to mpc-be made to support themes, and a workaround for ffmpeg linking problems (mpc-be solves by changing ffmpeg source.  I found a different approach).

5. Changes to CMPCTheme headers to avoid include problems (moved unnecessary headers to cpp when possible).

6. Fix for themed groupboxes to support SetFont call.

### CODE REVIEW

**Comment by clsid2** [comment]
Can you make a separate PR for the Theme/Propertypage changes? I prefer to have that as a separate patch that I can already apply.

Same for the Profile.h/cpp changes. And Maybe a third PR for the other support code additions in DSUtil that are not directly related to the audio renderer.

Make a copy of the FFmpeg build script files (.bat + .sh) and modify it to build in a different directory. We can later adjust the configure parameters to make a minimal build with just the required stuff. Then it adds less than 2MB instead of 10+.

**Comment by adipose** [comment]
1. Done.

2-4, will do

**Comment by clsid2** [comment]
This still uses the custom config/make files from BE. I would prefer to run configure to generate those, as that allows to easily disable all the decoders and all other unwanted stuff.

**Comment by adipose** [comment]
I built my own build script based on the be one. Some info:

1. With static build, my workaround for <initguid.h> doesn't work.  Several patches to ffmpeg are needed (in order to use these patches without changing the LAVFilters source, I need a custom makefile)
2. Build is much faster when just specifying the source files in use.
3. Custom link against mingw is needed, but I was able to make it work without using a special mingw build.  One requirement is the use of -D__USE_MINGW_ANSI_STDIO=0 (this is a semi-deprecated approach but the only way to remove the link conflicts in msys2/mingw).  mpc-be uses a special mingw build, which I think avoids this requirement.

I am thinking of trying the static build with msvc instead.  I made the debug build work with msvc before, so maybe that will work and we can avoid all the mingw problems.  I'm pretty sure the <initguid.h> problem will remain though.  Windows has a pretty ugly solution with <initguid.h> where it can only be included once per executable.  If you need to link two libs that both use it, it will break.

**Comment by clsid2** [comment]
Temporarily modify LAV script with this:
```
configure() {
  OPTIONS="
    --enable-gpl \
    --enable-version3 \
    --enable-w32threads \
    --enable-static \
    --disable-shared \
    --disable-everything \
    --disable-mediafoundation \
    --disable-schannel \
    --disable-dxva2 \
    --disable-d3d11va \
    --disable-programs \
    --disable-doc \
    --disable-avformat \
    --disable-avdevice \
    --disable-devices \
    --disable-postproc \
    --disable-swscale \
    --enable-filter=abuffer,abuffersink,atempo,aresample \
    --arch=${arch}"
```
Then look at `.\mpc-hc\src\thirdparty\LAVFilters\src\bin_Win32\thirdparty\ffmpeg`
Use the generated config.h as an example of minimal requirement.
In these folders you will find generated files. For example in libavcodec: bsf_list.c codec_list.c parser_list.c
Copy those files for use in your custom makefile.
Also adjust the makefile to include only the files that got build with this minimal script.

Right now your build includes everything, which is unacceptable, because the renderer only uses two filters from FFmpeg (atempo/aresample).

It makes me wonder if it wouldn't be easier to just rewrite the part of the audio renderer (filter.cpp) that uses FFmpeg code.

**Comment by adipose** [comment]
> It makes me wonder if it wouldn't be easier to just rewrite the part of the audio renderer (filter.cpp) that uses FFmpeg code.

I had the same thought.  I didn't dig in far enough to see how easy that would be.

>Right now your build includes everything,

Not quite.  

Quick count, there are 1060 c files in libavcodec, and my makefile only compiles ~450 of them.  I had to add a few to make it compile compared to what mpc-be used.  I considered removing as many as I could while still supporting the calls made by the AR.

It also only builds avcodec,avutil,avfilter,swresample, and swscale.

**Comment by clsid2** [comment]
codec_list.c and parser_list.c should just contain an empty list with just NULL

**Comment by adipose** [comment]
Yes, I will try that to see how it works.

**Comment by clsid2** [comment]
Here is a [patch](https://www.sendspace.com/file/hsyhx0) I made last year as a test to reduce the ffmpeg build.

**Comment by adipose** [comment]
OK, so this should minimalize it quite a bit per your suggestions.  I did make a few tweaks to remove bcrypt and other dependencies in the static lib.  If I can get it working with msvc, maybe I can exclude the gcc/mingw libs as well.

Custom .c files are no longer needed, so in theory this could be built with the configure script, provided I could get it to output a single ffmpeg.lib.

**Comment by clsid2** [comment]
If you have time, could you also look into porting these functions to SaneAR?
CMpcAudioRenderer::OnDeviceStateChanged
CMpcAudioRenderer::OnDefaultDeviceChanged
These should get triggered when for example plugging in/out headphones. It will do a re-init and switch to/from speakers.

SaneAR already has
AudioDeviceNotificationClient::OnDefaultDeviceChanged
But it doesn't seem to do anything yet.

Edit: hmm, maybe it already works #1255 and I don't understand the code correctly

**Comment by adipose** [comment]
Static msvc build is working.  This removes the dependency on mingw/gcc libs, which seems highly desirable.  Build is a bit faster, I think.

I left the mingw/gcc library utility (update_mingwlib.bat) as it may be useful in the future if we have mingw dependencies.

**Comment by clsid2** [comment]
I had to make these changes in config.h to fix compilation of FFmpeg:
`#define av_restrict`
`#define HAVE_UNISTD_H 0`

**Comment by clsid2** [comment]
It would be nice to have a config button behind the renderer list dropdown to access the settings of the renderer. Similar to in MPC-BE.
If possible move SaneAR settings into a separate dialog as well. That is less confusing than current situation with settings on two pages.

MPCAR does not seem to do pitch correction when speeding up video?

**Comment by adipose** [comment]
> 
> 
> I had to make these changes in config.h to fix compilation of FFmpeg:
> `#define av_restrict`
> `#define HAVE_UNISTD_H 0`
> And in avutil\ffversion.h I had to remove the dots from the inclusion guard name.

That's very odd, as I didn't have any trouble.  The custom config.h I'm using handles the UNISTD differently for 64 bit and 32 bit:

```
#ifdef WIN64
	#define EXTERN_PREFIX ""
	#define EXTERN_ASM
	#define HAVE_ALIGNED_STACK 1
	#define HAVE_FAST_64BIT 1
	#define BROKEN_RELOCATIONS 1
	#define ARCH_X86_32 0
	#define ARCH_X86_64 1
	#define HAVE_FAST_64BIT 1
	#define HAVE_FAST_CMOV 1
	#define HAVE_MM_EMPTY 0
	#define HAVE_UNISTD_H 1
#else
	#define EXTERN_PREFIX "_"
	#define EXTERN_ASM _
	#define HAVE_ALIGNED_STACK 0
	#define HAVE_FAST_64BIT 0
	#define ARCH_X86_32 1
	#define ARCH_X86_64 0
	#define HAVE_FAST_64BIT 0
	#define HAVE_FAST_CMOV 0
	#define HAVE_MM_EMPTY 1
	#define HAVE_UNISTD_H 0
#endif

```
avrestrict was defined in my branch:

```
#define av_restrict restrict
```

Also, here is my ffversion.h:

```
/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "4.4"
#endif /* _._../../FFMPEG/AVUTIL/FFVERSION.H */
```

**Comment by clsid2** [comment]
It does not seem to recognize `restrict` keyword. It does work with `__restrict`.

`.\libavutil/file_open.c(26): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory`

**Comment by adipose** [comment]
unistd.h is in `LAVFilters\src\thirdparty\64\include`

image

Maybe 64bit not set?

edit: that var gets set in ffmpeg.bat, I think:

image

image

Which is controlled by ffmpeg.vcxproj:

image

**Comment by clsid2** [comment]
I don't have that header:
https://github.com/clsid2/LAVFilters/tree/master/thirdparty/64/include

**Comment by adipose** [comment]
Ack!  Not sure when I put that in there.  Maybe left there when I did the debug build of msvc for LAVFilters.

It's identical to this one:

https://github.com/ShiftMediaProject/fontconfig/blob/daea2c71daf19623de405f9964aa209f219a19c7/SMP/unistd.h

Possibly, I just copied that one back when for LAVFilters.

**Comment by adipose** [comment]
I'm thinking the configure found unistd.h in that folder, and caused the define to be 1, but only for 64 bit.  Probably the right thing to do is just make it zero, as you did, and lose the header file.

**Comment by clsid2** [comment]
Renderer is working. Added size is small, which is also good.
Only issue I noticed is that when enabling it in the settings, it doesn't uncheck the internal renderer.

Can you add a config button to access its settings (when not playing anything)?

**Comment by adipose** [comment]
>  Only issue I noticed is that when enabling it in the settings, it doesn't uncheck the internal renderer.

https://github.com/clsid2/mpc-hc/pull/1278

This was a preexisting issue, so I've added a separate patch.

**Comment by adipose** [comment]
I ported some B.E. code to show the settings window, and made some other changes to remove more "Internal AR" references.  The big block of code is trying to find MPC-AR when it's not the current AR.  It may be unnecessary since I disable the button unless MPCAR is selected, which defaults to the first block of code.  I don't really understand why the first block of code wouldn't work even if MPC-AR weren't selected...but maybe the idea is it may not be present at all if it's not currently enabled.

**Comment by adipose** [comment]
> It would be nice to have a config button behind the renderer list dropdown to access the settings of the renderer. Similar to in MPC-BE.
> If possible move SaneAR settings into a separate dialog as well. That is less confusing than current situation with settings on two pages.
> 
Good idea. Should we leave for another patch?

**Comment by clsid2** [comment]
Yes, moving SaneAR settings can be done later.

The extra code block for accessing MPCAR settings is probably for when an external instance is used?

**Comment by clsid2** [comment]
I think MPCBE disables the config button when playback is active. We should probably do that as well, since settings do not get synchronized between the two filter instances.

I still need this change to fix ffmpeg compilation:
`#define av_restrict __restrict`

**Comment by adipose** [comment]
> 
> 
> I think MPCBE disables the config button when playback is active. We should probably do that as well, since settings do not get synchronized between the two filter instances.
> 
> I still need this change to fix ffmpeg compilation:
> `#define av_restrict __restrict`

I can make that change.  I'm uncertain right now why it isn't failing for me.  As far as I can tell, there's nothing in the build that actually specifies compiler or C standard.  GCC version specified C99, but Microsoft doesn't support C99, only C89 with partial C99 support.

According to Microsoft, the restrict keyword can be enabled with /std:c11 or /std:c19 flags (which I am not using), and only in VS2019 16.8: https://docs.microsoft.com/en-us/cpp/c-language/type-qualifiers?view=msvc-160#restrict

Before I make the change, I want to make sure our build is targeting a specific compiler and not just "whatever" is the default used by the build tools.  I suspect we have different dev environments and that's why it only works for me with "restrict".

**Comment by adipose** [comment]
I have been able to get the configure script to generate `__restrict`.  The trick was to force the compiler to VS2017.  So, apparently, VS2019 standard C behavior has a new, undocumented "feature" of supporting a bit more of C99, even if the standard is not specified with /std:c17.  Historically, the default C behavior has been C89 with partial C99 support, so I guess it isn't even "wrong," but it's still confusing.

**Comment by adipose** [comment]
> 
> 
> I think MPCBE disables the config button when playback is active. We should probably do that as well, since settings do not get synchronized between the two filter instances.
> 
I looked at the source for PPageAudio and it seems to enable it if MPCAR is the selected audio renderer or if it is active.

```cpp
void CPPageAudio::OnAudioRendererChange()
{
	UpdateData();

	BOOL flag = FALSE;
	CString str_audio = m_AudioRendererDisplayNames[m_iAudioRendererType];
	if (str_audio == AUDRNDT_MPC) {
		flag = TRUE;
	} else {
		BeginEnumSysDev(CLSID_AudioRendererCategory, pMoniker) {
			LPOLESTR olestr = nullptr;
			if (FAILED(pMoniker->GetDisplayName(0, 0, &olestr))) {
				continue;
			}

			CStringW str(olestr);
			CoTaskMemFree(olestr);

			if (str == m_AudioRendererDisplayNames[m_iAudioRendererType]) {
				CComPtr<IBaseFilter> pBF;
				HRESULT hr = pMoniker->BindToObject(nullptr, nullptr, IID_PPV_ARGS(&pBF));
				if (SUCCEEDED(hr)) {
					if (CComQIPtr<ISpecifyPropertyPages> pSPP = pBF) {
						flag = TRUE;
						break;
					}
				}
			}
		}
		EndEnumSysDev
	}

	m_audRendPropButton.EnableWindow(flag);

	SetModified();
}
```

**Comment by Aleksoid1978** [comment]
A little wrong  - enable button for MPCAR or if selected audiodevice support ISpecifyPropertyPages.
Also when press button - show MPCAR dialog or selected audiodevice via ISpecifyPropertyPages, new instance.

**Comment by adipose** [comment]
I see, now. It matches up with the other code that opens properties for an arbitrary renderer.

**Comment by clsid2** [comment]
IDS_AG_DEFAULT is missing in mpc-hc.rc causing empty entry in buffer dropdown in settings.

**Comment by clsid2** [comment]
The MPCToolbarLayout files are unrelated to this patch. After removing those I think it is ready for merge.

**Comment by clsid2** [comment]
I see some AudioTools updates in BE. Include those as well.

**Comment by adipose** [comment]
Toolbarlayout files are gone, too.

**Comment by adipose** [comment]
> MPCAR does not seem to do pitch correction when speeding up video?

I tested this out and it was working ok for me. Also found this ticket:

https://sourceforge.net/p/mpcbe/tickets/175/

**Comment by Aleksoid1978** [comment]
It's working long time ago :)

**Comment by clsid2** [comment]
I can confirm it works.
Any plans to add an option for it? Some people prefer to disable it.

Another interesting feature to port would be the AC3 encoder. In BE located in the audio decoder, but could maybe be moved to the audio renderer or ported to LAV Audio.

**Comment by clsid2** [comment]
I am getting a deadlock at EOF sometimes. Can you guys reproduce? Just hold down right arrow to seek to end of file.

**Comment by Aleksoid1978** [comment]
Do you check in MPC-BE the same file & situations ?

**Comment by clsid2** [comment]
Edit: Also happens with BE (1.6.8.6302) when using LAV Splitter and LAV Audio decoder

The player goes into paused state when the problem occurs.
The sleep loop at the end of CMpcAudioRenderer::WaitFinish() never exists. If I add `m_filterState == State_Paused` as a break condition, then problem is solved, but I don't know if that is correct.

**Comment by clsid2** [comment]
`m_bFlushing` as break condition also works.

**Comment by Aleksoid1978** [comment]
Test on 2 different files in MPC-BE + LAV Source + LAV Audio - can't reproduce.
Can you upload short sample file ?

**Comment by adipose** [comment]
I reproduced it with arrow seeking.  It doesn't occur when playing to EOF, I don't think.  So it must be an edge case where the seek allows the EOF to be found without the renderer seeing the EOF.

**Comment by Aleksoid1978** [comment]
Also tested just press right arrow until end. Give me sample files.

**Comment by clsid2** [comment]
[Sample](https://www1.zippyshare.com/v/Po5XNaNl/file.html)

**Comment by adipose** [comment]
For what it's worth, the first video I tried had the error. I think most any video could cause it.

Seek to the end with arrow, then back a few seconds,then to the end again. Repeat until it hangs.

**Comment by Aleksoid1978** [comment]
I fix in MPC-BE.

**Comment by adipose** [comment]
Seems good.  I ported fix here: https://github.com/clsid2/mpc-hc/pull/1299

**Comment by Aleksoid1978** [comment]
clsid2 already do it :)

**Comment by Aleksoid1978** [comment]
@adipose - can you help me in MPC-BE modify ffmpeg for build with MSVC.
I tried to do by analogy like you - not working.

**Comment by clsid2** [comment]
You can also look at LAV Filters build script as example. It can use MSVC for building the debug build. There are a few differences in the capabilities. It for example does not include the external libraries (dav1d/speex/etc).

What kind of error are you getting?

**Comment by adipose** [comment]
> @adipose - can you help me in MPC-BE modify ffmpeg for build with MSVC.
> I tried to do by analogy like you - not working.

Yes I can try. You might be using for other capabilities than AR?

**Comment by adipose** [comment]
libavcodec/h264_cavlc.c fails on lack of atomics support.  Looking at ffmpeg configure:

`h264_decoder_suggest="error_resilience"`

Error resilience is disabled without atomics, I think.

Might be impossible to compile without atomics.  

There are some other compiles that fail without it.  mpc-be had patch to workaround this already:

```
// ==> Start patch MPC
#ifdef __cplusplus
typedef int atomic_int;
#else
#include <stdatomic.h>
#endif
// ==> End patch MPC
```

But __cplusplus not defined probably as it's a straight C compile.  Actually I think that patch was trying to load the atomics from MINGW probably.

**Comment by adipose** [comment]
[mpcbe.diff.txt](https://github.com/clsid2/mpc-hc/files/7149008/mpcbe.diff.txt)

Here's a patch to get ffmpeg to compile.  It failed to link because of openjpeg.  Maybe you can remove that dependency.

Config.h I changed enough to get working.  But you should rebuild it from the ffmpeg config script (with the WIN64 ifdef I added). Same for config.asm.

**Comment by Aleksoid1978** [comment]
Ok thx.

P.S. Many link error in debug build.

**Comment by adipose** [comment]
Forgot to mention I included stdatomic from here: https://github.com/zenny-chen/simple-stdatomic-for-VS-Clang

Here's an updated patch that links successfully.  Basically you have to remove dav1d, speex, openjpeg.  Also fixed some other problems caused by gcc, etc.

[mpcbevc.diff.txt](https://github.com/clsid2/mpc-hc/files/7150251/mpcbevc.diff.txt)

**Comment by adipose** [comment]
@clsid2, I was able to enable libspeex on msvc pretty easily.  I just built speex with visual studio (2008.sln -> 2019.sln) and put the libspeex.lib file in the lib folders (renamed to speex.lib per windows name conventions needed by ffmpeg).

This would require an update to lavfilters, though.  We don't need it for mpcar so far.

**Comment by Aleksoid1978** [comment]
Finally - i can compile ffmpeg with VS and all external library(dav1d/speex/openjpeg).
Also i change config.h/config.asm to enable MMX/SSE(all)/AVX/AVX2.
But - as i understand when compile in VS - it's don't use all optimization code from .asm file(i don't know why...), result - software video decoder 2-5 slow then gcc's build. It's bad (

**Comment by clsid2** [comment]
Check if the runtime CPU detect code is enabled and working correctly. Pretty much all ASM stuff is compiled with YASM, so should be compatible with MSVC as well. Also check if multi-threaded decoding is working, as that could also be reason for the bad performance.

**Comment by Aleksoid1978** [comment]
All code the same - except compile ffmpeg with VS/gcc.

**Comment by clsid2** [comment]
Also completely identical config file?
There may be preprocessor code that gives different results based on the compiler used.
I still suggest to check if it correctly enables the optimized functions in the code. Then we at least know if that is or isn't the problem.

**Comment by adipose** [comment]
I noticed your original config file had mmx, sse, etc disabled. I enabled them due to asm compile issues.

Did you rebuild config.h and config.asm from configure script?

**Comment by adipose** [comment]
Also make config.asm match config.h. I didn't fix all vars to match.

**Comment by clsid2** [comment]
@Aleksoid1978
Do you plan to use MSVC for release builds or just for debugging?

Besides dav1d/speex/opencore, there are a few other libs that LAV uses that are currently only enabled for GCC in its build script: gnutls/gmp/libxml2.

**Comment by clsid2** [comment]
MSVC doesn't support inline ASM. So some code parts are slower. I don't think there is much inline ASM left in ffmpeg. But for example it is still used for CABAC and a little bit in swscale. So H264 and HEVC performance will at least be lower due to CABAC.

**Comment by adipose** [comment]
@Aleksoid1978 , if you have an example of poor performance I can take a look at it.  There are alternate methods for boosting performance in VS, but in general, performance can be good with the right approach.  For example, if you build libspeex, there is an option for an SSE2 build.  Maybe performance is better for speex in that case.

**Comment by clsid2** [comment]
Speex isn't a common audio format. So it's decoding performance isn't very important. Audio is typically easy to decode anyway.

**Comment by Aleksoid1978** [comment]
I planned use MSVC build for release/debug.
About performance - very-very bad VP9 10bit decoding, H.264/HEVC slower about 1.5-2 times.

**Comment by adipose** [comment]
@Aleksoid1978 

https://github.com/clsid2/mpc-hc/pull/1309

You might be able to reuse this script I created to auto-generate config.h/config.asm from a proper configure script.  I did notice some minor discrepancies in the config that was created.

**Comment by adipose** [comment]
@Aleksoid1978 How are you measuring performance? I played 720p H264 with no slowdown, but maybe I should up the framerate?

**Comment by Aleksoid1978** [comment]
I test on VP9 10bit 4K HDR, H.264/HEVC 4K 8bit

**Comment by adipose** [comment]
OK, can you upload some samples?  I tried a 4k h.264 video.  Custom built 1.6alpha dropped only one frame at 4x play rate.  1.5.8 dropped 70 frames.  So for me, it seemed faster.

**Comment by Aleksoid1978** [comment]
I compare CPU load.
Better check on VP9 10bit 4K HDR, any HDR clip from youtube. On software decoder.

https://www.youtube.com/watch?v=LXb3EKWsInQ

**Comment by clsid2** [comment]
A good way to test fps performance (of standalone filter) is with GraphStudioNext:
Menu > View > Performance Test

**Comment by clsid2** [comment]
MPCAR has some issues with mono input.
[Sample](https://www89.zippyshare.com/v/uPSL3M6Y/file.html)
Play at 100% volume and stereo output. You will hear distortion noise due to overflow. SaneAR fixes this with its [limiter](https://github.com/clsid2/mpc-hc/blob/develop/src/thirdparty/sanear/src/DspLimiter.cpp). FFmpeg has alimiter filter, but that has downside of small audio delay.
But problem can maybe also be prevented by adjusting how the mono is mixed to stereo. The volume is lower if I let LAV do the mixing, and there is no noise. I think LAV may be using 0.7071 for mixing, while ffmpeg uses 1.0? The center mix level value does not seem to have any effect for mono>stereo.

**Comment by clsid2** [comment]
Another bug. Enable expand mono to stereo in LAV, and disable mixing. Then MPCAR gets 8-bit stereo input with this sample, and audio is silent.

**Comment by Aleksoid1978** [comment]
Problems with the build ffmpeg with msvc seem to have solved. Do testing video software decoding.

**Comment by Aleksoid1978** [comment]
For input mono and output stereo internal mixer use 1.0, as is.

**Comment by Aleksoid1978** [comment]
> 
> 
> Another bug. Enable expand mono to stereo in LAV, and disable mixing. Then MPCAR gets 8-bit stereo input with this sample, and audio is silent.

It's PCM, decoder don't use in decoding. You something wrong :)

**Comment by clsid2** [comment]
The decoder gets used when using LAV Splitter Source. It does pcm_u8 -> PCM

The decoder is not relevant except for reproducing bug with this sample. Could also happen if source file was 8bit stereo.

**Comment by Aleksoid1978** [comment]
I use in MPC-BE with LAV Source - there is no audio decoder in graph.

**Comment by Aleksoid1978** [comment]
Give me WAV with 8bit stereo PCM(can do with ffmpeg) - i check it.

P.S. Found - http://mauvecloud.net/sounds/index.html
I check on http://mauvecloud.net/sounds/pcm0811s.wav - all is good.

**Comment by clsid2** [comment]
Try with MPC-HC with internal filters + MPCAR.

**Comment by adipose** [comment]
> 
> 
> Problems with the build ffmpeg with msvc seem to have solved. Do testing video software decoding.

Good!  Can you say what changed?

**Comment by Aleksoid1978** [comment]
> 
> 
> Try with MPC-HC with internal filters + MPCAR.

Why for me check in MPC-HC if all is good in MPC-BE with internal/external filters ?

**Comment by clsid2** [comment]
Because that does not load LAV Audio. It is just easiest way to generate the exact input case where the renderer has a problem. Other audio renderers work correctly with same input. You could also test in GraphStudioNext with standalone filters.

Your sample also has the issue when using LAV Splitter/Audio + MPCAR. No problem with other audio renderer.

The problem seems to be related to the input bitdepth. In my example MPCAR gets 8-bit integer input, and in MPC-BE it gets 16-bit input. So the BE audio switcher must be converting 8 to 16 bit, avoiding/hiding the bug in the renderer. I don't see any option to disable the stream switcher for testing?

**Comment by Aleksoid1978** [comment]
You are the developer in MPC-HC - debug/test/fix :)

**Comment by Aleksoid1978** [comment]
Can reproduce - silent in Shared mode.

P.S. Fixed.

**Comment by adipose** [comment]
> 
> 
> Can reproduce - silent in Shared mode.
> 
> P.S. Fixed.

https://github.com/clsid2/mpc-hc/pull/1310

**Comment by clsid2** [comment]
Are you able to reproduce the noise with 8-bit mono input? You should hear a bit of crackling and static in the background. It does not happen if input is upmixed to stereo. Player and Windows volume need to be at 100% to hear it.

**Comment by Aleksoid1978** [comment]
Yes i confirm. But i think that's bad source.
Screen from Audacity:
audio

P.S. DSound the same situation as with MPC AR.

**Comment by Aleksoid1978** [comment]
About compilation ffmpeg by the Visual Studio - there is one strange problem, crash using HEVC software decoding using multithread, in single thread all is good. Look's like VS "bad handle" multithread code, but only for HEVC.

**Comment by clsid2** [comment]
Can you consider porting the Limiter DSP from SaneAR to MPCAR? That can help with this kind of bad sources. The code seems relatively simple, and it only modifies the audio if it overflows.

Is the HEVC crash random (race condition) or does it always crash at same moment and same spot in the code? Does it already happen with 2 threads, or are more needed? Does it happen in debug build as well, and can you show screenshot of the crashin debugger?

[FFmpeg automated testing (FATE)](http://fate.ffmpeg.org/?sort=cc) doesn't show any issues for MSVC. So maybe also try different MSVC compiler versions to test if it is a compiler bug.

**Comment by Aleksoid1978** [comment]
Not planned add limiter to MPCAR. Maybe sometimes - to internal AudioSwitcher.

**Comment by Aleksoid1978** [comment]
Here is my **config.asm/config.h/ffmpeg.mak/unistd.h**
I use original **stdatomic.h** from **ffmpeg**.
[ffmpeg.zip](https://github.com/clsid2/mpc-hc/files/7190966/ffmpeg.zip)

P.S. Generate using you's **make_config.cmd** + **configure_ffmpeg-min.sh**, the only thing is that VisualStudio 2019/2022 does not work with **#define av_restrict restrict**, i use **__restrict**

**Comment by clsid2** [comment]
@adipose 
Are you able to test audio bitstreaming?

With SaneAR it is currently needed to enable both "exclusive mode" and "allow bitstreaming". I propose the following two simplifications:
1) Ignore the exclusive mode setting when doing bitstreaming. Because bitstreaming always requires exclusive mode just enforce exclusive mode in that case. The benefit of this would be that shared mode can be used whenever bitstreaming is not active.
2) The "allow bitstreaming" option could be removed? I am not sure what it is needed for, as bitstreaming can typically be disabled in the audio decoder.

**Comment by clsid2** [comment]
I have setup an old receiver next to my dev system. So I can do some bitstream testing later.

@Aleksoid1978
Found a tiny bug in MPCAR.
Get a file that contains both AC3 and DTS audio stream. When switching from DTS to AC3, the status page of the renderer still says `Bitstream [DTS]`.

**Comment by Aleksoid1978** [comment]
Bitstreaming always requires exclusive mode.

About render status AC3/DTS - i think because when bitstreaming AC3 & DTS use the same mediatype with wFormatTag = WAVE_FORMAT_DOLBY_AC3_SPDIF. When switching from DTS to AC3 - there is no calling SetMediaType() in MPCAR from upper filter.

P.S. Test in MPC-BE - status change.
Give me short sample.

**Comment by clsid2** [comment]
You are correct, `SetMediaType()` is not called in this case, since mediatype doesn't change.

Switching stream does call `CMpcAudioRenderer::NewSegment()`. Adding this there solves it for me:
```
if (m_BitstreamMode == BITSTREAM_DTS || m_BitstreamMode == BITSTREAM_AC3) {
    // format might have changed
    m_BitstreamMode = BITSTREAM_NONE;
}
```
That change should be safe, right?

**Comment by Aleksoid1978** [comment]
Yes, it's safe.

**Pull request merged**
