### PR TITLE
Basically support load subtitles from Youtube-dl.

### PR DESCRIPTION
**Pull request by lifegpc**
Now It only support for url based result not data based result. 
It only read subtitles which have no ext or ext is vvt, ass or srt now.
```https://www.youtube.com/watch?v=eBBOeYGqTvo``` (Video have subtitles. This video's webvtt subtitle have same line, parsing webvtt should be improved.)
image

### CODE REVIEW

**Comment by clsid2** [comment]
Downloading subs for all languages is a bad idea. We need an advanced option to specify which language to download. Similar to Options>Playback>Default Track Preference

**Comment by ale5000-git** [comment]
Why not adding a global "Default media language"?

**Comment by clsid2** [comment]
No, bad idea, no time to explain why and I am not interested in discussing this.

Subtitle download could follow settings from:
Options > Subtitles > Misc

**Comment by lifegpc** [comment]
My idea is that add an ```selectAllSubsFromYDL```(disabled by default) in advanced pages.
If ```selectAllSubsFromYDL``` is true or Languages in order of preference in Misc page is empty, read all subs from YDL.
If Languages in order of preference in Misc page is not empty, use it to read subs from YDL.

**Comment by lifegpc** [comment]
> Subtitle download could follow settings from:
> Options > Subtitles > Misc

I prefer add a ```YDLSubsPreference``` to Advanced Page. Make a provider Instance is not neccary.

**Comment by lifegpc** [comment]
image
It works fine now. (With ```YDLSubsPreference``` is ```en zh ja```.)

**Comment by clsid2** [comment]
When saving to playlist file, you don't need to store the indexes of the subtitles. Just read the lines and append to sub list of current PLI. That should work just fine with multiple sub lines.

I would also prefer if the information is stored in a single line for each subtitle:
1,ydl_sub,en,vtt,http://example.com/sub.vtt
In case of empty extension, just use empty string:
1,ydl_sub,en,,http://example.com/sub

**Comment by clsid2** [comment]
And maybe use --list-subs instead of --all-subs parameter

**Comment by lifegpc** [comment]
> And maybe use --list-subs instead of --all-subs parameter

Use --list-subs will return null.
image

**Comment by lifegpc** [comment]
Now it works well with data based subtitle.
image
image (I add some unicode char to content by modify youtube-dl source code, they are not in my PC default charset.)

**Comment by clsid2** [comment]
@adipose
Can you also do a quick review of this patchset?

**Comment by adipose** [comment]
PPageAdvanced.cpp should use string resources.  I see a few at the end did not but recently I had converted them all to resources to help with translations.  We can handle that in another patch, probably.

-------

`int m = pli->m_label.ReverseFind(*_T(" (")); `

This code looks funny to me.  There is no ReverseFind on CStringT for strings, only single characters.  Additionally this creates a pointer to a tchar*, which I don't see the point of.  Maybe the only way ReverseFind would accept that parameter.  See here for a function: https://stackoverflow.com/questions/11983903/cstring-find-the-last-entry

-------

Implicit conversion from CStringW to CStringA should be avoided:

`CStringA langt(lang);`

You should us CW2A and specify the correct codepage.  In this case I think it doesn't matter, as the lang should be valid ansi, but still best to avoid.

**Comment by clsid2** [comment]
Yes, some strings are not yet translatable resources due to laziness on my side. That can be done all in one go in a separate patch.

I also thought the ReverseFind was weird. For simplicity sake the subs don't need to contain the stream title. They could just be "[YoutubeDL] %languagecode%.%extension%"

**Comment by ale5000-git** [comment]
Maybe `"[YoutubeDL] %languagecode%.%extension%"` can also be used to name audio tracks that come from youtube-dl.exe

**Comment by lifegpc** [comment]
> Maybe `"[YoutubeDL] %languagecode%.%extension%"` can also be used to name audio tracks that come from youtube-dl.exe

But youtube-dl do not provide that infomation. :(

**Comment by ale5000-git** [comment]
Maybe just `[YoutubeDL] %extension%` but it is strange that it doesn't provide language.

**Comment by lifegpc** [comment]
I think use Audio Info is better (include Language). But I don't know why sometimes audio switcher can get audio info, but sometimes not.

**Comment by ale5000-git** [comment]
My message wasn't clear what I mean is:
`[YoutubeDL] %languagecode%.%extension%`
where
[YoutubeDL] mean that the track come from youtube-dl.exe (not the info)
%languagecode% come from youtube-dl.exe if present or from audio info (so using both)
%extension% come from youtube-dl.exe if present or from audio info (so using both)

**Comment by ale5000-git** [comment]
Hi,
any update about this?

**Comment by lifegpc** [comment]
Already completed.

**Comment by ale5000-git** [comment]
Is it possible to have a test build please?
I would like to try it.

**Comment by lifegpc** [comment]
> Is it possible to have a test build please?
> I would like to try it.

[Test build](https://mega.nz/file/MwQRWayS#j-FctO3qUo817TkAt0KzX3Sg8K5AJ8tkoaXNO4NdxyM)

**Comment by Dantrech** [comment]
> > Is it possible to have a test build please?
> > I would like to try it.
> 
> [Test build](https://mega.nz/file/MwQRWayS#j-FctO3qUo817TkAt0KzX3Sg8K5AJ8tkoaXNO4NdxyM)

- Will the caption style load itself or is it a custom style? It looks great with the pink color, I see it with the normal style :(
- With the example video, the English subtitles look double to me (see image). But if I see the direct video on Youtube, they look good. It's a bug?
repeat

**Comment by lifegpc** [comment]
> * Will the caption style load itself or is it a custom style? It looks great with the pink color, I see it with the normal style :(

That's because MPC-HC just support basic webvtt file. It ignore all formats in the file. MPC-HC will use it's default style in settings to replace it.

> * With the example video, the English subtitles look double to me (see image). But if I see the direct video on Youtube, they look good. It's a bug?

It is a broken subtitle. [Detail](https://github.com/clsid2/mpc-hc/issues/782)

**Comment by Dantrech** [comment]
> > * Will the caption style load itself or is it a custom style? It looks great with the pink color, I see it with the normal style :(
> 
> That's because MPC-HC just support basic webvtt file. It ignore all formats in the file. MPC-HC will use it's default style in settings to replace it.
> 
> > * With the example video, the English subtitles look double to me (see image). But if I see the direct video on Youtube, they look good. It's a bug?
> 
> It is a broken subtitle. [Detail](https://github.com/clsid2/mpc-hc/issues/782)

Thanks a lot!

PS: I found the font: https://en.m.fontke.com/font/20657667/

**Comment by ale5000-git** [comment]
@lifegpc: Latest youtube-dl.exe have merged the fix for automatic captions but I don't see them on `https://www.youtube.com/watch?v=GWGbOjlJDkU`.
Other than that they seems to be working properly, thanks.

**Comment by ale5000-git** [comment]
@lifegpc: A better sample link => `https://www.youtube.com/watch?v=wfpgaUDG6tA`

Subtitle can be downloaded with: `youtube-dl --write-auto-sub --sub-lang en --skip-download "https://www.youtube.com/watch?v=wfpgaUDG6tA"`

**Comment by lifegpc** [comment]
> @lifegpc: A better sample link => `https://www.youtube.com/watch?v=wfpgaUDG6tA`
> 
> Subtitle can be downloaded with: `youtube-dl --write-auto-sub --sub-lang en --skip-download "https://www.youtube.com/watch?v=wfpgaUDG6tA"`

I see. Seems new version fix write-auto-subs will let output json to null. It use another key to store auto subtitles. I will do that in my spare time.

**Comment by lifegpc** [comment]
[test build](https://mega.nz/file/00oj1QhA#a6m_tNh1QmTohPW0pjrXcKGsqyjoZ9Y2WK4thZutivc). I add a new option in advanced page.

**Comment by ale5000-git** [comment]
It works fine but it is really slow at opening videos.

**Comment by clsid2** [comment]
I have not tested this yet.

Is it slow because auto generated subs are generated on-demand?
If so, it may be wise to mention in the option description that it may slow down youtube-dl processing.

**Comment by lifegpc** [comment]
> I have not tested this yet.
> 
> Is it slow because auto generated subs are generated on-demand?
> If so, it may be wise to mention in the option description that it may slow down youtube-dl processing.

Because auto generated subs need a token, it may cost lots of time. I notice other subtitles do not have a token.

**Comment by ale5000-git** [comment]
Save a Copy... option in File menu merge the audio track even if it is separate (how it is in Youtube) so why not merging also subtitles in the final mkv?

**Comment by clsid2** [comment]
You can do whatever you want through "YDLCommandLine" in advanced options.

**Comment by lifegpc** [comment]
> I have not tested this yet.
> 
> Is it slow because auto generated subs are generated on-demand?
> If so, it may be wise to mention in the option description that it may slow down youtube-dl processing.

image
image
I write a simple python script to calculate the cost time. It seems not releated to auto generated subs. (test with latest release version of youtube-dl.

**Comment by lifegpc** [comment]
image
image
Looks like load subs will extend cost time. ( But seems not big deal on server:(

**Comment by OscarL** [comment]
I was about to open a Feature Request for this one! Any chance of having it merged?

Thanks to everyone for your work on MPC-HC. It is really appreciated.

**Comment by clsid2** [comment]
I will have a look at this again soon. Lots of things to do.

**Comment by ale5000-git** [comment]
An idea to avoid loading too much subtitles: by default load only the subtitle languages listed inside `Options > Subtitles > Misc > Languages in order of preference`.

PS: Also for automatic captions since automatic captions are "automatic" they always have all languages and clutter interface a lot.
PS2: Optionally an advanced options to load all languages.

@lifegpc: The problem of loading all subtitles isn't on the server but on the pc.

**Comment by OscarL** [comment]
@ale5000-git: 

+1 on the "list only the languages in `Options > Subtitles > Misc > Languages in order of preference`".

> since automatic captions are "automatic" they always have all languages

You mean the auto-translated subs you might select when a video already has a "normal" subtitle?

Because the automatically-generated subtitles I've ever seen on YouTube are all one and unique for each video (and sometimes a video in English gets auto-generated subs in a different language for some reason!).

Anyway... I hope this can be added soon, as the workaround (downloading the subtitle manually) cannot be automated because `mpc-hc.exe <URL> /sub sub.vtt` isn't working with the youtube-dl integration (#526).

**Comment by ale5000-git** [comment]
@OscarL: Yes, if you enable UseAutomaticCaptions in advanced options you get auto-translated subs in all languages also if they aren't displayed on Youtube.

**Comment by OscarL** [comment]
@ale5000-git I wasn't able to download the test build, so I may be well talking gibberish.

I think I get it now... There is a difference between:
- "Subtitles". Youtube might not have one, or have, say one for English, and one for Korean, and so on. These are preferred ones (usually).
- "Auto-Generated". Youtube might or might not have these available. Usually in the language that it is spoken on the video (but not always, sometimes it picks Korean for video in English, for example). These are the ones I am after, and what I was referring to as "automatic" subtitles.
- "Auto-Translated". Youtube let you select from a looong list of languages if you select "auto-translate". Goes bad FAST when combined with "Auto-generated" in my experience.

This patch is downloading all the "auto-translations" instead of just the Auto-Generated one?

Using youtube-dl, I'm only able to get either of the first two (when available). I assumed this patch worked like that, instead of getting all the auto-translations.

If that's how it works, I hope that it gets a separated toggle, because I see how that can get slow, and I would turn that off anyway.

Ok. I've generated too much noise on this issue already. I'll let the grown ups do their thing.

**Comment by lifegpc** [comment]
I try to rebase this branch but I see many whitespace change in Files changed.

**Comment by lifegpc** [comment]
I test latest youtube-dl(2021.4.7), looks like `--sub-lang` have no any effects to `subtitles` object. Remove `--all-subs` still will return all language in subtitles object.
image

**Comment by lifegpc** [comment]
Maybe the default value of `YDLSubsPreference` can be UI's default language.

**Comment by ale5000-git** [comment]
With this:
`youtube-dl.exe --sub-lang en,it --write-sub --write-auto-sub https://www.youtube.com/watch?v=cxHM9D4Fw_g`
I get eng and ita,
while with this:
`youtube-dl.exe --sub-lang it --write-sub --write-auto-sub https://www.youtube.com/watch?v=cxHM9D4Fw_g`
I get only ita.

If you convert from three letters to two letters language codes you could reuse existing configuration.
PS: How programmer I vote -1 for using UI's default language because to easy bug reports I often use English UI language but I don't want to see English subs.

**Comment by ale5000-git** [comment]
Maybe it is just the JSON that isn't filtered, but you can just skip the unneded one from the JSON in the C++ code.

**Pull request merged**
