### PR TITLE
do not expand no-click zone near seekbar horizontally

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
Now safezone only works here below the seekbar. Not above.

**Comment by adipose** [comment]
I noticed the same thing. I think what is happening is the 10% drag tolerance means the initial click may be in the safe zone, but by the time it is dragged 10% vertically, it's out of the zone, and that's when the first nc click is registered.

I decided it was OK, because it means they didn't just click there but actually dragged 10%. What do you think?

**Comment by clsid2** [comment]
The drag protection is only applied in maximized state.

I think there might be an issue with placement of the safezone. 
I don't have time to look at it today.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1183

What I observed is that the NC click is not the only possible problem.  The mousetouch itself generates events, one of which will be NC click, but only if dragging. Pause, etc., are handled before that.

I added a check in mousetouch and it seems to be working better, now.  This might also stop some mouse shortcuts working in the safe zone.

**Pull request merged**
