### PR TITLE
Add support for libass rendering in RTS internal renderer

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
Awesome! I will test this asap.

Can you add an option in the GUI for it? That is useful for comparing performance and dealing with rendering issues.

**Comment by clsid2** [comment]
I assume the style editor won't work when using this. In that case Play>Subtitles>Styles should be disabled. Similarly for Default Style, if that can't be supported for ASS/SSA.

A possible future feature would be to add an option to also use it for SRT subs.
https://github.com/Blitzker/assfiltermod

**Comment by adipose** [comment]
> 
> 
> I assume the style editor won't work when using this. In that case Play>Subtitles>Styles should be disabled. Similarly for Default Style, if that can't be supported for ASS/SSA.
> 
> A possible future feature would be to add an option to also use it for SRT subs.
> https://github.com/Blitzker/assfiltermod

Yes, that's true.  But we may want to have some rendering options for libass.  Right now it simply renders directly onto the subpicture without setting many parameters.

**Comment by clsid2** [comment]
The newly added project files should include platform.props file. Currently they fail to compile with VS2017.

**Comment by adipose** [comment]
See if they work, now.  I had been including that, but when I cleaned up all the project files, I must have removed it from a bunch of them.

**Comment by clsid2** [comment]
The platform toolset and sdk settings must also be removed from the project files, so they inherit properly from platform.props

And also include common-3rd-party.props so warnings are suppressed.

I also needed to add "libcmt.lib" to the default library ignore list of mpc-hc to fix a link error.

**Comment by adipose** [comment]
I think this should be done. The 3rd part props is in all the files already, I thought.

**Comment by clsid2** [comment]
I tried it with some files with embedded subs. I noticed several cases where subs were displayed as plain white text without any borders or shadows. I assume that is the "default style" of libass?

Applying the default style settings from MPC-HC as parameters to libass needs to be done first before we can ask others to test this. The assfiltermod project I linked to is based on the MPC-HC/VSFilter gui and has same options, so you can use that as an example.

It also seems that embedded fonts are not working properly.

[sample file](https://www.sendspace.com/file/syqf9p)

**Comment by adipose** [comment]
Finally found the memory leak, which was in fribidi project.    Also, SRT is supported, too.

I'll look at the other issues.

**Comment by adipose** [comment]
I think your sample file is working.  My last attempt to clear the memory leak actually broke the renderer and I didn't realize it.  I'm surprised it was working for you at all!

**Comment by clsid2** [comment]
Here are some more sample files with complex subs:
[link](https://www.sendspace.com/file/2of7dm)

There still is a memory leak. Usage keeps increasing until end of playback.
Are custom fonts working for you? They don't work here with a vs2017 build.

**Comment by adipose** [comment]
I see the growing memory usage, but VS doesn't detect any actual leaks.  And when I render using the built-in one, it grows even faster!

**Comment by clsid2** [comment]
I get a peak usage of 172M with built-in renderer for "ddy dimension w op.mkv" sample. Libass goes over 400M. I tried VLC as well, and that also goes over 400M. Doesn't have to be a leak, libass may just be less efficient with mem usage in some cases.

**Comment by adipose** [comment]
There is a way to clear the libass cache, maybe that will help.  I'll see.

**Comment by adipose** [comment]
Outstanding issues remain:

1. No background or border on fonts.  I see nothing in either project above that explicitly tells libass to do this.  I can surely hack something in, but I'm curious how others have defaulted such things.
2. High memory usage.  VLC does some optimizations, but you note it uses similar memory.
3. Settings dialogs.  There are very few settings for libass in the XY-vsfilter: 

image

4. Embedded fonts.  There is a function included to do this, but maybe it's not working.  VLC has another method.

**Comment by adipose** [comment]
It seems embedded fonts are now loaded.  However, in [PSNR]Air.Creditless.OP.[avc][vorbis], I noticed that the font across the top is now showing garbage characters.  There must be some bug in the use of that font.

**Comment by clsid2** [comment]
VLC has the same bug with garbage characters on that file. It does however have correct border/shadow/color on the text.

**Comment by adipose** [comment]
Interesting.  But it works with the internal subtitle renderer.

**Comment by clsid2** [comment]
For SRT to ASS conversion with style from MPC-HC settings:
https://github.com/Blitzker/assfiltermod/blob/master/assfilter/AssFilter.cpp (line 223)

**Comment by adipose** [comment]
Yeah, I will look at that.  I already have imported code to handle converting SRT to ASS.  I'm pretty sure there is a basic bug with backgrounds and outlines, because this sample video contains ASS rules for both, and yet nothing is rendered.

**Comment by adipose** [comment]
I have seen the outlines, now.  Something wrong in my implementation with RTS.  It's like there's an alpha mask that needs updating other than the subpicture.  I'm not too familiar with it, but if I render on a white square it's ok, but on the video it doesn't work.

**Comment by adipose** [comment]
OK, it seems to be working better, now.  I discovered that the subpicture has an inverse alpha, apparently.  Now that that is taken into account, the dark borders show up, and the colors look right.

**Comment by clsid2** [comment]
Yes, working now.

**Comment by adipose** [comment]
Cool. I still have a few things I need to work on re: SRT subs.  But it's getting closer!

**Comment by adipose** [comment]
OK, so embedded SRT is working, now.

Right now settings are using a hardcoded default, but I'll look at that.

**Comment by adipose** [comment]
I'm not sure what fixed it, but the garbage characters seem to be fixed.  One thing I changed is using directwrite, maybe it's a bug in fontconfig.

**Comment by adipose** [comment]
OK, so I've gotten the defaults working for srt subtitles, now.  I tested most of them and they seem to work pretty much as expected.

**Comment by clsid2** [comment]
Custom fonts are broken now?

**Comment by adipose** [comment]
Oh, interesting.  Maybe that's why the garbage characters disappeared.

**Comment by adipose** [comment]
Fixed that, and now the garbage characters are back.

**Comment by clsid2** [comment]
VLC has the same issue, so most likely a bug in one of the libraries.

**Comment by clsid2** [comment]
I was thinking to merge this PR into a new branch. After looking at the external projects used, I noticed that https://github.com/ShiftMediaProject/libass uses relatively old libass code. Would it be possible to switch to the official libass repo and import the VS project files from ShiftMediaProject into MPC-HC repo? Same for the other projects, although those seem less out-of-date.

**Comment by adipose** [comment]
I have been able to update the libass code in the past. When I requested, he has updated other projects. Main issue here is code that compiles on windows without making msys tool chain. Let me see if he would update.

**Comment by clsid2** [comment]
We already use MSYS/MingW for compiling FFmpeg part of LAV Filters, so it would not be an issue if that is also needed to compile libass.

**Comment by adipose** [comment]
The msys compiles are slow and require some manual build scripts, but I have no issue switching if you can integrate the build with lavfilters. VS was easier to integrate, that's all.

**Comment by clsid2** [comment]
Using VS is fine too. I was just worried the projects might not be updated frequently enough. However, using official repos is preferable if it isn't too complex to implement. The VS project and bash script of LAV could be copied and modded to work for libass.

In case of FFmpeg most slowness comes from their insanely complex configure script.

**Comment by adipose** [comment]
I requested an update to libass from shiftmedia. Here was the response:

https://github.com/ShiftMediaProject/libass/issues/3

It is true the last release of libass was in 2017:

https://github.com/libass/libass/releases

I actually imported newer sources before to see if it improved anything, but I didn't notice any differences for what I was working on.

So, do we want to use the newer sources, or wait for a "real" release?  Seems it might take a few years...

**Comment by clsid2** [comment]
Then I prefer the actual latest source. Then we can update whenever there is an important fix.

**Comment by adipose** [comment]
OK, I will see what source code changes are required for the VS build.  Otherwise, maybe an msys build.

**Comment by adipose** [comment]
@clsid2 

Tracking latest libass source, now.  I found a memory leak which I submitted a PR for. Now that I have it working, I think that memory leak would never happen (only happens when error creating font occurs).  But without the right config.h settings, it could happen which caused a memory leak (also fonts were not working, so...).

I have also merged upstream.

**Comment by clsid2** [comment]
ToDo:
- Add option to enable use of libass. In case of VSFilter a registry value is enough for now. GUI can be added later. For MPC-HC an advanced option will suffice for now.
- Place #if USE_LIBASS around more of the added code and includes
- Suppress compile warnings in the external libs

**Comment by adipose** [comment]
- Add option to enable use of libass. In case of VSFilter a registry value is enough for now. GUI can be added later. For MPC-HC an advanced option will suffice for now.

I added a checkbox to options.

- Place #if USE_LIBASS around more of the added code and includes

I replaced the ifdef with a boolean.  I can bring it back if it helps merge it into develop.

- Suppress compile warnings in the external libs

Which warnings are you seeing?  I know of a couple things.

**Comment by adipose** [comment]
Warnings should be cleaned up.

**Comment by clsid2** [comment]
Yes, I prefer to keep the #if USE_LIBASS around the added code to be able to make a build without libass included.

**Comment by adipose** [comment]
OK, it now should pretty much exclude all the libass related code, minus a couple minor configuration items.  I left those in so it won't lose libass options when switching builds (they will not actually do anything in non-libass builds).

The gui options will be hidden in non-libass builds.  Form objects are still there, but are disabled.

Finally, I had added some code for opentype languages, which is working in libass.  I think I can make it work in the internal renderer if desired, so I'm leaving that option "on" even when libass is disabled.  It currently won't work for internal renderer but it won't do any harm either.

**Pull request merged**
