### PR TITLE
RFS: autoplay if only one video in archive (regression)

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
I see that the getMediaTypeList function reads data from the Registry. The presence of these reg keys often depend on external codecs being installed, which isn't necessarily the case when using MPC-HC.

It would be better (and faster) to include a static list with the mediatype data for common formats.

**Comment by adipose** [comment]
That code came from the old RFS.  There is a static list of types in the source, too, that isn't used.

```cpp
const
file_type_t CRARFileSource::s_file_types [] =
{
	{ "avi", &MEDIASUBTYPE_Avi },
	{ "mpg", &MEDIASUBTYPE_MPEG1System },
	{ "vob", &MEDIASUBTYPE_MPEG2_PROGRAM },
	{ "mkv", &MEDIASUBTYPE_Matroska },
	{ "mka", &MEDIASUBTYPE_Matroska },
	{ "mks", &MEDIASUBTYPE_Matroska },
	{ "mov", &MEDIASUBTYPE_QTMovie },
	{ "mp4", &MEDIASUBTYPE_QTMovie },
	{ "wav", &MEDIASUBTYPE_WAVE },
	{ "mp3", &MEDIASUBTYPE_MPEG1Audio },
	{ "mpa", &MEDIASUBTYPE_MPEG1Audio },
	{ "mpv", &MEDIASUBTYPE_MPEG1Video },
	{ "dat", &MEDIASUBTYPE_MPEG1VideoCD },
	{ NULL, NULL }
};
```

**Comment by clsid2** [comment]
I took a quick look again, and I don't think the mediasubtype is strictly needed. The default MEDIATYPE_Stream + MEDIASUBTYPE_NULL should already be sufficient.

So simpler solution would be to just check if the file extension matches with a list of extensions that we allow in rar.

**Comment by adipose** [comment]
@clsid2 , do you want to use that short list I provided, or were you thinking to use all the types listed in MediaFormats.cpp?  I had some trouble getting access to those from the filter, as it doesn't use MFC in its compile.  I thought maybe to move those declarations to a separate include.

**Comment by clsid2** [comment]
The short list is fine. You can add: ogm ogg flac m2ts mk3d

**Comment by adipose** [comment]
OK, that's done.

**Pull request merged**
