### PR TITLE
Added the SweetFX video shaders

### PR DESCRIPTION
**Pull request by CeeJayDK**
These are the shaders from SweetFX (also by me) ported to run in MPC-HC.

Settings can be set in the source files themselves - not the best solution, but currently the only solution as MPC-HC does not have an interface to control shader settings.

### CODE REVIEW

**Comment by CeeJayDK** [comment]
What is the reason you opted to close this?

**Comment by clsid2** [comment]
I don't think these shaders are useful enough to add.

**Comment by CeeJayDK** [comment]
Oh? They are popular on the Doom9 forums - especially Lumasharpen, which was also added to MPC-BE.

https://forum.doom9.org/showthread.php?t=157634&highlight=lumasharpen&page=26

IMO two things are vital to getting the best image quality
A good upscaler and a good sharpener.
Lumasharpen solves one of those.

But there are other good ones too. Here is an comparison of sharpening shaders : https://misie.ga/sharp/

It would be nice to have at least one good sharpener in MPC-HC. SharpenComplex2 doesn't quite cut it - in fact I originally wrote Lumasharpen to replace SharpenComplex2 because I wasn't satisfied with it's quality and speed.

**Comment by clsid2** [comment]
I have added lumasharpen and sepia.

**Pull request closed without merging**
