### PR TITLE
remember last quickopen and saveimage paths separately

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by ale5000-git** [comment]
@adipose: If possible can you add an option to disable saving path (for privacy or shared pc) please?

PS: Also it wold be nice if the default folder of "last quickopen" is the user video folder if there isn't a saved one or if saving is disabled (instead user image folder for saveimage).

**Comment by clsid2** [comment]
It can be enabled based on the keep history option. But you should realize that Windows also remembers...

**Comment by adipose** [comment]
Was going to say that too.

https://stackoverflow.com/questions/61568991/how-to-retrieve-the-last-folder-used-by-openfiledialog

**Comment by ale5000-git** [comment]
This is because I also said that should hopefully set video folder specifically when saving is disabled.

```
if (savePath && s.lastQuickOpenPath.GetLength()) {
  fd.m_ofn.lpstrInitialDir = s.lastQuickOpenPath;
}
else
{
  fd.m_ofn.lpstrInitialDir = userVideoFolder.
}
```

This isn't working code, it is just to give the idea.

**Pull request merged**
