### PR TITLE
Partly support escape sequences in WEBVTT file.

### PR DESCRIPTION
**Pull request by lifegpc**
[Example file](https://1drv.ms/u/s!Aoq8mAMlVv8UnQU64-XB8g-rP6XT?e=ltgZdc).

### CODE REVIEW

**Comment by clsid2** [comment]
@adipose @lifegpc
The Chinese subs of the above example file do not render correctly. It is caused by the temporary conversion to ansi string for the regex replacement. That is something we need to fix as well.

**Comment by lifegpc** [comment]
image
It seems works fine.

**Comment by lifegpc** [comment]
image
image
But it seems have problem with Arabic.

**Comment by clsid2** [comment]
It might work for you because it is your native code page. I get the ? for the Chinese characters, as well as for Arabic and a few others.

**Comment by lifegpc** [comment]
#677 I fix it.
image

**Pull request merged**
