### PR TITLE
sanear: try to detect backwards frame jump caused by DVD still handling in ffmpeg and reslave

### PR DESCRIPTION
**Pull request by adipose**
I've thrown out the event mode changes and tried something different, here.  When seeking to the title automatically, I create an artificial flush.  When catching this flush, I avoid pushing the jitter, as that causes the same hang.  This seems to work so far in testing.  Hopefully, avoiding any of the issues changing the buffers and event mode did.

I haven't figured out an obvious way to only avoid the reslaving jitter at the menu seek, so it's entirely off for DVDs at the moment.  I haven't noticed any serious issues with it, though.

### CODE REVIEW

**Comment by adipose** [comment]
@Aleksoid1978, @lifegpc

Please test.

**Comment by adipose** [comment]
https://mega.nz/file/UcABTCiB#dq7VDh7rpTbdKqxGMFOqGFq7Ym-_0ftFRbOKDcXM9FU

**Comment by lifegpc** [comment]
It has problem when drawing menu.
image

**Comment by lifegpc** [comment]
I can not see the menu, sometimes it will be no response.

**Comment by adipose** [comment]
https://mega.nz/file/VEJD0CRJ#whZYzgJf3sdok19ALIk9DYCxgobzypsXxU1GrRpYcAY

Try this build--I think that one was incomplete.

**Comment by lifegpc** [comment]
No sounds. And it stop playing .
image

**Comment by adipose** [comment]
Ugh, sorry, I had switched branches before I built that.  Hang on for a different build.

**Comment by lifegpc** [comment]
hmm. I will build this branch myself.

**Comment by adipose** [comment]
https://mega.nz/file/lNBXGKyS#UA4LPxqBOmMlTlHmO1QRTZAmt9onJ3h6zeFdfR-TcOc

Here's a good build, I think.  When merging manually, a line of code got changed, and some changes were reverted.  I think it's good again!

**Comment by lifegpc** [comment]
It works fine with MPC-VR/EVR-CP and Internal Audio Renderer.

**Comment by Aleksoid1978** [comment]
Some DVD not working normal - https://yadi.sk/d/uC8irKzTXahQ7A, working using standard sound output.

P.S. I think it's a bad way modify something in player's code, need modify Sanear's code. :)

**Comment by adipose** [comment]
Ha ha, I agree with you.  I am sure the problem is with pushing the reslave jitter.  The event loop never gives up after that, so maybe it is too long or something, and the stream ends before the jitter finishes.

However, if I don't flush, I can't control the way it pushes jitter at that time.  But I could disable it entirely.

**Comment by Aleksoid1978** [comment]
You can try "understand" how it's work in MPC-BE AR :)

**Comment by adipose** [comment]
I tried.  MPC-BE makes sense to me, sanear not so much.  The code is very confusing.

**Comment by adipose** [comment]
MPC-AR also had some interesting code to unslave just for DVD:

```
	if (m_bDVDPlayback) {
		m_pSyncClock->UnSlave();
	}
```

But this is just during a flush, which didn't occur in the problem dvd.  And sanear seems to unslave all the time, not just for DVD.

**Comment by Aleksoid1978** [comment]
MPC-BE AR slave/unslave in different place & some different in code for DVD/any other.

**Comment by adipose** [comment]
Incidentally, in MPC-BE, using EVR-CP and MPC-BE AR, the menu goes completely black in the problem DVD.  Hovering over a button causes it the menu to redraw and show up.

So even with MPC-BE, there is strange behavior with the auto-seek to the menu.

**Comment by Aleksoid1978** [comment]
Test in latest SVN(for me it's good) - https://yadi.sk/d/hlf1lfC8mKU58/!_last

**Comment by adipose** [comment]
No, the bug is still there for me using EVR-CP, even in that latest build.

**Comment by Aleksoid1978** [comment]
Hmm - for me all is good on this(my) test DVD. When menu is show - all is good.
Can you record video with "bug" ?

**Comment by adipose** [comment]
Check the original DVD causing the problem. 

https://1drv.ms/u/s!Aoq8mAMlVv8Ul1tXuHPKJlDTuEwO?e=3Uy59p

**Comment by Aleksoid1978** [comment]
All is good, testing with EVR-CP & MPC VR, all filter internal:
DVDMenu

**Comment by adipose** [comment]
What settings do you have here:

image

**Comment by adipose** [comment]
Strange.  I can reproduce every time.  Can you send me your settings (for mpc-be)?

**Comment by Aleksoid1978** [comment]
> 
> 
> Strange. I can reproduce every time. Can you send me your settings (for mpc-be)?

[MPC-BE.reg.zip](https://github.com/clsid2/mpc-hc/files/5205105/MPC-BE.reg.zip)

**Comment by adipose** [comment]
@Aleksoid1978 , @lifegpc please test:

After looking into this for a while, I've come to the conclusion that the ffmpeg hack is not handled well by sanear.  Maybe it's a bug in sanear, but I can't really find anything obvious.  What I can say is that is very confused by the sudden clock warp, and simply reslaving the clock when that happens seems to solve the issue.  My guess is that it is waiting (forever) to catch up after ffmpeg makes it jump backwards to force still frame display.

After looking at some other open source players that use ffmpeg (kodi, mythtv) they had all run into issues with ffmpeg in the past, and introduced hacks to deal with the stills (~2006).  But since then they have new code to process the DVD mpeg packets outside of ffmpeg (and removed their hacks from ffmpeg), and specifically deal with stills.  So, maybe this is a "bug" in LAVFilters which may not be worth fixing.  It's beyond my knowledge to fix it.

So, we are left with trying to deal with it in sanear or the player.  Sanear should probably not wait forever in this instance, but rather than make a change that might affect other things, this simply detects a clock warp of -1/2 DVD frame and reslaves when that happens.

I hope this doesn't break any of the other scenarios we've seen.

**Comment by Aleksoid1978** [comment]
Your test DVD - ok, but my DVD not good.

**Comment by adipose** [comment]
What does your DVD do?  I'm surprised this patch would affect it all.

**Comment by adipose** [comment]
I found a small code change in ffmpeg in that build. I reverted it now.  See if that helps.

https://mega.nz/file/tRJCmSqY#w9Cjwprs_sniGxjlbh1347X9YDbhcVESMVmnFAFITFg

**Comment by Aleksoid1978** [comment]
The same. You can check, here is DVD - https://yadi.sk/d/uC8irKzTXahQ7A
Playback stop after some seconds after start. Normal with system audio renderer, MPC-BE AR.

P.S. It's happened right now after sound is end while in menu.

**Comment by adipose** [comment]
https://mega.nz/file/wIIwEKBT#eOZ4nJXbjIfbx2swgRmgueJ-nE8dRwPt7lwIxjC9spE

I will test out that dvd. In the meantime, hwee is am uodated build. Last one didn't zip up the updated libs.

**Comment by adipose** [comment]
> P.S. It's happened right now after sound is end while in menu.

I'm confused.  What menu?  In your DVD I heard no sound in the menu at all?

**Comment by Aleksoid1978** [comment]
mpc-hc64-dvdaudio23y.7z - the same.
I mean not in menu - after opening DVD we have sound but it's play only some seconds using Sanear and then playback "stopped" and we have black screen. If using system sound renderer or MPC-BE AR - playback not stopped.

**Comment by adipose** [comment]
OK, I just listened to 2 minutes straight plus the pre-title bit, no loss of audio.

Is this the same DVD as before?  I'm downloading just in case.

**Comment by Aleksoid1978** [comment]
Hmm, very strange. For me - start playback and after this "logo" playback is stop, black screen & no sound.
DVD

**Comment by lifegpc** [comment]
I reproduce this problem with MPC-VR and Internal Audio Renderer.
But it seems sometimes works well, sometimes not.
image

**Comment by Aleksoid1978** [comment]
I using EVR-CP - the same.

**Comment by adipose** [comment]
I was checking a different DVD.  I did reproduce your issue.

https://mega.nz/file/ZIYExCII#XbEXUjMOxDlyecrk0SNvFFiSc1N-cDltmaLC3UidxaU

I've increased the sensitivity to 2ms.  I was trying to do 1/2 a DVD frame @ 24fps, but the video manager menus are sometimes 30 or 60fps.  That would be 8.33ms, which worked in my testing.  However, I set it even lower.

The clock relies on the "reference clock" which explicitly warns in the code that it uses "getprivatetime" to avoid negative clock seeks which can cause infinite loops.  But getprivatetime in sanear has multiple implementations, including the "audioclocktime" which is based on position and not an actual forward moving clock. Doubtless this is the real problem.

**Comment by Aleksoid1978** [comment]
Good !

**Comment by adipose** [comment]
> 
> 
> > Strange. I can reproduce every time. Can you send me your settings (for mpc-be)?
> 
> [MPC-BE.reg.zip](https://github.com/clsid2/mpc-hc/files/5205105/MPC-BE.reg.zip)

FYI, I tested using your settings--no problem.  However, you were using MPC-VR. Once I switched to EVR-CP with your settings, it goes to a black screen at the menu.  Only hovering is required to make it show up again.  Possibly my gfx card is behaving different than yours.

I can enter an MPC-BE bug if you like...

**Pull request merged**
