### PR TITLE
support tooltips for alpha sliders; support mousewheel tooltips (themed only)

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by NBruderman** [comment]
https://github.com/clsid2/mpc-hc/issues/2886

**Comment by adipose** [comment]
I was able to get my themed tooltips to work with the mousewheel.  Probably I could get unthemed ones to work as well.

**Comment by NBruderman** [comment]
> I was able to get my themed tooltips to work with the mousewheel.  Probably I could get unthemed ones to work as well.

Nice, might be worth a shot if its not too complicated

**Comment by NBruderman** [comment]
@adipose can https://github.com/clsid2/mpc-hc/issues/2886 be closed?
Or do you want to keep it open until you're done with unthemed sliders too?

**Comment by adipose** [comment]
I am busy for a few days but I will review the other issues and unthemed tooltips.

**Pull request merged**
