### PR TITLE
Fix for themed tooltip flicker in win7 classic theme

### PR DESCRIPTION
**Pull request by adipose**
Not ready to merge yet.

### CODE REVIEW

**Comment by adipose** [comment]
This is ready to merge.

**Comment by clsid2** [comment]
Found another bug with dark theme.

Add two filters in the external filters list. Use up/down to swap their order. Close window and re-open. The order has been reset to the original state.

**Comment by adipose** [comment]
> 
> 
> Found another bug with dark theme.
> 
> Add two filters in the external filters list. Use up/down to swap their order. Close window and re-open. The order has been reset to the original state.

Fixed.  That was a weird one.  I mistook the control for a listbox (vs. listctrl) and the style change caused it to think it was sort ascending. Completely random as the styles for listbox and listctrl aren't the same bitflags.

**Comment by adipose** [comment]
@clsid2 

Looking for some advice on doing future PRs.  I have the option to delete my fork, and start over, but I understand that will lose the history of the changes.   Continuing to do PRs off my fork is working fine.

Should I be creating branches, deleting my fork, or continue doing what I've been doing?  The one thing I don't like is my fork has a lot of commits which make the PR a bit less tidy for a small change.

**Comment by clsid2** [comment]
Probably best to create a new branch for future PRs.

**Pull request merged**
