### PR TITLE
Feature/auto shown preset

### PR DESCRIPTION
**Pull request by Sp3EdeR**

### CODE REVIEW

**Comment by clsid2** [comment]
I don't think such a behavioral change is good.

**Comment by Sp3EdeR** [comment]
@clsid2 what behavioral change do you mean? Can you elaborate please?

**Comment by clsid2** [comment]
Preset Normal must remain 3.

If your intention is to add a new preset with windowed controls hidden, then it must get a better name. Maybe "Auto Hide Controls". And hide menu as well.

**Comment by Sp3EdeR** [comment]
@clsid2 alright, sure! I'll move it over to the 4th viewing profile and rename it. Functionally, in this mode the controls are not shown, until the mouse is hovered over the appropriate edge of the window, so I thought that "Auto Shown Controls" would be a better name than "Auto Hidden Controls" perhaps. But I'm fine with either! :)

The main menu on the top of the window already gets hidden due to the frameless window style. Is there anything else that should be hidden? As far as I could test, this looks like minimal view, with panels floating in at the edges.

**Comment by clsid2** [comment]
Question is: what do people really need?

Currently HideWindowedControls can be combined with preset 2/3. So essentially there are 5 presets. By having set HideWindowedControls by the modified presets this flexibility disappears. So am am very hesitant to changing anything.

What you want to do is pretty much just:
1 and then Ctrl+1
Pressing that combo is pretty easy.

**Comment by Sp3EdeR** [comment]
@clsid2, I think that the profile I proposed is achieved by `1` with `HideWindowedControls` set to True, then `Ctrl+1`, `Ctrl+2`, `Ctrl+5`. This seems like a complicated way of achieving a "MediaCenter-like" UI, perhaps enough so for most users never to experience it. (By the way, what would your opinion be about calling the profile "Media Center"?)

The flexibility would still stay though, because HideWindowedControls could still be re-enabled after choosing Preset 2 (although not by hotkey currently). Since the controls are automatically hidden anyway, I would expect that most users probably wouldn't require the compact profile with autohidden view, since the additional controls take up no additional space when autohidden.

I thought that view profiles are to provide common, overall look-and-feel options to the user. If that is true, then perhaps the autohiding feature seems like a reasonable part of such easy, common profiles.

**Comment by clsid2** [comment]
I need to think about this a bit more.

Please remove the `&` from the menu string. I would like to avoid adding new accelerators to the menu, as they are not very useful and annoying for translators.

**Comment by clsid2** [comment]
Leave the PO file changes out of the PR. That helps to keep the patch small and prevents merge conflicts. It is trivial for me to sync them manually after merge. It also makes it easier to adjust the text.

I was thinking to make the fourth preset a CUSTOM one. The visible toolbars/panels and also value of BORDERLESS/HideWindowedControls could be specified by an advanced option, as a bitflag. Then users can make their own preset.

**Comment by Sp3EdeR** [comment]
I needed the PO files to be able to properly run and test a translated version of MPC-HC with the usage of each feature. When the new string is in a dialog and PO files aren't updated, MPC-HC messes up badly. When the string is part of a menu, translated MPC-HC does not display the item. So not updating PO files would make updates on my side harder. It would be possible to merge changes without the PO update commit using a git cherry-pick. I can remove the PO update commits though if you really need it.

The custom preset idea is cool for those that prefer to switch between presets often. But on the other hand, I believe that the point of presets is probably to offer the most typical UI scenarios for users that do not have the understanding to customize advanced options and panels one-by-one. (I've got a specific friend in mind here.) So I would propose to keep this preset available as a named option, due to its distinct and handy style, and adding a 5th, custom one. The custom one could default to showing a dialog that explains the way to set it up.

What do you think about my proposal, @clsid2?

**Comment by butterw** [comment]
I use normal + menubar hidden + controls hidden + HideWindowedControls + dark mode.

Adding a user-defined preset would be a great feature.
IMO anything else is too specific and ultimately not very useful. However, the user-defined preset could come with default values different from the normal preset, making it a fourth+ preset.

I'm not sure what preset covers, but one feature I sometimes need ON is the seekbar preview. This can't currently be set via command-line (contrary to a preset) and requires an app restart to activate. My work-around is to have a second mpc-hc version (50MB) with the option ON. OSD feature is similar. Maybe this could be handled by a user-defined preset or we just need a few more command-line switches.

**Pull request closed without merging**
