### PR TITLE
Add cue sheet support

### PR DESCRIPTION
**Pull request by lifegpc**
#687 
[Test file](https://1drv.ms/u/s!Aoq8mAMlVv8UnRpojkiUrHqtdf8R?e=mH0asO)
image

### CODE REVIEW

**Comment by clsid2** [comment]
Some documentation for cue sheets:
https://wiki.hydrogenaud.io/index.php?title=Cue_sheet

Things you should test if they are handled correctly:
- There can be multiple FILE entries
- TITLE/PERFORMER can appear at top level and at track level
- Unsupported tags such as REM/PREGAP should be skipped/ignored

**Comment by lifegpc** [comment]
Both FILE entries will be added to playlist.
I only handle TITLE/PERFORMER/FILE/INDEX, other tags will be ignored.
TITLE/PERFORMER can be distinguished correctly. Because I use ```cue_index``` to track it's location.
image

**Comment by lifegpc** [comment]
I think I should change label name if it has multiply FILE entries.

**Comment by lifegpc** [comment]
I should rewrite it to support ```Multiple files with gaps (Noncompliant)```.

**Pull request closed without merging**
