### PR TITLE
paint background of videowindow in preview

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by ale5000-git** [comment]
I don't know in what conditions but GetClientRect can fail so it may be worth check its return value.

**Comment by clsid2** [comment]
Should we maybe draw something tiny in the middle, so it is possible to see difference with a fully black thumb?
back_rbg
Example with three small square dots with colors from the 321 clipboard logo.

**Comment by adipose** [comment]
Yes, seems like a good idea.

**Comment by adipose** [comment]
> 
> 
> I don't know in what conditions but GetClientRect can fail so it may be worth check its return value.

`CWnd::GetClientRect` has void return value.  `::GetClientRect` has one, but perhaps only to deal with non-windows.  If you look at the code, there's an assert in `CWnd::GetClientRect` that requires it to be a valid window.  Presumably, as long as you call `CWnd::GetClientRect` inside an `::OnPaint` method, it's guaranteed to be true, anyway.

I could use the win32 one and pass the handle if I wanted to check the return value, but I guess it's unlikely to be a problem, or else the convenience method wouldn't have been created.

**Comment by adipose** [comment]
image

**Comment by clsid2** [comment]
res\noimage.png is missing

**Comment by adipose** [comment]
Added

**Pull request merged**
