### PR TITLE
merge updates to resizablelib from https://github.com/ppescher/resizablelib

### PR DESCRIPTION
**Pull request by adipose**
Try to bring our code as close to the latest as possible, while retaining useful mods.

### CODE REVIEW

**Comment by clsid2** [comment]
The `CalcSizeExtra` function is no longer needed with updated code? Just checking.

The custom code can be marked with this comment to easily find it in future when merging updates:
`// MPC-HC custom`

**Comment by adipose** [comment]
> The `CalcSizeExtra` function is no longer needed with updated code? Just checking.
> 
> 
> 
> The custom code can be marked with this comment to easily find it in future when merging updates:
> 
> `// MPC-HC custom`

Yes, he merged similar code after I reported the issue.

**Comment by adipose** [comment]
You can leave this open for now.  I'm going to see which patches I can get accepted before merging changes to mpc-hc.

**Comment by NBruderman** [comment]
> The `CalcSizeExtra` function is no longer needed with updated code? Just checking.
> 
> The custom code can be marked with this comment to easily find it in future when merging updates:
> `// MPC-HC custom`

The thing is that the maintainer said he'll look into the changes here and might integrate some, so some comments might become redundant shortly. This might be a non issue, but I just thought I might bring this up, just in case.

**Comment by adipose** [comment]
Once we agree on what changes make sense to merge, we may not need the comments at all.  But if we do need them, I'll see if it's possible to derive a class rather than changing the resizelib code.  This allows us to make it a linked project if we want, but even if not, merging is easier.

**Comment by adipose** [comment]
This latest commit is supposed to fix redraw issues that were covered up by an extra `Invalidate()` call.  The one I found difficult to fix was the gripper.  It seems like both windows and resizelib draw a gripper (in the case of a statusbar that has a gripper, that is).  I settled on invalidating the gripper itself after a resize.

Perhaps the ncpaint is supposed to exclude the triangular gripper, but I failed to get it working.

**Comment by clsid2** [comment]
Let me know when this is ready to merge.

**Comment by adipose** [comment]
We can merge it.  I haven't heard anything about my latest commits.  But I will revisit in the future.

@ppescher

**Comment by ppescher** [comment]
I'm sorry guys, I only can find a few hours a week to work on my "pet" projects and sometimes not even that.
And even worse, sometimes I just forget... guess I'm getting old, or maybe I need a vacation! :disappointed:

**Comment by adipose** [comment]
> I'm sorry guys, I only can find a few hours a week to work on my "pet" projects and sometimes not even that.
> And even worse, sometimes I just forget... guess I'm getting old, or maybe I need a vacation! 😞

No worries, I really appreciate you collaborating with us on this.  If it helps, maybe I can make a fork of your project with all the proposed changes and you can merge them back at your leisure, if you like them.

**Pull request merged**
