### PR TITLE
libass support for VSFilter

### PR DESCRIPTION
**Pull request by adipose**
It's not obvious how to change VSFilter settings, especially when they don't exist in the registry.  One change I made to make things behave better, is to default to Calibri when using a language hint, because Arial and Tahoma don't work with language hints, but are a common default (which may not have even been chosen deliberately).

With a better interface, we could alert them why it doesn't work, but I'm not sure if it's possible for VSFilter.

### CODE REVIEW

**Comment by clsid2** [comment]
I don't understand the need for the font replacement. If a font doesn't contain anything language specific, then it is logical that the language hint is ignored.

**Comment by adipose** [comment]
> 
> 
> I don't understand the need for the font replacement. If a font doesn't contain anything language specific, then it is logical that the language hint is ignored.

My thinking was this: a user sets the language hint, hoping to get some (usually Cyrillic) fonts working appropriately for their locale. It fails to work, because most fonts don't actually support language specific glyph variations.  As a result, they think the feature doesn't work.  When using VSFilter, to set the font, I didn't know of a better way to specify the font than setting the style string in the registry--and that style string isn't even there, by default.  So basically, you won't be able to get it unless you copy an entire style string, and specify Calibri or other compatible font.

In my opinion, it's not just that the font doesn't contain anything language specific.  Older fonts are simply not compatible with the concept of opentype language hinting at all.  If you had a .ssa subtitle, and it had a language hint, hopefully the maker would have chosen a compatible font, but for SRT, what's normally a suitable default (Tahoma) will fail even if you choose the hint language, which seems undesirable, to me.

A user that chooses an opentype language hint has essentially requested that language hinting work.  And unless we choose a newer font that can do it, it won't.  I didn't want to override deliberate font selection, even so, but I figured Tahoma or Arial were probably just defaults, so I limited the override to those.  This solution isn't perfect but in my opinion it's better than silently failing to show language specific glyphs.

Another option would be to just make Calibri the default font for subtitles, so we don't have to make this substitution.  Calibri has been included in Windows since Vista, so I think that would be acceptable.

**Comment by clsid2** [comment]
The settings are written to the registry if you change anything in the VSFilter settings GUI.

The language hint should not overrule the font. It is a secondary setting that depends on the chosen font. If that font does not support it, then it is simply ignored.

I changed the default from Arial to Tahoma because certain Unicode characters were not included in the Arial font. I need to test with Calibri to see if that is a suitable new default.

**Comment by adipose** [comment]
Sounds good--I can remove that code.  How do we get to the VSFilter settings gui?  Sorry for my ignorance, but I've never needed VSFilter before!

**Comment by clsid2** [comment]
Method 1:
Add it to external filters, then double-click on it.
Method 2:
Menu > Play > Filters
Method 3:
rundll32.exe vsfilter.dll,DirectVobSub

**Comment by clsid2** [comment]
Calibri as default is ok.

**Comment by adipose** [comment]
I made calibri the default and removed the reg code, now that I know how to edit settings (doh...why didn't I think of that).

**Pull request merged**
