### PR TITLE
improvments to preview window 

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by adipose** [comment]
Main fix here is the EVR parameter `MFVideoRenderPrefs_DoNotRepaintOnStop`

Also forced an Invalidate *after* setting the initial video position, which avoids the transparent video window.  I believe it was doing the initial draw before the window was visible, which required a second seek before it would draw.

**Comment by clsid2** [comment]
You added call to LoadKeyFrames() in OpenFile(), but it is also called in OnFilePostOpenmedia(). Was the original call being done too late? A check/fix is needed to avoid doing same thing two times.

firstShow is never set to true? Maybe you forgot to commit some code?

**Comment by adipose** [comment]
Loadkeyframes can be removed. The call was there in mpc-be, but it didn't cause me any problems in testing so I left it.

I remembered last night I never set that boolean. Which means the initial invalidate call never happens. But it still works pretty well. I will test it out some more.

**Comment by ale5000-git** [comment]
Do you have a test build, please?
So I can test if it fix the problem.

**Comment by adipose** [comment]
Test build:

https://mega.nz/file/sB5BRY6a#VVXqFoNgXmpyZpLL_Tr8BlTa3-LvZ-pG828MInOm8UE

**Comment by ale5000-git** [comment]
Thanks, I confirm that the flickering is completely fixed (at least for me).

PS: I have found another [issue](https://github.com/clsid2/mpc-hc/issues/860) but isn't really related to this PR.

**Comment by ale5000-git** [comment]
Is there an advanced setting to disable EVR (to test the other case)?

**Comment by clsid2** [comment]
VMR9 is still buggy. Not the preview video itself, but the window border/background/header.

With test build you would need to disable EVR on your system. For example by renaming this reg key:
HKEY_CLASSES_ROOT\CLSID\{FA10746C-9B63-4b6c-BC49-FC300EA5F256}

**Comment by ale5000-git** [comment]
```
With test build you would need to disable EVR on your system. For example by renaming this reg key:
HKEY_CLASSES_ROOT\CLSID\{FA10746C-9B63-4b6c-BC49-FC300EA5F256}
```
After doing this, EVR doesn't disappear from the list of renderer and additional it seems to be still used although in the filter list is now called only "Video Renderer".

**Comment by clsid2** [comment]
"Video Renderer" is VMR7.

Also rename:
HKEY_CLASSES_ROOT\CLSID\{083863F1-70DE-11D0-BD40-00A0C911CE86}\Instance\{FA10746C-9B63-4B6C-BC49-FC300EA5F256}

**Comment by ale5000-git** [comment]
VMR9 doesn't seems to have problems excluding the know issues.

**Pull request merged**
