### PR TITLE
When saving a subtitle, the path is remembered

### PR DESCRIPTION
**Pull request by Sp3EdeR**
The subtitle file is added to the recent file lists when autosaving subtitles.

This PR contains the changes requested in the following PR review:
https://github.com/clsid2/mpc-hc/pull/1511#pullrequestreview-1011425661

### CODE REVIEW

**Comment by Sp3EdeR** [comment]
Note: I only added the `SHAddToRecentDocs` call for autosaved subtitles, but did not add it for auto-opened subtitles. I'm not sure what way you want it, @clsid2.

**Comment by clsid2** [comment]
SHAddToRecentDocs is for Windows recent file. It should not be added using that. I meant the file history of the player itself.

**Comment by Sp3EdeR** [comment]
As far as I found, the application's recent files listing (`AfxGetApSettings().MRU`) only contains video and audio files by design, since subtitles cannot be played by themselves.

The subtitle open/saving functions use CFileDialog-s currently (directly on load, CSaveSubtitlesFileDialog -> CSaveTextFileDialog -> CFileDialog on save). The save dialog does not use the `OFN_DONTADDTORECENT` in its `OPENFILENAME` structure, so it should save to Windows recents and as far as I could see, the loading CFileDialog uses the recent files to populate its combo box too.

**Comment by clsid2** [comment]
No, the file history also stores external subs that below to a video.

I probably should do it myself once I get time for it. Saved subs will get auto-loaded anyway, so it is not important.

**Comment by Sp3EdeR** [comment]
Thank you for the info, @clsid2!
I believe I probably found what you meant. I hope this helps!

**Pull request merged**
