### PR TITLE
Pan & Scan rotate options in menu

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
Rotate x/y/z might be a bit confusing for most people. Doing one degree rotation steps through a menu isn't very practical either, so those options should be removed.

I would prefer the following menu entries:
- Rotate left (z=90)
- Rotate right (z=270)
- Flip (x=180)
- Mirror (y=180)

**Comment by adipose** [comment]
I think that sounds good, but there is something strange about the MPC-HC code.  Sometimes it rotates by 270, and sometimes it rotates by 2 degrees.  

What's the thinking here?

image

**Comment by adipose** [comment]
Basically we need two new options to rotate CCW 90, and we could reuse the two that rotate CW 90.  The others would not be discoverable through the menu, but they aren't particularly useful for most users, I'd say.

And then we should answer what the shortcut for CCW rotate should be, as the "good" shortcut for it is already taken by the 2 degree CCW rotate.

**Comment by clsid2** [comment]
The top case is for madVR and the bottom case for the other renderers. Long ago it did 2 degree steps in both directions. I changed that to do big steps in one direction.

Add CCW rotate without shortcut for now.

**Comment by adipose** [comment]
How is this?

image

**Comment by clsid2** [comment]
The names could be less detailed. Rest is fine.

"Rotate Clockwise"
"Rotate Counter-Clockwise"
"Flip Vertically"
"Mirror"

**Comment by adipose** [comment]
Done

**Pull request merged**
