### PR TITLE
support flip and mirror (requires patch to mpc-vr)

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by adipose** [comment]
@madshi

Any chance of implementing a "flip" command in madVR?  I see someone requested it in 2012 ;)

**Comment by adipose** [comment]
Depends on https://github.com/Aleksoid1978/VideoRenderer/pull/14

**Comment by madshi** [comment]
madVR currently supports rotation but not (yet) flip. You mean flip = mirror, right? What would be the purpose of doing a flip? I can understand why a user would want to rotate, e.g. maybe his phone recorded the video rotated, or maybe he uses his monitor in portrait view instead of landscape. But what's flipping/mirroring good for, in real life?

**Comment by clsid2** [comment]
Flip is upside down.

I don't know if these feature are used much in practice nowadays.

**Comment by adipose** [comment]
The code I wrote can both mirror (y axis) and flip (x axis) using a single flip command.

The API from mpc-be that I emulated actually refers to the vertical mirroring as "flip,"  but I adjusted for that in the mpc-hc code.

**Comment by adipose** [comment]
@madshi, @Aleksoid1978

Here is a youtube video explaining how to flip mirrored videos on VLC:

https://www.youtube.com/watch?v=kL9by-0Zm8A

I'm guessing somebody needed it at some point.  One possibility might be webcams, which can reverse the video to give the local user a feeling of looking in the mirror.  But if the video were recorded this way (typically the software would adjust the video sent to the remote viewer to be non-mirrored), any writing would be backwards.  I have seen this happen from logitech software bugs.

The main reason I request this feature be implemented in madVR and MPC-VR is for parity with the internal renderers.  It's a simple feature to support, and while it's probably rarely used, it's a regression when using either of those external renderers compared to mpc-hc internal ones.  To me, that's a good enough reason to support it unless it's overly onerous (since I already provided a patch for MPC-VR, I'm going to say it isn't ;) ).

**Comment by madshi** [comment]
It's easy to do, but still costs time to implement. Which I'm notoriously short of atm...  ;-(

**Comment by adipose** [comment]
Understood. I hope you will take the time but in the meantime we can mark it as unavailable when using madVR. Feel free to look at my patch for mpc-vr.

**Comment by adipose** [comment]
Oh, and I found this thread on doom9 from 2012:

https://forum.doom9.org/showpost.php?p=1594414&postcount=14332

image

;-)

**Comment by adipose** [comment]
@clsid2, mpc-vr now supports flip command.

https://github.com/Aleksoid1978/VideoRenderer/pull/14

Should probably be tested against this patch.

**Comment by clsid2** [comment]
Can you rebase this?

**Comment by adipose** [comment]
I think it is working.  The merge was a bit ugly but it looks ok, now.  Maybe test out a few things.

**Comment by clsid2** [comment]
If z=90/270 then flip/mirror actions seem to be swapped.

**Comment by adipose** [comment]
I had tested it before and got the same results as the built-in ones.

The "flip" command in mpc-vr was the same as our mirror command, I think.

**Pull request merged**
