### PR TITLE
Add player menu short only key

### PR DESCRIPTION
**Pull request by mustanggb**
Currently `Player Menu` executes `OnMenuPlayerShort()`, however it doesn't always show the short menu as the name suggests, instead it sometimes shows the short menu, and sometimes shows the long menu.

This pull request renames `OnMenuPlayerShort()` to `OnMenuPlayerAuto()`, as it more accurately describes it's usage, and adds a true `OnMenuPlayerShort()` that always shows the short menu.

**Summary**
```
        "Player Menu" => "Player Menu (auto)"    [rename]
                 NULL => "Player Menu (short)"   [new]
 "Player Menu (full)" => "Player Menu (long)"    [rename]
"OnMenuPlayerShort()" => "OnMenuPlayerAuto()"    [rename]
                 NULL => "OnMenuPlayerShort()"   [new]
```

**ToDo**
- Test it works

### CODE REVIEW

**Comment by clsid2** [comment]
I don't see any need for adding yet another shortcut.

**Comment by mustanggb** [comment]
What would you suggest then?

As I see it the other alternatives are:

1. Remove the auto functionality from `OnMenuPlayerShort()` so it works as described. Which isn't ideal for anyone that prefers the current functionality.
2. Remove `Player Menu (full)` key bind, and instead have a dropdown somewhere else in the interface to select which of the three functionality applies to the `Player Menu` key. I personally wouldn't mind this, but thought the way proposed in this pull request was more in keeping with existing philosophy, hence more likely to be the preferred route to go.

**Comment by adipose** [comment]
Unless the main menu is hidden in some way, Short shows the short menu.  But in the interface, it simply says "Player Menu", which is neutral.  So, I feel like it's not in need of correction (perhaps internally it could be named OnMenuPlayerShortExceptWhenMainMenuHidden or something better).

Long (or "full" as it says in the interface) always shows the full menu.  

So, the real question is, what's the value of the short menu during full screen, which is the only feature I can think that would be added here?  Maybe you can explain better what you wanted to do.

One other thing--now that fullscreen allows other screen controls, perhaps the "auto" functionality should be revisited.  There's no need to show the full menu on the controls screen in that event.

**Comment by mustanggb** [comment]
```
Maybe you can explain better what you wanted to do.
```
Perfect comment/question!

I probably should have mentioned the reasoning behind it.

Basically I typically play videos in two ways. Firstly as an always-on-top picture-in-picture type setup whilst doing other work; which means I have it setup as a small window in the corner, with menu turned off (as you said), controls only appearing on hover, etc. in order to maximize available screen area for the other work. Secondly as a dedicated sit down viewing experience; which means fullscreen.

Now with that in mind the reasoning for wanting to always have the short menu is also two-fold. Firstly to have the windowed and fullscreen menu's be the same, for the sake of speed as it relates to muscle memory and cognitive load. Secondly to have options that are toggled on a multi-times a day basis to be at the top level rather than having to drill down each time, again for the sake of speed and cognitive load.

```
what's the value of the short menu during full screen
```
To clarify fullscreen does show the short menu, it's windowed (without menu) that is lacking it.

---

It might be worth mentioning that MPC-BE does have the ability to force short menu always. I was somewhat hesitant to mention this initially for fear of being told "well go and use it then if you love it so much". The reality is that both players have different advantages/disadvantages/bugs/features, so if a few features from there can be ported over it would give the best of both worlds. To me here is the more logical place to congregate on, and in the spirit of open source also thought others would also like to have these features. Not to mention #1387 seemed like feature requests in the form of pull requests would be warmly welcomed, so I am a little perplexed by the response thus far, i.e. a blunt no followed by radio silence.

**Comment by adipose** [comment]
Sorry, I was referring to d3d full-screen. 

Anyway, I think an advanced option to show the short menu when the main menu is hidden, might work. That would give a consistent experience for those who switch frequently.

Adding shortcuts is generally  avoided as having too many clutters things and makes it harder to find the right one. There are already so many.

**Comment by mustanggb** [comment]
Like I said, open to alternative suggestions. But not much point working on it until there is buy-in from someone with commit access. So back to waiting.

**Comment by clsid2** [comment]
I am tempted to just modifying it to have just a single menu, which looks mostly like the "short" one. The "long" one doesn't actually have that many more entries, it just less organized.

For example, having play/pause on top level is useless, as 99% will just click on the video to do that or use spacebar. Same for volume, adjusting that through menu is not done often.

**Comment by adipose** [comment]
I agree. I don't care for the long menu much. However for those who used it, perhaps its functionality can still be found via the dedicated "long" shortcut?

Advanced option I was thinking is "always show short menu", but maybe it's better for short to be the default, especially if we can add a few missing entries.

**Comment by adipose** [comment]
I think unifying the menus is a worthy goal.  I wonder how many people even realize the difference between the two and actually like how it works.  However, it has been this way a long time so I'm not sure how popular a big change would be.

In the meantime, here's a small patch to use an advanced option to keep the menu consistent even if the main menu is hidden:

https://github.com/clsid2/mpc-hc/pull/1674

**Comment by MadokaAyukawa** [comment]
Perhaps I'm mistaken, but setting that advanced option to true gives me what I though was the long menu all the time.

**Comment by adipose** [comment]
> Perhaps I'm mistaken, but setting that advanced option to true gives me what I though was the long menu all the time.

I can't comment on what you thought was the long menu.  But below is the relevant code.  Maybe you missed the not (!).  

If the new setting is false (which is the default), there are cases where calling for the short menu (via right click) will actually get you the long menu.  But if you set it to true (again, this is NOT the default), it ALWAYS has to provide the short menu, no matter the player state.

image

**Comment by MadokaAyukawa** [comment]
You are way above my pay-grade. LOL. I thought this was the short menu.

image

But the I get the longer one with Fullscreen and Play/Pause. It's fine if I'm mistaken.

**Comment by adipose** [comment]
I believe that's the long menu as it basically has every single "main menu" category at the top level and you can drill down into it.  The thinking is, if the main menu is hidden, you might need on of those features, so we need to show you every single option instead of just the convenient options at the top level.  If you were to drill down you'd see this menu has more options than the other.

**Comment by MadokaAyukawa** [comment]
I see. I have it backwards then. My bad. But that was the menu I wanted all time. I'll try to get used to the other one. Thank you for your kind explanation.

**Comment by xLn2** [comment]
1.9.21.13 , tested with window mode
| Compact view & AlwaysUseShortMenu=False | Compact view & AlwaysUseShortMenu=True | Normal view & AlwaysUseShortMenu=False | Normal view & AlwaysUseShortMenu=True |
| ------------- | ------------- |------------- | ------------- |
|resim|resim|resim|resim|

I think there is some misleading or bug, when I hide menu with ctrl+0 the Option "AlwaysUseShortMenu" looks like working in the opposite way. In my opinion ~~when menu is hidden~~ it should always show shortmenu in windowed mode with this option.

**Comment by adipose** [comment]
It looks fine to me.  As I mentioned the menu on the left is the "long" menu.  So you can see that when alwaysuseshort=true, it's always showing the same menu.  Which is what we want.  We don't want it randomly giving different menus depending on the player.

When it is false, you can see that it changes which menu it shows depending on the window view.  Which is the original complaint, though that is the way the player was designed--give a different menu when the main menu is hidden.

**Pull request closed without merging**
