### PR TITLE
enable safezone for seekbar

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
It seems to work for dragging only?
Using it also for accidental clicks above the seekbar might be a good idea.

Additionally, disable seeking in the whole toolbar area below the seekbar would be fine with me as well.

**Comment by ale5000-git** [comment]
Just be sure to not disable the dragging of a video from explorer to MPC-HC in that place.

**Comment by kasper93** [comment]
This was very crude way for someone to test how safezone works for him back in the day. I don't think it should be included in this form. 

1. Safezone should be configurable 
2. Safezone needs to be scaled by DPI, just hardcoding raw value is wrong
3. I don't remember if it actually did solve the problems it supposed to ;) And not sure even if it shouldn't be implemented differently.

Also I don't mind personally, but as a rule of thumb you should actually credit were the code you are using comes from.

**Comment by adipose** [comment]
> 
> 
> This was very crude way for someone to test how safezone works for him back in the day. I don't think it should be included in this form.
> 
>     1. Safezone should be configurable
> 
>     2. Safezone needs to be scaled by DPI, just hardcoding raw value is wrong
> 
>     3. I don't remember if it actually did solve the problems it supposed to ;) And not sure even if it shouldn't be implemented differently.
> 
> 
> Also I don't mind personally, but as a rule of thumb you should actually credit were the code you are using comes from.

Yes, I should--a bit lazy, although the source of the code was documented in the original issue I referenced. :)

Since the code was contributed as a patch to the same project at some point, I just figure "it's all good."  But I will try to be better about that.

Ideally the safezone would be dpi configured, but my main goal was just to have an empty area at the bottom that doesn't get accidentally clicked.  I wasn't too concerned about it being a specific size as much as being "far enough" to avoid any problems.  I don't imagine many people are trying to drag from the bottom of the video window.

Honestly, I don't use this feature and I think it's of questionable value anyway.  There are windows shortcuts like win+shift+left that move windows to the next monitor.  But if a tiny patch can help make it less annoying, then we can keep it in.  Not something I wanted to spend much time on. ;)

**Comment by kasper93** [comment]
> Ideally the safezone would be dpi configured, but my main goal was just to have an empty area at the bottom that doesn't get accidentally clicked. I wasn't too concerned about it being a specific size as much as being "far enough" to avoid any problems. I don't imagine many people are trying to drag from the bottom of the video window.

What I mean we have `m_dpi.ScaleX` and `m_dpi.ScaleY` so it simply should be applied. Depending on Windows scaling settings current safe zone will be inconsistent.

**Comment by adipose** [comment]
> 
> 
> > Ideally the safezone would be dpi configured, but my main goal was just to have an empty area at the bottom that doesn't get accidentally clicked. I wasn't too concerned about it being a specific size as much as being "far enough" to avoid any problems. I don't imagine many people are trying to drag from the bottom of the video window.
> 
> What I mean we have `m_dpi.ScaleX` and `m_dpi.ScaleY` so it simply should be applied. Depending on Windows scaling settings current safe zone will be inconsistent.

Yes, I understood.  That would be an improvement, but we probably need to check by monitor as well.

**Comment by clsid2** [comment]
It also causes a small regression in compact view mode (only video + seekbar). Then it is not possible to resize the window by dragging the bottom right corner.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1177

I changed this a bit.  Depending on the situation, it wouldn't have had the right point mapping (the code I left out from the original patch changed all the passed points to be in screen coordinates).  That should be fixed.

I also changed it to not expand horizontally.  Since the seekbar goes to the edges (at least in dark theme), it didn't seem necessary.  This should fix the sizing regression.

**Pull request merged**
