### PR TITLE
freetype codepath enhancements

### PR DESCRIPTION
**Pull request by adipose**
This is more code than I intended, but it does work in my limited testing.

1. Move caching of freetype to the RTS class so it lasts for the whole subtitle instead of the individual raster class (one word/sub?)
2. Add advanced option to enable freetype codepath
3. Resurrect the OpenTypeLangHint (from libass fork) but did not add interface to update it, only through registry for now
4. Use lang hint to grab per language glyphs using harfbuzz

The only real use of this is the case of serbian specific characters when otherwise russian would display (and any other languages with special font codepoints).  I tested and it works.

Problems I observed:

1. RTL langauges are not supported.  They can solve this by not enabling the advanced option...
2. FT path only works one char at a time, and this might cause other rendering issues with languages that have behavior for characters that run together (including RTL)

BTW I tested LIBASS codepath and it was working ok.  I don't know what issues we needed to fix there, but this is a more limited way to enable per-language glyphs.

### CODE REVIEW

**Comment by clsid2** [comment]
I won't be near my dev system to test this for about a week or so.

I haven't tested the libass stuff in a long time. It might have gotten better since then due to library updates and other changes. Maybe you can make a libass test build for others to play with and test.

Don't the libass based players support RTL either? Or is the issue just with our FT codepath?

**Comment by adipose** [comment]
> I won't be near my dev system to test this for about a week or so.
> 
> I haven't tested the libass stuff in a long time. It might have gotten better since then due to library updates and other changes. Maybe you can make a libass test build for others to play with and test.
> 
> Don't the libass based players support RTL either? Or is the issue just with our FT codepath?

Just our path.  The way it works (today) is it tries to render using windows, but if that fails, it goes into a special codepath to render one char at a time, using a FT capability to grab the vertices.  I don't think freetype has a function for a whole string, just a char, but I didn't look that closely before.  Libass of course is doing full FT+HB rendering/shaping so even RTL and merged unicode chars should work.

**Comment by clsid2** [comment]
The subtitles at the top have wrong characters with this sample.
https://www.sendspace.com/file/g9xenv

Edit: added reduced test case. Seems to be an issue with a specific font. 
VLC has the same bug.

**Comment by adipose** [comment]
> The subtitles at the top have wrong characters with this sample. https://www.sendspace.com/file/g9xenv
> 
> Edit: added reduced test case. Seems to be an issue with a specific font. VLC has the same bug.

So to be clear, is it trying to use eng for hinting?  I wonder if we should introduce a mapping where hinting needs to be compatible with the language noted in the subs?

I don't think eng has any special hinting so I wonder what it's doing, here.

**Comment by clsid2** [comment]
There is no reason for the language tag. Just ignore it.

The issue with this font is likely a Freetype bug, so not much we can do I think.

**Pull request merged**
