### PR TITLE
get a pin from graph for finding fonts later

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
In `CSubtitleInputPin::DecodeSample()` an optimization is possible I think. Set the graph only once, when its value is nullptr.

**Comment by adipose** [comment]
> In `CSubtitleInputPin::DecodeSample()` an optimization is possible I think. Set the graph only once, when its value is nullptr.

I don't think it would change, but I added a check to only do the update if it has changed (including from nullptr).

**Comment by clsid2** [comment]
`GetGraphFromFilter` call could be skipped as well if nullptr check is moved. The graph itself should not change.

**Comment by adipose** [comment]
See what you think of this approach.

**Pull request merged**
