### PR TITLE
support dark thumbnails for people using dark theme

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
Maybe add a `bool darktheme` to cache return value of AppIsThemeLoaded()?

**Comment by adipose** [comment]
You mean within the function?  Sure, can do.  It is already a pointer to a boolean, though:

`static_cast<CMPlayerCApp*>(AfxGetApp())->m_bThemeLoaded`

**Comment by clsid2** [comment]
No, I meant to add a local bool value in SaveThumbnails function.

**Comment by adipose** [comment]
> No, I meant to add a local bool value in SaveThumbnails function.

Yes that's what I thought you meant. I was just saying it is a static bool already but local is faster.

**Pull request merged**
