### PR TITLE
support dynamic widget position and size

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by adipose** [comment]
I've made some code updates to do dynamic alignment based on widget pairs.  It works better across DPIs now, though you can get close by eyeballing it.  The different DPIs scale text and combos a bit differently.

Here's how it looks currently:

image

**Comment by clsid2** [comment]
Not directly related to this issue, but people have some difficulty with finding the seekbar video preview option due to it being "hidden" in the dropdown as a non-default value.

What do you think about changing the hover type dropdown to two checkboxes?
[ ] Show time
[ ] Show video preview
(time can be ignored if preview is checked, or even preview could be shown without time, but not really important)

Hover -> Hover position ?
(and below the two new checkboxes)

Language box could be removed to right column to make more space in left column.

**Comment by adipose** [comment]
Sounds like a good idea. Radio button could work:

[]preview and time
[]time
[]none

**Comment by clsid2** [comment]
Just "preview" and "time" is enough. Both unchecked = none.

**Comment by adipose** [comment]
My concern is the unchecking of "time" won't be honored if "preview" is checked, unless we modify the preview code to pay attention to that (I'd rather not--time on the preview is useful but harmless if you didn't want it).

**Comment by clsid2** [comment]
Preview will simply include time regardless of time setting. No need to make things complex. Time checkbox could be greyed out if preview is enabled.

**Comment by adipose** [comment]
I've updated more pages with the new dynamic layout, which handles both vertical centering and dynamic width for languages, where possible.

**Comment by adipose** [comment]
It looks like this has the unfortunate side effect of changing the translations for all the elements that I changed the ID for: STATIC->STATIC1.

I'll see if my other script can be updated to handle this.

**Pull request merged**
