### PR TITLE
Addic7ed subtitles provider

### PR DESCRIPTION
**Pull request by awawa-dev**
Implemented Addic7ed subtitles provider. Because there is no API available then we must use their web pages and parse the result, so it's prone to changes. To be able searching using WWW form and to download subtitles, the cookie must be obtain first. User authentication is not necessary so far.

### CODE REVIEW

**Comment by clsid2** [comment]
I will look at this after 1.9.17 release.

It should probably be excluded from the automatic search. Because it doesn't provide "exact match" (hash) based results. But also to avoid them blocking us due to an excessive amount of searches.

**Comment by awawa-dev** [comment]
You mean disabled on default and required to enable? That's OK, they blocked me for ~2 hours already after some time of testing needed for development. But it was short period of intensive work. mpc-hc agent identifier doesn't work for me from the start so popular one alternative must be used. Despite lack of hashes addict7ed provides very good quality hit results based on the release name. We can force user to provide their login/password and include authorization if necessary to reduce the amount of unauthorized searches (we have already working cookie mechanism).

**Comment by clsid2** [comment]
Yes, it should be disabled by default. At least initially.

What I mean is that it should also be excluded from the automatic search when that is enabled in the player options. So it should only be included in manual search (press D). 

It would be a waste of effort if it gets blocked due to high amount of traffic. OpenSubtitles moved to login requirement after traffic spikes at being of the pandemic.

**Comment by awawa-dev** [comment]
I understand but from my perspective that operation scheme is pointless (usage in HTPC mode).

**Pull request closed without merging**
