### PR TITLE
light theme and other theme changes

### PR DESCRIPTION
**Pull request by adipose**
1. Moves theme settings to a dedicated property page
2. Adds an option to choose dark/light/follow windows theme
3. Ability to change theme colors is implemented now (can be used for use-selected colors in the future, but nothing implemented)
4. Light theme first try

The dark theme necessitated theming a lot of basic controls in the property pages, whereas the light theme can mostly live with the default windows controls.  A new macro, `AppNeedsThemedControls` has been added to disable theming on many light widgets.  If the widget will be themed, even in light mode, we can use `AppIsThemeLoaded` instead.

In some cases, we may want to redo those widgets anyway.  It's not super urgent as long as it's "light," IMO.  Radio buttons, checkmarks, listboxes/listcontrols, links, etc. are just using the windows defaults for now.

Classic:

image

Dark:

image

Light:

image

### CODE REVIEW

**Comment by clsid2** [comment]
Looks good.

I plan to release a stable build soon (probably end of month). So this merge will need to wait until after that is done.

Can you do a Transifex update?

**Comment by adipose** [comment]
> Can you do a Transifex update?

Done

**Comment by clsid2** [comment]
Is this ready for merge?

**Comment by adipose** [comment]
Yes, it should be.

**Comment by clsid2** [comment]
Modern Seekbar option should be greyed out when modern theme is disabled. Or just removed altogether. I don't think many people use old seekbar with modern theme?

I was thinking to increase default seekbar height a bit too? What do you think about 16?

**Comment by clsid2** [comment]
Small bug in light theme:
mpc_light_theme_bug1

The red area is normally light grey.

**Comment by clsid2** [comment]
In the Download subtitles dialog, the status bar has red background.

On the "Keys" option page, the table headers also have red borders. Also for Subresync table headers.

Same for the table on the Audio Switcher page.
mpc_light_theme_bug2

On Miscellaneous page, the tracks of the color control sliders could be a tiny bit darker. Barely visible now.

In Add Favorite dialog, the V on the dropdown button is barely visible.

Subtitle Styles dialog has a red border.

The X to close Subresync in left top is only visible when hovering above it. Same for playlist. Plus the X has red background.

**Comment by adipose** [comment]
I used red for theme changes I didn't think I needed.  I'll see what I missed.

**Comment by adipose** [comment]
> Modern Seekbar option should be greyed out when modern theme is disabled. Or just removed altogether. I don't think many people use old seekbar with modern theme?
> 
> I was thinking to increase default seekbar height a bit too? What do you think about 16?

I personally use 24, but I'm happy to increase the default.

Regarding the old seekbar, it does work with the dark theme, but of course I don't use it.  Not sure if anyone would care if we just disabled it in the theme.

**Comment by clsid2** [comment]
Yeah, lets remove the option and just always use modern seekbar in modern theme.
Default height can go to 16.

**Comment by adipose** [comment]
> Yeah, lets remove the option and just always use modern seekbar in modern theme. Default height can go to 16.

Done

**Pull request merged**
