### PR TITLE
Snapshot features

### PR DESCRIPTION
**Pull request by adipose**
Import some code from mpc-be and rewrite/replace it where necessary to conform to mpc-hc codebase.  A couple other minor features as well.

1. Save images in DAR using EVR, EVR-CP, and MadVR
2. Support mpc-be feature to render subtitles onto screenshots
3. Add advanced option to remove video extension from snapshot filename.
4. Support checkbox theming on windows file dialog.

### CODE REVIEW

**Comment by clsid2** [comment]
Looks good. I will test it later this week.

**Comment by clsid2** [comment]
Does it also work with EVR Sync? Could VMR-9 also be supported if it isn't yet?

**Comment by adipose** [comment]
VMR9 shares the same code for GetDIB, I believe, and works in both renderless and windowed mode.  SyncRenderer did not work.  I think I saw an mpc-be patch for that, actually.

**Comment by adipose** [comment]
SyncRenderer is working now, too.

**Comment by clsid2** [comment]
The "include subtitles" doesn't have effect with madVR. It follows the screenshot settings as defined in madVR options. To avoid confusion, perhaps it is best to hide the option when madVR is used, and respect the madVR settings? It should also be hidden for renderers that do not support internal sub renderer, such as plain EVR.

With MPC Video Renderer, it still uses SAR. Including subtitle works.

The quality of the subtitles in the screenshots is worse than during playback. The edges are ugly. No alpha blending?

**Comment by adipose** [comment]
It's now disabled with madVR.
MPCVR problem is unclear.  I've imported a few more pieces of code, but the framegrabber piece is external.  Something must alert it to use DAR, but I couldn't find it.
Fixed the subtitle rendering.  Was a bug in the color format chosen.

**Comment by clsid2** [comment]
I will merge this now. We can look at the MPCVR AR issue later, since it isn't a regression compared to existing functionality.

**Pull request merged**
