### PR TITLE
snapsizing

### PR DESCRIPTION
**Pull request by adipose**
Merged from sp3eder.  I currently see one bug with incremental zoom.

If the window is wider than tall, and snapped to the bottom, it only grows horizontally.

### CODE REVIEW

**Comment by adipose** [comment]
It seems to work ok, now.  I'm not sure about the extra block of code I've commented out.  It seems to do double duty, but there must be a purpose.

**Review by Sp3EdeR — COMMENTED** [review]
There is no point to change CMainFrame::OnViewModifySize at all, if the window size is limited to the current monitor's size. No snapping to be done here then.

**Comment by adipose** [comment]
Thanks, I understand now.

So if we zoom towards center of the monitor, we'd only need to deal with windows exceeding the monitor dimensions.  Perhaps incremental zoom should only zoom to that point anyway.

However, honoring the snapped edges currently works with incremental zoom, which is pretty useful imo.

**Comment by Sp3EdeR** [comment]
> Thanks, I understand now.
> 
> So if we zoom towards center of the monitor, we'd only need to deal with windows exceeding the monitor dimensions. Perhaps incremental zoom should only zoom to that point anyway.
> 
> However, honoring the snapped edges currently works with incremental zoom, which is pretty useful imo.

That behaviour is already part of the 2.2.1 version. The `GetZoomWindowRect` invocation forces the window to be within the current monitor's bounds, which also implies that snapping will happen, just differently.

**Comment by adipose** [comment]
> There is no point to change CMainFrame::OnViewModifySize at all, if the window size is limited to the current monitor's size. No snapping to be done here then.

I took your suggestion and reverted that.  Everything works fine from my view.  Incremental zoom works about the same as before, and resize snapping is working.

I did include a fix here because `fRememberWindowPos` interferes with incremental zoom.

@clsid2, I think this can be merged as-is.

**Comment by NBruderman** [comment]
@Sp3EdeR what else is left to be fixed?

**Comment by Sp3EdeR** [comment]
> @Sp3EdeR what else is left to be fixed?

Nothing in this PR. Snapping on resize works fine. As for the incremental zoom feature, everything listed in issue #2740.

**Pull request merged**
