### PR TITLE
add gaussian blur

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by butterw** [comment]
1.9.8.36 (dbfcf7221-dirty) (patch157) (develop@a91c9d4), Nov 15 2020
- Gaussian Blur 3x3.hlsl (9textures, 15 arithmetic): OK

Performance can be improved with a hw linear sampling optimization, if supported:
https://github.com/butterw/bShaders/blob/master/test_linearSampling/bSmooth_test.hlsl
I've opening #748 with regard to the support status of this feature in mpc-hc.

- Gausian Blur_pass >> typo: Gaussian 
Also based on hardware linear sampling >> Result is incorrect if the feature isn't supported !!!

_pass1, _pass2: I'm getting different results vs renamed individual passes (tested using presets and 3*2passes) !!!

**Comment by adipose** [comment]
> 
> 
> 1.9.8.36 ([dbfcf72](https://github.com/clsid2/mpc-hc/commit/dbfcf7221e0384dedb8a3f3b00f88bd8e2cfc679)-dirty) (patch157) (develop@a91c9d4), Nov 15 2020
> 
>     * Gaussian Blur 3x3.hlsl (9textures, 15 arithmetic): OK
> 
> 
> Performance can be improved with a hw linear sampling optimization, if supported:
> https://github.com/butterw/bShaders/blob/master/test_linearSampling/bSmooth_test.hlsl
> I've opening #748 with regard to the support status of this feature in mpc-hc.
> 
>     * Gausian Blur_pass >> typo: Gaussian
>       Also based on hardware linear sampling >> Result is incorrect if the feature isn't supported !!!
> 
> 
> _pass1, _pass2: I'm getting different results vs renamed individual passes (tested using presets and 3*2passes) !!!

Please retest with latest build.

https://mega.nz/file/NEgWESSB#AjV6IRXv4jijEj07i4Pk2qpNnC2R6rn59irHn7Uy9jE

**Comment by butterw** [comment]
I would suggest keeping the final _ in the shader name, so that it is clear there are multiple passes.
ex: blurGauss_pass1 becomes "blurGauss_", instead of "blurGauss".  
tested OK in EVR-CP PreResize (same result) 
PreResize2=.\blurGaus.hlsl;.\blurGaus_Y.hlsl;.\blurGaus.hlsl;.\blurGaus_Y.hlsl;.\blurGaus.hlsl;.\blurGaus_Y.hlsl
PreResize1=.\blurGauss_pass1.hlsl;.\blurGauss_pass1.hlsl;.\blurGauss_pass1.hlsl

_pass3 seems to be also applied, which is good as there are use cases for more than 2-passes.

**Comment by adipose** [comment]
Maybe the first one can always be named multipass.

**Comment by butterw** [comment]
name length is a real issue in the interface and nobody uses _ at the end of shader name.

**Comment by adipose** [comment]
Sure, but _ doesn't really convey anything to the average user, either. Perhaps (MP) is enough.

**Comment by butterw** [comment]
if there are 2 passes _2p would be useful.

The place where name length is most critical is the compiler debug list because the whole path is used.

**Comment by adipose** [comment]
I implemented formatting now to show the number of passes in the interface.

image

**Comment by adipose** [comment]
In debug shaders, it doesn't actually show the adjusted title.  I'm not sure if that matters too much.  But the second pass doesn't even show up to be debugged, there.

**Comment by butterw** [comment]
I thinks it's looking good.
To be able to debug the subsequent passes you would need to rename. But most people don't debug.
The length problem is really caused by including the full path in the debug selector (IMO should be just folder/filename with the full pathname as tooltip). 
Maybe filename length can also be an issue in the shader list if you are importing shaders from outside ./Shaders.

**Comment by adipose** [comment]
Good idea for the drop-down. You can enter another bug for that.

**Comment by adipose** [comment]
@butterw , can you create dx11 versions of those shaders?  It should require only minor changes.

**Comment by butterw** [comment]
I don't mind converting the shaders to dx11. 
But I will not be able to test them: dx11 (in mpc-vr) doesn't work in mpc-hc for me.

**Comment by adipose** [comment]
> 
> 
> I don't mind converting the shaders to dx11.
> But I will not be able to test them: dx11 (in mpc-vr) doesn't work in mpc-hc for me.

Why not?  Maybe you need to change the registry.

image

**Comment by butterw** [comment]
It does work briefly.

Every time I restart mpc-hc, I have to change (tick anything in mpc-vr) & apply, otherwise I get a black screen. I also get a black screen on seeking.

**Comment by clsid2** [comment]
Which OS and GPU do you have?

**Comment by butterw** [comment]
Win10.0 / Intel hd4400 igpu.

**Comment by clsid2** [comment]
Then I would expect D3D11 to work properly. Which W10 build? And which Intel driver version?

I recommend submitting a bug report here:
https://github.com/Aleksoid1978/VideoRenderer/issues

**Comment by butterw** [comment]
I only recently tested mpc-vr. I do plan put in a request for pre-resize shaders and ask about this dx11 bug.

**Comment by adipose** [comment]
> 
> 
> I only recently tested mpc-vr. I do plan put in a request for pre-resize shaders and ask about this dx11 bug.

So far I have had no issues with dx11, but maybe something with your driver.  As for pre-size, we already opened a request and it was denied.  But feel free to try!

**Comment by butterw** [comment]
dx11, untested:
[Shaders11.zip](https://github.com/clsid2/mpc-hc/files/5577445/Shaders11.zip)

**Comment by adipose** [comment]
I didn't check why, but it doesn't successfully load these shaders.

**Comment by adipose** [comment]
I've added those two, now.  The problem was unrelated to the shader files.

**Comment by clsid2** [comment]
Is this ready for merging?

**Comment by adipose** [comment]
Yes, I think so.

**Pull request merged**
