### PR TITLE
Support filling volume and seek controls instead of showing dragger

### PR DESCRIPTION
**Pull request by adipose**
image

### CODE REVIEW

**Comment by clsid2** [comment]
Looks great.

The advanced option tooltip should probably also mention "Only applies to Dark Theme" for clarity.

An option to specify the seekbar height (regardless of theme) would be nice too if you could add that. Similar to the toolbar button size option.

**Comment by adipose** [comment]
See what you think.  I support heights from 4-8 pixels @96dpi. The old height was ~4.  To go thicker I would have to mess with the resource for the seekbar, which controls the full height of that area (not just the channel area).  At 8 pixels the dragger in classic mode maxes out.  If we lost the dragger we could go thicker.

image

**Comment by adipose** [comment]
I think the dark theme should just default to the screenshot above, which is "fill" on and seekbar height=8.  However, in classic mode, seekbar height=8 looks less good.  So I'm at an impasse for how to control the seekbar height in both modes.

One possibility is to make the seekbar match the height of the dragger when it's not there.  Then the official height could be that of the dragger, rather than the channel.

**Comment by clsid2** [comment]
> I think the dark theme should just default to the screenshot above, which is "fill" on and seekbar height=8.

That is ok.

> One possibility is to make the seekbar match the height of the dragger when it's not there. Then the official height could be that of the dragger, rather than the channel.

That is good solution. Perhaps we can allow larger values when theme is active (up to 32)? And just cap it to 8 in the drawing code when classic mode is used. Some people use their TV and have large viewing distance. So they will appreciate the ability to have option for huge controls.

Perhaps it will also look better with current position displayed as a colored vertical line (red/blue)? Then it is more recognizable as a seekbar, specially at start of playback when the filling effect isn't visible yet.

**Comment by adipose** [comment]
Check it out (this is @ 32 high). I think I have enabled all the features you mentioned.  Min is 15 (which is = the current classic them dragger height) and max is 32.

image

**Comment by clsid2** [comment]
Looks great. But after testing I think one seekbar height value isn't ideal. 

What do you think about:
1) Rename "MPCThemeFillSeekbarAndVolume" to "ModernSeekbar". With tooltip "Requires Dark Theme. When enabled, the time seekbar and volume indicator don't show a dragger at current position, but instead are filled from left to right."
2) SeekbarHeightModern, range 8-64, default 10.
3) The non-filled seekbar stays at existing default height (15).

**Comment by adipose** [comment]
Done, I think.

Min (8px):

image

Default (10px)

image

Max (64pixel)

image

**Pull request merged**
