### PR TITLE
support .style for srt subs

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by xLn2** [comment]
Does deleting the "Default2" style created by MPC prevent the user from intentionally forcing the "Default Style"? Would it make sense to use a more comprehensive value like "MPC Default" instead of Default2 or the default value in MPC?
The main expected thing is that the in the .style file style is applied to all subtitle lines.

Thanks for patch.

**Comment by adipose** [comment]
>Does deleting the "Default2" style created by MPC prevent the user from intentionally forcing the "Default Style"

Yes.

>Would it make sense to use a more comprehensive value like "MPC Default" instead of Default2 or the default value in MPC?

Maybe, but the "Default" is used to hijack the SSA parser to use an MPC standard style.  I could copy the old default to something else, but honestly, I think if you don't want to use the .style file, you can delete/rename it.  It's not as if the mpc default is particularly interesting.

**Comment by xLn2** [comment]
> Does deleting the "Default2" style created by MPC prevent the user from intentionally forcing the "Default Style"?
> 
> Yes. I think if you don't want to use the .style file, you can delete/rename it. It's not as if the mpc default is particularly interesting.

It might be a bit destructive behavior, In future maybe there will be some subtitle providers also create some style with srt file but users may not want it and maybe they don't have idea about style file so they basically try to use their own standart style. My point is if possible some "kind" method be used for future proof. For renaming Default you are right it is complex and not necessary. Thanks for explanation.

**Comment by clsid2** [comment]
The existence of .style file is extremely rare for .srt.
If it exists, then that is the Default style that should be used. If not, user should remove the style file.
We are not going to support non-existent use cases.

**Pull request merged**
