### PR TITLE
improvements to OSD

### PR DESCRIPTION
**Pull request by adipose**
This works better, but it has 3 problems:

1. D3D FS seems to hang if it's entered while the video is paused.
2. OSD is only drawing on the video area and not the full screen (when letterboxed)
3. OSD doesn't draw after leaving D3DFS until you resize the window.

Couldn't figure out what is causing either one, but the hang is avoided by not calling

`m_pMFVMB->SetAlphaBitmap(&m_MFVAlphaBitmap);` in `OSD.cpp`

Of course this breaks the OSD.

### CODE REVIEW

**Comment by adipose** [comment]
Fixed the first two issues.  MPC-BE has implemented an additional interface (`IMFVideoMixerBitmap`) on EVR, and the OSD was not working well with the standard interface.  I can't really identify the reason, but it may have to do with having a permanent pointer to the `IMFVideoMixerBitmap` interface.

This also fixes the issue where it couldn't draw on the letterboxed area.  I'm not sure why, but perhaps VMROSD had some additional code to adjust for that, which OSD didn't (but is handled by the custom alpha bitmap code, now).

**Comment by adipose** [comment]
Third issue is fixed.

**Comment by clsid2** [comment]
I have simplified the code in `COSD::GradientFill`. Border works better now. But transparency seems broken?

Perhaps GradientFill could be replaced with simple solidrect filling. I assume GradientFill is used for the transparency? I am fine with removing transparency support if needed.

**Comment by adipose** [comment]
> I have simplified the code in `COSD::GradientFill`. Border works better now. But transparency seems broken?
> 
> Perhaps GradientFill could be replaced with simple solidrect filling. I assume GradientFill is used for the transparency? I am fine with removing transparency support if needed.

I think gradient fill I left as-is, but I used the same color twice which should have left it solid.  Not sure about the transparency, but I can check.

**Comment by adipose** [comment]
Oh, one other note, VMR9 doesn't work with this OSD.  VMROSD had code for VMR9 but this doesn't.

**Comment by clsid2** [comment]
The exclusive mode seekbar does not cover whole width of the screen. There are ~16px of black on each side. 

The time text is light grey instead of black. The seekbar track could be darker as well. In light theme.
In dark theme the contrast of colors could also be improved for visibility (on longer distance).

**Comment by clsid2** [comment]
Works here with VMR9. Or do you mean not working with exclusive fullscreen? I am fine with removing exclusive fullscreen ability for VMR9. Those few who use exclusive mode, are likely to use EVR.

**Comment by adipose** [comment]
> Works here with VMR9. Or do you mean not working with exclusive fullscreen? I am fine with removing exclusive fullscreen ability for VMR9. Those few who use exclusive mode, are likely to use EVR.

Yes, in D3D fs.

**Comment by adipose** [comment]
> The exclusive mode seekbar does not cover whole width of the screen. There are ~16px of black on each side.

image

It's deliberate (mpc-be).   I guess the idea may be to have room to see the dragger even when all the way to the edge of the screen?  Or maybe to do with overscan tvs?

**Comment by adipose** [comment]
> The exclusive mode seekbar does not cover whole width of the screen. There are ~16px of black on each side.
> 
> The time text is light grey instead of black. The seekbar track could be darker as well. In light theme. In dark theme the contrast of colors could also be improved for visibility (on longer distance).

https://github.com/clsid2/mpc-hc/pull/2764

**Comment by adipose** [comment]
Maybe we should add some additional colors for OSD specific features.

**Comment by adipose** [comment]
> I have simplified the code in `COSD::GradientFill`. Border works better now. But transparency seems broken?
> 
> Perhaps GradientFill could be replaced with simple solidrect filling. I assume GradientFill is used for the transparency? I am fine with removing transparency support if needed.

The transparency worked for me fine.  But you obviously have to set nOSDTransparent (needs to be a number between 0 and 255, like 128).  Also the code you removed was adding 32 to the border colors.  Maybe trying to make it standout more?

**Comment by clsid2** [comment]
I tried hardcoding it to 128 yesterday, but I still get solid background. It used to work in your initial patch. I prefer the current look, but I am just curious why alpha stopped working here.

**Comment by adipose** [comment]
> I tried hardcoding it to 128 yesterday, but I still get solid background. It used to work in your initial patch. I prefer the current look, but I am just curious why alpha stopped working here.

Did you hardcode it in the gradientfill or in settings?  Because it is used it one other place, too.

image

image

**Comment by clsid2** [comment]
Just in GradientFill. Got it working now.

**Comment by adipose** [comment]
I made a simplefill function and changed the border to use the edit border color.  Looks like this:

image

```
void COSD::SimpleFill(CDC* pDc, CRect* rc)
{
    const CAppSettings& s = AfxGetAppSettings();

    pDc->SelectObject(m_brushBack);
    pDc->SelectObject(m_penBorder);

    pDc->Rectangle(rc);
}
```

**Comment by clsid2** [comment]
You can make it select between the two functions based on `nOSDTransparent > 0`.

And for `GradientFill`, perhaps the borders could be drawn solid, and use alpha just for the body. Dunno if that looks good. But would be simpler.

**Comment by adipose** [comment]
Yeah that's an idea.  By the way, I think that alpha doesn't actually do anything?

https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-gradientfill

> Note that GradientFill does not use the Alpha member of the [TRIVERTEX](https://learn.microsoft.com/en-us/windows/desktop/api/wingdi/ns-wingdi-trivertex) structure. To use GradientFill with transparency, call GradientFill and then call [AlphaBlend](https://learn.microsoft.com/en-us/windows/desktop/api/wingdi/nf-wingdi-alphablend) with the desired values for the alpha channel of each vertex.

**Comment by adipose** [comment]
Also, because the transparency is set on the window, we cannot probably control the border transparency separately.

**Comment by clsid2** [comment]
So alpha could then be set to constant 0 in GradientFill?

**Comment by adipose** [comment]
I think so...

**Comment by adipose** [comment]
Transparency 128 with simple fill:

image

**Pull request merged**
