### PR TITLE
theme fixes

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
Remaining issues:

1. Menu > Play > Filters: property dialogs have a red outline border
2. ^ Same for subtitle styles dialog
3. In Add Favorite dialog, the V on the dropdown button is barely visible.
4. On Miscellaneous page, the tracks of the color control sliders could be a tiny bit darker. Barely visible now.

I am a big fan of the green color used for the seekbar ;)

I am seriously considering making theme enabled by default (with windows default setting).

**Comment by adipose** [comment]
1. Fixed
2. Fixed
3. Noticed this, it was everywhere, fixed

For 4, do you mean this? It looks visible to me, not sure if I changed something
image

> I am a big fan of the green color used for the seekbar ;)

Haha...I stole that from explorer search progress color.  But I will change it to whatever you prefer.

**Comment by adipose** [comment]
I made the sliders darker--not sure how I chose that color, but it was the same as the scrollbar channel.  In dark theme, it wasn't the same, so I changed it to be darker now.

**Comment by clsid2** [comment]
I meant the green color is actually looking very good. No need to change, haha.

The slider track is shown as a 1 pixel thick line here (Win7). But with darker color it is visible fine now. Weird thing is that it is thicker on default style page.

Page title could maybe be improved?
mpc_misc
mpc_defstyle

**Comment by bibsp** [comment]
As you are working on theme related stuff, Can you fix a small bug in light theme of MPC on windows 11 only.
The bottom 2 corners of player is not properly rounded in light theme. There is a glitch. Dark theme is fine. It looks very weird.

**Comment by clsid2** [comment]
@adipose
Do you have PayPal? If you want I can add you to the donate page. There are lots of people willing to donate, but currently can't.

**Comment by clsid2** [comment]
Noticed another bug.
The text in OSD is messed up in light theme. The inside of the letters is transparent instead of black.

Edit: happens with vanilla EVR

**Comment by adipose** [comment]
> Do you have PayPal? If you want I can add you to the donate page. There are lots of people willing to donate, but currently can't.

Not for now, I suppose I could set one up, but I am ok for now.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2302

That's a funny one.

**Pull request merged**
