### PR TITLE
support PerMonitorV2 for dpi scaling between monitors (options dialog)

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
Awesome! I will test this later, might be no sooner than the weekend, I am not near my dev machine. Could you make a test build?

I assume that the manual scaling still works on Win7/8?

**Comment by adipose** [comment]
I think the existing windows 7/8 behavior should be preserved. Most of the new code should only take effect when permonitorv2 is allowed (win 10 1703).

I didn't test extensively on those since I don't have a two monitor system with windows 7 or 8.

**Comment by clsid2** [comment]
I can test on dual monitor Win7.

**Comment by adipose** [comment]
https://mega.nz/file/JBAShDaQ#mB1ndxlVJ__BmCLEO9v5oFbj_CfXQ7udoFQRnsSS38g

**Comment by clsid2** [comment]
What is the purpose of that dummy sheet? Windows notifies DPI changes with window message:
https://docs.microsoft.com/en-us/windows/win32/hidpi/wm-dpichanged

**Comment by adipose** [comment]
Treepropsheet size logic is done in initdialog based on initial sizes, which are dictated by dpi. When the dpi changed is received by the dragged window, all windows are resized, but not correctly.  The initdialog logic is not used, just some "intelligent" logic. For example the window is just tall enough for the tree view. Other miscellaneous glitches are due to less space calculated than is done for a window starting on that screen.

I used the dummy sheet to perform initdialog on a new sheet on the new monitor and detect the sizes. I can't reverse the calculation easily because windows has already assigned new sizes to everything before the dpi changed message.

**Comment by clsid2** [comment]
test build 100%:
dpi1_100percent
test build 150%:
dpi1_150percent
vanilla 150%
vanilla_150percent

Working good on quick test. Only issue is the page header text size. That is a bit small. Another tiny issue is that the images on the page are not scaled. But I am unsure if scaling will make them look better. Not really important.

**Comment by adipose** [comment]
So that test was opening it directly on the 150% screen, or dragging?

I'm surprised it would even look different, since most of the code should be deactivated in win7.  It almost looks like it's failing to scale some things because it expects the app to do it, but permonitorv2 should be ignored by win7...

**Comment by clsid2** [comment]
These screenshots are from Windows 10 20H1.

On Windows 7 I have only tried 100% scaling. Will test more later.

**Comment by adipose** [comment]
OK, made a bug fix for some of the base scaled values.  It worked ok when scaling from 96 to other DPIs but not other situations.  That could explain some of your differences.  It looks better in windows 7 to me, now.

**Comment by clsid2** [comment]
Accidental delete?

**Comment by adipose** [comment]
Yep

**Comment by clsid2** [comment]
Since the dummy sheet contains formats page, does that also mean that the code from that page is executed twice? Reading stuff from registry and doing file association checks. If so, maybe more efficient to use a different (simpler) page or create a dummy page?

**Comment by adipose** [comment]
Yes, a dummy page is a better solution. In early testing, other pages did not "grow" the dialog full size. I speculated it was due to the images on the far right. I haven't tested the theory, but it would be easy to make a tester.

**Comment by adipose** [comment]
@clsid2 , this is ready for further review

**Comment by clsid2** [comment]
Perhaps some of the code, like the new icon/bitmap workaround, can be skipped if DPI remains unchanged? If necessary to keep things simple, maybe just detect if DPI changed, set a global bool, and from that point forward assume everywhere that DPI might have changed when doing something.
This would at least skip unnecessary stuff on single monitor systems, or multi monitor systems with equal DPI settings.

**Comment by adipose** [comment]
> 
> 
> Perhaps some of the code, like the new icon/bitmap workaround, can be skipped if DPI remains unchanged? If necessary to keep things simple, maybe just detect if DPI changed, set a global bool, and from that point forward assume everywhere that DPI might have changed when doing something.
> This would at least skip unnecessary stuff on single monitor systems, or multi monitor systems with equal DPI settings.

The code is all called after receiving a WM_DPICHANGED event.  I'm unsure if that can occur without a real DPI change for the options window.  I do think it might happen once in the very beginning--however, I avoid that by using the initialized flag which gets set after oninitdialog is finished.

I can add additional code to only make changes after the dpi is different from the prior DPI, I suppose.  But I'm unsure if it's a real problem.  If you drag from monitor to monitor with same DPI, the event never fires.

**Pull request merged**
