### PR TITLE
show volume percentage on the volume bar, sliders lock to zero

### PR DESCRIPTION
**Pull request by adipose**
image

### CODE REVIEW

**Comment by clsid2** [comment]
Already tested it with high DPI and non-standard text scaling?

**Comment by clsid2** [comment]
Now that % is shown in the bar, the volume tooltip is redundant.

**Comment by BreakPoints** [comment]
Unless in fullscreen

**Comment by BreakPoints** [comment]
Ah, I wasn't aware there was a % tooltip for the volume slider. Doesn't show for me by default.

**Comment by adipose** [comment]
> Already tested it with high DPI and non-standard text scaling?

I tested high and low DPI.  I'll check text scaling.

**Comment by adipose** [comment]
Text scaling is not relevant to the way it scales the font.  It seems to work fine.

**Pull request merged**
