### PR TITLE
libass sse2 patch

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
Doesn't work properly. Issue with alpha?

**Comment by clsid2** [comment]
I am also wondering if the `concurrency::parallel_for` does actually help to improve the performance of the flatten function. For both sse2 and normal version. So far I have seen higher CPU usage more often for libass compared to ISR.

**Comment by adipose** [comment]
> Doesn't work properly. Issue with alpha?

Maybe so.  I didn't check to see if it inverts the alpha.

This code renders direct to the spd but xyfilter created a temporary render frame, so it probably inverts the alpha later.

**Comment by clsid2** [comment]
I had to remove the `if changed` before the flatten call to fix a problem where a subtitle sometimes would display too short. A temporary subframe, which can be re-used for multiple video frames, might have efficiency benefits.

**Comment by adipose** [comment]
> I had to remove the `if changed` before the flatten call to fix a problem where a subtitle sometimes would display too short. A temporary subframe, which can be re-used for multiple video frames, might have efficiency benefits.

Yes same here.  I think maybe if we store the subpic we can reuse it in that case.  But it has to be blitted to the video again.

Will be back in a few days to take another look.

**Comment by adipose** [comment]
> Doesn't work properly. Issue with alpha?

I couldn't get this sse2 code to work.  I had to use AlphaBlend() from xysubfilter to make use of it, but even though I have the same basic code for rendering to spd, it doesn't handle transparency correctly.  I'm nto sure if xysubfilter does, either.

```
void AlphaBlenderArgbC::AlphaBlend( const BYTE *src, int w, int h, int pitch, BYTE *dst, int dst_pitch )
{
    for(int i = 0; i < h; i++, src += pitch, dst += dst_pitch)
    {
        const BYTE* s2 = src;
        const BYTE* s2end = s2 + w*4;
        DWORD* d2 = (DWORD*)dst;
        for(; s2 < s2end; s2 += 4, d2++)
        {
            if(s2[3] < 0xff)
            {
                *d2 = (((((*d2&0x00ff00ff)*s2[3])>>8) + (*((DWORD*)s2)&0x00ff00ff))&0x00ff00ff)
                    | (((((*d2&0x0000ff00)*s2[3])>>8) + (*((DWORD*)s2)&0x0000ff00))&0x0000ff00);
            }
        }
    }
}
```

I don't understand this alphablend code.  First of all, unless I invert the alpha here (s2[3]), it doesn't work at all with the sse2 output.  If I do invert it, it works, but there's no transparency when it's expected.

I understand the left-hand parts as multiplying the alpha by the destination (existing bmp).  This should be inverted alpha, which I think is not what the sse2 code outputs... But the right-hand side is not multiplied by alpha.  Hmm, maybe it's supposed to be pre-multiplied alpha?

**Comment by clsid2** [comment]
I am not sure either. It is not important if the perf difference was small.

Currently the libass code still depends on the internal parser for timing info. See fixme here:
https://github.com/clsid2/mpc-hc/blob/d80fa0791a9e8b1946dc1a9b24d8f99eac911112/src/Subtitles/SubtitleInputPin.cpp#L516
That is something more important that needs to be improved. I don't know how other players use the libass API. Maybe just query for a sub each frame?

**Pull request merged**
