### PR TITLE
add FullScreenSeparateControls to fullscreen page

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
Screenshot?

You can leave the advanced option active for now, in case people look for it there. It can be removed in future.

**Comment by adipose** [comment]
image

**Comment by clsid2** [comment]
What do you think about "Allow separate control window" instead of "Show ..."? Or maybe "Use ..."?

**Comment by adipose** [comment]
I like "Allow" as it is not guaranteed to show up unless you have a second monitor.

Btw I did add the hover info there.

image

**Comment by clsid2** [comment]
Agree that "Allow" is better.

Also, are there many translation updates yet? I plan do a 2.3.7 release this weekend, but can wait a few days if needed.

**Comment by adipose** [comment]
Let me see about the translations.

**Comment by adipose** [comment]
I noticed something in the translations merge.  Hotkey was removed which is breaking "good" translations:

image

I could probably save all these by removing the ampersand.

**Comment by clsid2** [comment]
Yeah, I removed ampersand because it caused a ugly draw artifact in options gui.

**Comment by adipose** [comment]
Do you want me to save the existing translations and just remove the ampersand?

**Comment by clsid2** [comment]
Yes please.

In the chinese example above the whole `(&I)` can be removed.

**Pull request merged**
