### PR TITLE
support fixed starting position command line option

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
A simpler patch would be to allow to specify the coordinate of window topleft position. That also gives user a bit more flexibility in positioning.

**Comment by adipose** [comment]
> A simpler patch would be to allow to specify the coordinate of window topleft position. That also gives user a bit more flexibility in positioning.

That would indeed be simpler.  I had merged the patch here:

https://github.com/clsid2/mpc-hc/issues/1424

It didn't quite work.  One issue was it didn't pay attention to the taskbar location for upper-left.  Another was it didn't activate unless "rememberpos" was set.  But the more annoying issue to fix was the Windows 10 hidden frame issue.  Especially since that cannot be adjusted until after the window is shown.

If we let them set upper-left only, will we keep the code to address the hidden frame?  Or would we just force them to position the window at {-11,0} to get it to the borders?  I find the specific locations pretty useful because then you don't have to subtract the window size from the monitor width and then offset by 11 (or whatever it is at your DPI) for the borders.

**Comment by clsid2** [comment]
With hidden frame I assume you mean borderless window? Yes, that correction should be done internally. Users will be unaware of the weird offset being needed.

**Comment by adipose** [comment]
> With hidden frame I assume you mean borderless window? Yes, that correction should be done internally. Users will be unaware of the weird offset being needed.

Basically, yes.  https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowrect  

In windows 10 there are 11 pixels that represent the frame draggers, but they are replaced with a drop shadow.  GetWindowRect includes the drop shadow which means that the fixedsize is also probably wrong...

**Comment by adipose** [comment]
image

Yeah, so I set it to 600x600 but the actual window is only 578 x 589 due to left, right, and bottom invisible frames of 11.

**Comment by adipose** [comment]
OK, it now works with upper left position and hidden frame.

I did use the working monitor rect.

**Pull request merged**
