### PR TITLE
improvements to playlist

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
I noticed a small issue:

Give a playlist entry a long title. Then edit it. Press any letter so new title is for example "a". The editbox will be small (grows with size of new typed title) and the old title will be displayed behind the editbox.

If you make the new title super long, the editbox can grow beyond the duration value (if known and displayed). This by itself is not really a problem that needs solving. But perhaps the editbox could be given a fixed width, equal to max width at which titles are displayed? That would solve both issues.

**Comment by adipose** [comment]
The first issue I have fixed here: https://github.com/clsid2/mpc-hc/pull/1332  From testing explorer, I can see that the default behavior for this case is to not draw the text behind.  You wouldn't see it unless it were shorter, but it makes sense to hide it since the filename currently "lives" in the edit.

Second issue I think I can fix.  Explorer has the same problem, in testing:

image

I also noticed a third issue, that the right hand border of the inline edit isn't drawn.  I don't know why yet.

**Comment by adipose** [comment]
Max width is working, now, and the border is drawn correctly.  I found a fourth very minor issue that the background glitches white on the very left, when the filename gets long enough to cause ltr scrolling.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1333

Fixed the last issue.  Had to do a custom paint for the border.  I always avoided it because I didn't want to draw the text, but apparently that's not drawn by the same window!

**Pull request merged**
