### PR TITLE
support fullscreen to second monitor while showing mainframe

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by adipose** [comment]
This is not done...but it works.

**Comment by clsid2** [comment]
It does not work with MPCVR and MadVR.
VMR9 (windowed) has very poor quality scaling in fullscreen.
VMR7 crashes graphics driver when going fullscreen.

**Comment by adipose** [comment]
I am sure something of that is solvable. But we could limit to EVR-CP for now.

**Comment by clsid2** [comment]
Yes, I have a patch already to limit it to the EVR renderers. Still testing a bit.

**Comment by clsid2** [comment]
The VMR7 driver access violation also happens before your patch. I can step over it and playback continues. So unrelated and probably NVIDIA driver bug.

**Comment by clsid2** [comment]
There is a crash issue:
https://drdump.com/Problem.aspx?ProblemID=767532

The `if (m_fFirstFSAfterLaunchOnFS)` on line 11024 is the cause as it calls `ZoomWindow()` before `m_fFullScreen` value is toggled, causing infinite recursion.
That block seems unneeded, since it is checked again in line 11045. I think it is safe to remove it, what do you think?

**Comment by clsid2** [comment]
Another issue. To reproduce:
Launch player with command line parameter /fullscreen. Also enable option to launch files in fullscreen.

Pressing play will now actually exit fullscreen.

Problem code is
```
if (s.fLaunchfullscreen && !HasFullScreenWindow() && !m_fAudioOnly) {
    OnViewFullscreen();
}
```
In `OnFilePostOpenmedia()`

`HasFullScreenWindow()` returns false there. But `m_fFullScreen` is true. So missing assignment for `m_pFullscreenWnd` somewhere?

**Comment by adipose** [comment]
I encountered this loop before.  The code itself seems potentially problematic.  However, upon review my code had a bug and the issue went away.  But here is what I had noticed:

image

Note that the ZoomVideoWindow() call happens before the flag is updated.  As a result, if ToggleFullscreen() is called inside ZoomVideoWindow, the code can potentially recurse.  But it only will be called again if `m_fFullScreen` is true.  And that value should be toggling on each call to ToggleFullscreen().

Anyway, the way I fixed it before was simply to move the boolean up.

image

Note that an identical code is present in the old fullscreend3d code, too.

**Comment by adipose** [comment]
> There is a crash issue: https://drdump.com/Problem.aspx?ProblemID=767532
> 
> The `if (m_fFirstFSAfterLaunchOnFS)` on line 11024 is the cause as it calls `ZoomWindow()` before `m_fFullScreen` value is toggled, causing infinite recursion. That block seems unneeded, since it is checked again in line 11045. I think it is safe to remove it, what do you think?

The recursing code is taken from ToggleD3DFullscreen().

Code on 11038 and 11066 (currently) seems to perform the same task.  However, it is currently scoped to the second half of the if-block, applying only when `!fullScreenSecondMonitor`.  I don't think it would cover the type of fullscreen I just added.

I'm not entirely clear when it would be used.  I believe "launch on fullscreen" setting would need to be used, so I can test how that currently works.

**Comment by clsid2** [comment]
There is a second block further down:
```
bool bZoomVideoWindow = false;
if (m_fFirstFSAfterLaunchOnFS) {
    ASSERT(m_fFullScreen);
    bZoomVideoWindow = s.fRememberZoomLevel;
    m_fFirstFSAfterLaunchOnFS = false;
}
```
So that block inside `fullScreenSecondMonitor` branch can be removed as well I think?

**Comment by adipose** [comment]
What I was saying is, that second block only applies when fullScreenSecondMonitor==false.

First block (fullScreenSecondMonitor and m_fFullScreen):
```
            m_pFullscreenWnd->DestroyWindow();
            if (m_fFirstFSAfterLaunchOnFS) {
                if (s.fRememberZoomLevel) {
                    ZoomVideoWindow();
                }
                m_fFirstFSAfterLaunchOnFS = false;
            }
```
Second block ( !fullScreenSecondMonitor and  m_fFullScreen)

```
        bool bZoomVideoWindow = false;
        if (m_fFirstFSAfterLaunchOnFS) {
            ASSERT(m_fFullScreen);
            bZoomVideoWindow = s.fRememberZoomLevel;
            m_fFirstFSAfterLaunchOnFS = false;
        }
```

**Comment by adipose** [comment]
So far, in testing, launching on fullscreen isn't working at all with this option enabled.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1628

Here's a patch.  What I noticed is that that flag makes the most sense when the first attempt to fullscreen fails--i.e., the player was launched in fullscreen but it's not ready, yet.  So, to somewhat mimic the d3d code, I now exit right away if m_pMFVDC  and m_pVMRWC are both null.  This allows it to come back later when it's ready to fullscreen to the second monitor, instead of doing a partial run and setting the fullscreen flag.

**Comment by clsid2** [comment]
Launch in fullscreen works here (with current code). Except when the window is already fullscreen at launch. Using /fullscreen, without file parameter, so start by pressing play to open last used file.

**Comment by adipose** [comment]
> Launch in fullscreen works here. Except when the window is already fullscreen at launch. Using /fullscreen, without file parameter, so start by pressing play to open last used file.

I was doing with a file.  See my patch.

**Comment by clsid2** [comment]
That patch breaks it with other renderers.
I got it to work by adjusting `SetDefaultFullscreenState()`

Two remaining issues I noticed:
1) When D3D exclusive on second monitor, the clicks on mainframe are ignored. Tooltips do work.
2) Changing the fullscreen monitor to "current" while there is an existing fullscreen on second monitor causes missing video problem when exiting fullscreen, and a crash when closing.

**Comment by clsid2** [comment]
Fixed second issue.

**Comment by adipose** [comment]
Cool, nice work.  By the way, I was trying MPC-VR.  It appears there is no way to change the hwnd after AP creation?  I did try put_Owner, but still no video on second screen.

**Comment by clsid2** [comment]
Looking at the MPCVR code, I see `put_Owner()` from `IVideoWindow` interface.

**Comment by adipose** [comment]
I did try that before, but still no video on the fullscreen.

**Comment by adipose** [comment]
I noticed some additional problems.  You can zoom the main video window which causes redraw issues.  Minor stuff but the empty window needs a redraw when the size changes.

**Comment by clsid2** [comment]
Got it to work with MPCVR. Testing more now.

Resizing main window works normally here. Zoom 50/100/200% exists fullscreen, which I guess is as expected, but no redraw issue?

**Comment by adipose** [comment]
Maybe it was an artifact of another issue.  It happened while I was testing mpc-vr.  Did you get mpc-vr working in non-d3d mode?  Did you have to reset the graph?

**Comment by adipose** [comment]
Well, it's working for me with mpc-vr, now. That's strange.  

Oh, never mind--it's going fullscreen but no offscreen controls are there.

**Comment by clsid2** [comment]
Here is latest [MPCVR build](https://www.sendspace.com/file/ew34jh)

Having main window on different monitor means that the toolbar is not shown when moving mouse to bottom of the fullscreen window. Would it be possible to show it in both places? People might want that.

**Comment by adipose** [comment]
> Having main window on different monitor means that the toolbar is not shown when moving mouse to bottom of the fullscreen window. Would it be possible to show it in both places? People might want that.

Not really.  The way it works is creating a regular fullscreen window with no intelligence, and sending the video render there instead of the view window, which is embedded in the controls.  In order to show it in both places, we would need something a bit more sophisticated, like a second "lite frame" that could auto-hide the controls.  When you do normal fullscreen, it's not an issue as the toolbars are part of the same window that's showing the video.

But you have convinced me we need a way to disable this mode, otherwise there would be no way to have the controls over there.

**Comment by adipose** [comment]
Hmm, so it does work with madvr, for me, but still no mpc-vr.  Not sure why.

**Comment by clsid2** [comment]
I will add an advanced option for the separated fullscreen behavior tomorrow.

I think the only remaining issue now is the ignored clicks with D3D fullscreen.

Did you try with my MPCVR build?

**Comment by adipose** [comment]
I did try it. Using windows 11 with 4k second display. Not sure if that matters.

**Comment by clsid2** [comment]
It works in DX9 mode. With DX11 it indeed does not work here either. Must be a bug in the renderer.

**Comment by adipose** [comment]
You're a genius...turning off D3D11 fixed it!  Guess put_owner was all I needed in the first place...sigh.

**Pull request merged**
