### PR TITLE
fix blinking on PGS subtitles

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
If this works, then the real bug must be further down in that code. For example on line 600 I see a multiply by 3/4 which seems to have a similar goal.

But what exactly is going wrong now? Does a subpic time range sometimes include two frames, but it gets discarded after the first use? Or is there a gap in the timestamps of subpic X and X+1?

**Comment by adipose** [comment]
There's no gap in the timestamps.

**Comment by Aleksoid1978** [comment]
Maybe just set for PGS subs as animated - CPGSSub::IsAnimated() return true ?

**Comment by adipose** [comment]
I compared the trace with and without this fix.  Note the first blink occurs around 2 seconds, and without the fix it finds nothing to display at that time.

image

I tried changing the animated flag but it still flickered.

**Comment by adipose** [comment]
Actually that does seem to work with mpc-vr.  It seems to behave a bit strange with madvr, though.

**Comment by adipose** [comment]
Here are the subs around the time of the missing frame:

image

As you can see there is no gap.

**Comment by Aleksoid1978** [comment]
>I tried changing the animated flag but it still flickered.

I check this in MPC-BE - there is no flick with EVR-CP/MPC VR/madVR.

**Comment by adipose** [comment]
With madvr the first subtitle disappeared for a long time. Maybe something about debug mode, but it definitely looked different than MPC-VR.

**Comment by adipose** [comment]
Looks like madvr has that issue anyway.

Maybe animated is the right answer, here.  I'm not sure.  But I did find the cause of the problem, I think.  It looks like it tries to jump to the next frame if the start render time is greater than the current time. Sometimes this causes it to skip a subpic that is actually shorter than a frame in length.  I added a check to make sure it only skips if the subpic time is longer than a frame, and that seems to fix it.

I don't think it's a huge problem if it renders it anyway.  The other thread is looking for a subpic, and if it needs it, it will use it.  This is better than it just dropping a subpic for an arbitrary test, which doesn't seem quite right anyway (probably ok if the subpics are there longer than a single frame, though).

**Comment by clsid2** [comment]
Good find. Yes, if start+end falls in between two frames, then displaying it seems more logical than dropping it.

**Comment by ale5000-git** [comment]
It broke indentation.

**Comment by adipose** [comment]
I pushed another PR for the indent, thanks!

**Pull request merged**
