### PR TITLE
support per window dpi differences

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by clsid2** [comment]
This caused a small regression. The text scaling option in Windows 10 does now no longer have any effect on the statusbar text size.

**Comment by adipose** [comment]
I think it's actually caused by https://github.com/clsid2/mpc-hc/pull/625

Because of that patch, it now honors the size set in the dialog, rather than the "system" size for a status font (see GetStatusFont() in DSUtil/WinAPIUtils).  However, dialog sizes don't change with system text size, because it can mess up the layout, I think.

Since it is a fairly simple widget I could support it there by comparing the system text size to a known default font size for windows.  Or, we could revert https://github.com/clsid2/mpc-hc/pull/625.

The reason I updated it to use the parent font size was to allow the designer to control that font (read: make it bigger) so things like the unicode glyphs would display nicely for subs/lang.  Since that is not in use (currently "SUBS"), we don't need it.  We can't both honor the designer selected font size and follow windows font scaling, but we could make the designer's font size a minimum, if desired.

**Comment by clsid2** [comment]
Does it ever happen that the size of the windows scaled font is smaller than the minimum size we need? The text scaling option in Windows 10 has a minimum value of 100%.
I removed the unicode glyphs in your statusbar patch because they didn't work on my system. Could that have been due to the (too small) font size?

**Comment by adipose** [comment]
> 
> 
> Does it ever happen that the size of the windows scaled font is smaller than the minimum size we need? The text scaling option in Windows 10 has a minimum value of 100%.
> I removed the unicode glyphs in your statusbar patch because they didn't work on my system. Could that have been due to the (too small) font size?

The default size at 96dpi was too small to render the unicode picture glyphs properly. They were legible, but ugly.  I'm not sure why they didn't work on your machine, possibly you had an older font version or something. I'm on 2004.

At higher dpi it wouldn't be necessary.  Another thing we could do is make the status bar 2 font sizes larger than whatever windows is suggesting.  That way it follows the font scaling rules + 2, which is probably enough to keep anyone using font scaling happy.

**Comment by clsid2** [comment]
The glyphs were displayed as rectangles on my Win7 system, so probably missing character/glyph in the used font. Or just one of the many Unicode glitches in Win7.

I am not sure if people will like having larger default size with normal DPI.

**Pull request merged**
