### PR TITLE
Changes to allow Filters builds to work

### PR DESCRIPTION
**Pull request by adipose**
I moved the location for some extern functions so that Filters still compiles.

Simiarly, I moved regexutil to a common project as Filters did not have it in its build, causing failure.

### CODE REVIEW

**Comment by clsid2** [comment]
Move regexutil to dsutil? That is where most shared stuff is located.

**Comment by clsid2** [comment]
unistd.h is a linux header. It should not be needed.

Edit: I have committed a fix for it.

**Comment by adipose** [comment]
> unistd.h is a linux header. It should not be needed.
> 
> 
> 
> Edit: I have committed a fix for it.

I added it so zlib could stay unmodified (theoretically). A few linux libraries (fontconfig) don't support MSVC because of that dependency -- but mingw has it.

Since it's for debug only I just need a way to let it compile.

But to achieve what you did we could use preprocessor defines in the ffmpeg config.

**Comment by clsid2** [comment]
fontconfig compiles ok here?

**Comment by adipose** [comment]
> fontconfig compiles ok here?

https://github.com/ShiftMediaProject/fontconfig/tree/master/SMP

Because of unistd.h being here in the SMP version.

**Pull request merged**
