### PR TITLE
prevent hang while MediatypesDlg is open and new file is launched

### PR DESCRIPTION
**Pull request by adipose**

### CODE REVIEW

**Comment by bfoos** [comment]
I compiled and installed patch93. Tested with @clsid2 's sample file. Triggered pin connection error as expected. Opened another video using Windows Explorer and after about 30 seconds or so the error dialog disappeared and the video played. However, the GUI is still unresponsive. Taskbar thumbnail controls worked, but MPC-HC had to be killed via Task Manager.

**Comment by adipose** [comment]
Hmm.  Maybe I didn't wait long enough to close the popup. But in my testing, the second video simply never plays.

**Comment by bfoos** [comment]
Just tested same scenario with a fresh install of my compile of patch93 branch of your repo. I reset settings. First test was using MadVR, second EVR Custom Presenter. Same result as first test.

**Comment by adipose** [comment]
I can't duplicate the behavior you describe.  It has nothing to do with video renderer, it's just a modal dialog problem.  The new video needs to close the old video before it can play, but the old video is in the midst of opening, and blocks on the modal dialog.  As a result it will never finish opening and can never close.  The code then force kills the render session but the main window is never restored to its former glory by the killed modal dialog.

I tried just now with default settings, and it still is working fine for me.  Perhaps you can send a video (please include help/about).

Here is a test build that should have the fix.  If this works and yours doesn't, something is up with your build.

https://mega.nz/file/oNRXxCBL#dFdD7Orwg6oJtXuHYmFRP8hRrSSR_qIRWDKWNTMxD3Y

**Comment by clsid2** [comment]
I just made a test build myself and here it also works. New files are ignored while the modal dialog is displayed.

Can we force close the dialog in this situation? No need to keep it open if a user tries to open a different file.

**Comment by bfoos** [comment]
Yeah test build works as described above. Wonder why my compile didn't.

**Comment by clsid2** [comment]
If you switch between branches you need to do a full rebuild, otherwise things may get messed up.

**Comment by bfoos** [comment]
> 
> 
> If you switch between branches you need to do a full rebuild, otherwise things may get messed up.

I actually cloned patch93 into its own directory and compiled it, so I have no idea what happened.

***EDIT***
Ok, I figured it out. Total PEBKAC on my part. I forgot to checkout/pull patch93 so I compiled adipose's dev branch. My bad, guys. I'll be more mindful in the future.

**Comment by bfoos** [comment]
Actually compiled a proper patch93 test build this time and subsequent attempts at playing a media file while the pin connection error dialog is open are ignored.

**Comment by adipose** [comment]
> 
> 
> I just made a test build myself and here it also works. New files are ignored while the modal dialog is displayed.
> 
> Can we force close the dialog in this situation? No need to keep it open if a user tries to open a different file.

It's bad UI to close a modal dialog, but in this case I think it's a good idea.

**Comment by bfoos** [comment]
Compiled your latest commits @adipose . Pin connection error dialog is automatically dismissed when playing a subsequent file. Nice work!

**Comment by adipose** [comment]
Maybe an improvement would be to close the dialog (and possibly others) when processing any external command.

**Comment by bfoos** [comment]
I'm trying to envision all possible external commands that this would be useful for, but just can't and I am not at all familiar enough with the code to offer an informed opinion on which other dialogs this would be good for. My uninformed opinion thinks that it is a good idea though.

**Comment by clsid2** [comment]
Yes, perhaps closing code could be moved to CMainFrame::OnCopyData.

**Pull request merged**
