### PR TITLE
Read Blu-ray Disc Title from xml file.

### PR DESCRIPTION
**Pull request by lifegpc**

### CODE REVIEW

**Comment by lifegpc** [comment]
@clsid2  Now it support to ```.mpls``` file. Should I also add support to ```.m2ts``` file?

**Comment by lifegpc** [comment]
Now I just use the metadata of the first found xml file. It would be a good idea to choose the same language for metadata as the interface language, but I don't know how to do it.

**Comment by adipose** [comment]
Also see UTF8ToStringW, MultiByteToWideChar doesn't always work well.

**Comment by lifegpc** [comment]
I will see it when I have spare time.

**Comment by adipose** [comment]
@clsid2 

Saw this PR and associated issue.

Amy chance this gets approved if lifegpc merges upstream?

**Comment by clsid2** [comment]
Sure, if you can test it.

**Comment by adipose** [comment]
@lifegpc , do you want to merge this upstream?

**Comment by Ever4engel** [comment]
> @lifegpc , do you want to merge this upstream?

i think he's gone from long ago. his work need to be PR'ed to upstream.

@clsid2 what can we do?

**Pull request closed without merging**
