### PR TITLE
additional info from about dlg

### PR DESCRIPTION
**Pull request by adipose**
I'm hoping we can expand the data available here and ask people to post it with their bug reports.

This adds:
1. monitors with resolution, bit depth, and dpi.
2. Text scaling factor
3. Ansi codpage

We can add more "anonymous" info if we find it useful.

### CODE REVIEW

**Comment by xLn2** [comment]
If it's thought to work

- Inactive other GPU:
- Video renderer: + Dx9/Dx11
- Audio renderer:
- Subtitle renderer + libass options checked?
- External filters: (i.e. MPC Image source, Bass Audio etc.)

Considering that this information will generally be used on github, can like a tabular layout be given with the style (Markdown) used by?

| MPC-HC (Nightly, 64-bit) | | | |
:-: | --- | --- | --- |
| **Build information:** | Version: 2.1.5.23 (7e39cc1f2) | Compiler: MSVC v19.29.30154 | Build date: Feb 25 2024 |
| **LAV Filters:** | LAV Splitter:  | LAV Video: | LAV Audio: | 
| **Operating system:** | Name: Windows 10 (Build 22H2) | Version: 10.0.1x (64-bit) | |
| **Hardware:** | CPU: XXS CPU @ 2.80GHz | GPU: Graphics XX (driver version: XX.2127) | |

```
| MPC-HC (Nightly, 64-bit) | | | |
:-: | --- | --- | --- |
| **Build information:** | Version: 2.1.5.23 () | Compiler: MSVC v19.29.30154 | Build date: Feb 25 2024 |
| **LAV Filters:** | LAV Splitter:  | LAV Video: | LAV Audio: | 
| **Operating system:** | Name: Windows 10 (Build 22H2) | Version: 10.0.1x (64-bit) | |
| **Hardware:** | CPU: XXS CPU @ 2.80GHz | GPU: Graphics XX (driver version: XX.2127) | |
```
or tables can be divided according to headers

| Build information: |
| --- | 
| Version: 2.1.5.23 () |
| Compiler: MSVC v19.29.30154 |
| Build date: Feb 25 2024 |

FFmpeg Compiler is a required information?

**Comment by clsid2** [comment]
I prefer simple text based data. This info is used on regular forums as well.

Compiler info is not really useful anymore. So that could be removed.

Renderer info would be useful.

**Comment by clsid2** [comment]
`DpiHelper::GetTextScaleFactor()` crashes on Windows 7. Needs a `CanUsePerMonitorV2()` check?

dpihelper_crash

My monitors also show 0 DPI:
`[1920x1200 32-bit 0 DPI]`
Maybe hide DPI in case value is unknown?

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2614

Technically corewrappers isn't supported below Windows 8, but I guess it doesn't fail very gracefully.

**Comment by clsid2** [comment]
Wouldn't a Windows version check be better then?

**Comment by adipose** [comment]
Sure, we can add a windows check, I just figured the exception was more reliable since there are other API calls and I wasn't sure if Windows 8.x would always work either.

**Comment by clsid2** [comment]
You can do both version check and exception handling for safety. Just Check for Win 10, since hardly anyone uses 8.x.

**Pull request merged**
